### ISSUE TITLE
If a collection has no items, then a page that paginates that collection will not be generated. 

### ISSUE THREAD

**Issue by dospunk** [11ty/eleventy#1074]
This is not documented anywhere and happens silently, even when using debug

**Comment by Snapstromegon** [comment]
Hi,
I know that this response is late, but in the next version of 11ty (v2) there is even a new option to generate the page anyways. Together with the new feature this is now documented on the [pagination docs page](http://localhost:8080/docs/pagination/#generating-an-empty-results-page).

Since this also already documents the current behavior, I think we could close this issue.

**Comment by zachleat** [comment]
Yeah! And if you want even more info, check the two upstream PRs for this particular thing #2208 and #1698
