### ISSUE TITLE
Access Static Files Inside Static Folder

### ISSUE THREAD

**Issue by BayuAngora** [11ty/eleventy#1127]
With Hugo, all static files put together inside "static" folder. I tried to use "static" folder with 11ty, but each files inside must be accessed through ./static/file-name. How to access each static files through /file-name without any ./static/ path?

**Comment by brycewray** [comment]
In Eleventy, you have more flexibility with the directory structure. It will look in the **input** directory, which by default is the project's top level. For example, if you set `/src` as the input directory, you then can put the static files anywhere within there and refer to them as `/path/to/filename.ext` (*i.e.*, rather than `/src/path/to/filename.ext`). For more details, see https://www.11ty.dev/docs/config/ (and, more specifically, https://www.11ty.dev/docs/config/#input-directory).

**Comment by BayuAngora** [comment]
> In Eleventy, you have more flexibility with the directory structure. It will look in the **input** directory, which by default is the project's top level. For example, if you set `/src` as the input directory, you then can put the static files anywhere within there and refer to them as `/path/to/filename.ext` (_i.e._, rather than `/src/path/to/filename.ext`). For more details, see https://www.11ty.dev/docs/config/ (and, more specifically, https://www.11ty.dev/docs/config/#input-directory).

It works. Thanks.
