### ISSUE TITLE
Template render error - unexpected token: !

### ISSUE THREAD

**Issue by regenrek** [11ty/eleventy#1146]
Hi,

the following markdown runs into a Template error

````
{% highlight "html" %}
<template>
    {{ !active ? 'Click me 👍' : 'Close me ❌' }}
</template>
{% endhighlight %}
````

(event tried with ``` )

````
`Template render error` was thrown:
    Template render error: (./posts/2020-05-01-asdf.md) [Line 74, Column 8]
      unexpected token: !
```

Any ideas?

Regards

**Comment by pdehaan** [comment]
I think the issue is that even though you said it's Markdown, I believe that Liquidjs (default, but I believe you can override to Nunjucks) processses the file and thinks that you're trying to interpret that as a Liquid variable.

You might need to use `{% raw %}...{% endraw %}` to prevent liquid from processing that inner stuff.

Untested, but this might work:

```liquid
{% highlight "html" %}
{% raw %}
<template>
    {{ !active ? 'Click me 👍' : 'Close me ❌' }}
</template>
{% endraw %}
{% endhighlight %}
```

**Comment by regenrek** [comment]
Thanks @pdehaan!

I thought I could avoid the {% raw %} somehow, but since just this snippet raises the error its ok for me.
