### ISSUE TITLE
How can I move files into the root directory?

### ISSUE THREAD

**Issue by autonome** [11ty/eleventy#1147]
I have new posts since migrating to 11ty. I have old posts from pre-11ty.

The new posts are in posts and stay there, ending up at /post/{title} as normal.

The old posts have date-based permalinks I want to keep. They're in a directory called `old-posts`, eg: `old-posts/2002/03/01/index.md`.

I know I can put all those dirs in the root dir and they'll pass through... but that makes the root dir really hard to navigate, super messy.

How can I go from `old-posts/2002/...` and build to `_site/2002`?

Thanks!

**Comment by brycewray** [comment]
What if you just assign a different `input` directory (e.g., `/src/`) in `.eleventy.js`? Then the *real* root isn't as "super messy" because you'd put your content such as `post/*.*` and `old-posts/**/*.*` in `src/` while leaving the root for items like `.eleventy.js`, `_data/`, `package.json`, *etc.* (Yeah, you're just moving the "mess," but at least it's not in the root dir that way.)

**Comment by ckot** [comment]
Not sure I'm understanding right, but it sounds like you just want them to pass thru.  If that's true, you could probably add something similar to the following in your .eleventy.js   
```
    // copy contents of src/old_posts/ to _site/
    eleventyConfig.addPassthroughCopy({'src/old_posts':  '.'})
```

**Comment by autonome** [comment]
@ckot This is *exactly* what I was looking for - being able to pass `'.'`. Thank you so much!

**Comment by autonome** [comment]
> What if you just assign a different `input` directory (e.g., `/src/`) in `.eleventy.js`?

This was the first thing I tried in fork of 11ty/eleventy-base-blog, and got a bunch of errors. Thought just being able to pass through to the target dir was another route (solved above).

This way would also work in a vanilla install.
