### ISSUE TITLE
css applied on every pages

### ISSUE THREAD

**Issue by sdelon** [11ty/eleventy#1150]
Hello ! I am learning how to use eleventy and created a "training project" which can be found here :  https://github.com/sdelon/11ty-training

My main problem is that I can't make css rules apply as I woud like them to on every pages. I have created layout and a css folder, created a eleventyConfig.addPassthroughCopy('src/css') in the .eleventy.js and still, the rules only apply on the homepage.

Would someone please mind to help me on that issue ?
Thanks a lot !

**Comment by TigersWay** [comment]
Quick look... your css call is relative and so not working. Try to add a / in your header.njk.
Enjoy!

**Comment by sdelon** [comment]
Thanks for your help but what do you mean by a /. how would you proceed (sorry for this probably newb question)...

**Comment by sdelon** [comment]
I got it ! Thanks for your help !!! :-)

**Comment by Ryuno-Ki** [comment]
Hi @sdelon,

two things: Could you share your solution? Ideally with a before and after.
Then, would you close this issue since your problem got solved?

Thanks and enjoy your journey with Eleventy :-)

**Comment by sdelon** [comment]
Of course ! The problem was indeed that my css call was relative, I forgot a / in the link.

**Comment by SpotCrux** [comment]
![16419961087737598296820809544956](https://user-images.githubusercontent.com/96922970/149154636-06610525-2564-4040-bd09-3ad09c3de94c.jpg)
![16419961305262450371588458423209](https://user-images.githubusercontent.com/96922970/149154702-805becad-0fdc-4302-9a56-05d0c0ff4421.jpg)
![16419962147056457513766037241619](https://user-images.githubusercontent.com/96922970/149154928-715fec27-2032-4045-857c-5225f019e374.jpg)
Here my source code(base.njk & themes.njk) and my output.. css is not working properly . Any help please?

**Comment by pdehaan** [comment]
@SpotCrux The problem (I think, based on the screenshots) is that your layout file refers to a relative `./style.css` file, which will work for HTML pages in the same directory, but probably break when your pages are in subdirectories (such as http://localhost/themes/, per your screenshot). I'm guessing that if you open up your Net work tab in Google Chrome DevTools, you'll see that the ./style.css request is 404ing [because it'd be trying to load a /themes/style.css file].
