### ISSUE TITLE
The overall UX of docs needs to be improved

### ISSUE THREAD

**Issue by plug-n-play** [11ty/eleventy#1166]
**Is your feature request related to a problem? Please describe.**
The documentation UX is bad and needs to be improved, font used, line height, letter-spacing, effects, design, accessibility - all are in dire need to be improved, and are low hanging fruits for a better UX

**Describe the solution you'd like**
Working on atleast the color-theme, removing weird UI effects like
![image](https://user-images.githubusercontent.com/6245927/81521233-35fce400-9364-11ea-82b9-3c878ad50353.png)
and hover effects like 
![image](https://user-images.githubusercontent.com/6245927/81521286-52008580-9364-11ea-9c0f-23f4122ff250.png)
are low hanging fruits and would help end user a lot

**Describe alternatives you've considered**
I literally went away to other solutions after a very bad experience with docs. It's only a well written blog post which has drawn my interest back to 11ty. Please do consider the request

**Comment by carlos-ds** [comment]
Some questions/remarks

- Could you let us know which well-written blog post that was?
- Being more specific would help any chances of this making the cut. For example: which font combination and/or color combination would be an improvement? What would be better values for line height, letter spacing ...?
- Please keep in mind: there are people (including myself) who love the "weird UI and hover effects". Most docs are boring enough. I also love these little gems such as on https://www.11ty.dev/docs/pagination/nav/ where you can read _"Alright, you definitely read all of those right? 😇 Here’s some accessible code you definitely would have written yourself after reading those wonderful resources:"._ That stuff is real, you can feel it's written by a person. It makes me want to read the page and understand the subject, instead of scrolling to the bottom and clicking away. But ofcourse, this is very subjective, much like the request. There are obviously lots of good reasons to avoid this in documentation.

**Comment by plug-n-play** [comment]
Thanks for your reply @carlos-ds 

- https://snipcart.com/blog/11ty-javascript-static-site-generator-tutorial- this blog motivated me to try 11ty again
- Medium.com theme is one of the best UX for reading, center-aligned, without any distractions, just the focus on the content; use of a decent colour theme for code example; UX of https://vercel.com/docs is also impressive. 
-  Weird UI and effects I cited in the original issue for example are not for everyone. A community resource needs to target a wide audience. However, the content style you suggested in https://www.11ty.dev/docs/pagination/nav/ is totally perfect.

**Comment by zachleat** [comment]
Appreciate the discussion but we need more granular issues filed here about specific issues so we can discuss them on a case by case basis. Thanks!
