### ISSUE TITLE
How to access global .json data in config

### ISSUE THREAD

**Issue by Miosame** [11ty/eleventy#1231]
Is there a way to access the .json data from the global `_data` dir natively? neither `collectionApi` nor `eleventyConfig` seem to have it during `.eleventy.js` steps. You could read in the .json's yourself but I'm hoping there's already some way to not duplicate the data.

**Comment by denisbrodbeck** [comment]
You could `require("./src/_data/foo.json")` in your init code directly.

`_data` gets populated after `.eleventy.js` ran through (because that's where the framework configuration takes place).
Before that point 11ty doesn't know, where to find your `_data` directory (it's configurable), so naturally it won't be available, yet.

After that all your `_data` is available for all your templates (see [docs](https://www.11ty.dev/docs/data-js/)).

**Comment by Miosame** [comment]
@denisbrodbeck I've thought that's why it's missing, ended up doing `fs.readFileSync` + `JSON.parse` as described in OP, but require could be nice too, since it doesn't matter in this case that it'll get runtime cached, because eleventy exits out after building, thanks!
