### ISSUE TITLE
Allow for htmlTemplateEngine as an API call

### ISSUE THREAD

**Issue by cfjedimaster** [11ty/eleventy#1267]
**Is your feature request related to a problem? Please describe.**
I need to change the HTML template engine. The docs (https://www.11ty.dev/docs/config/#default-template-engine-for-html-files) show this method:

```
module.exports = {
    htmlTemplateEngine: "njk"
};
```

However, my config file is using a function to set up my configuration. If you scroll down to the next section (https://www.11ty.dev/docs/config/#template-formats), you can see 2 code samples are provided, one for setting the value as a simple config object and one using an API call, `eleventyConfig.setTemplateFormats`

As far as I can tell, there is no `eleventyConfig.setHtmlTemplateEngine`.

**Describe the solution you'd like**
An API call on eleventyConfig.

**Describe alternatives you've considered**
I don't believe there is one.

**Comment by simonsarris** [comment]
You can set it in the return object to that function. Here's an example:

```
module.exports = function (eleventyConfig) {
  // Copy images
  eleventyConfig.setTemplateFormats([
    "png",
    "jpg",
    "jpeg"
  ]);

  // do other config stuff

  return {
    // set other properties here, example:
    dir: {
      input: "src"
    },
    // set template engine:
    htmlTemplateEngine: "njk"
  };
};
```

I tested and it worked for me, if this works for you, please close the issue.

**Comment by cfjedimaster** [comment]
I agree this works, but shouldn't there be a consistent way for all settings to be set either via the return ob or an API call?

**Comment by simonsarris** [comment]
According to the docs the answer appears to be no, the `eleventyConfig` arg is to allow helper methods for configuring filters, shortcodes, advanced sorting, JS functions, and plugins, but it is _not_ for merely setting settings, which is left to the options return obj.

It's true there are two ways to do things with `setTemplateFormats` specifically, but I suspect this is to allow setting the template formats before any plugins are referenced, while then letting plugins further modify the list (with `addTemplateFormats`) before the options obj is returned, so two ways were considered needed. Since the HTML template engine (among other settings) is not additive, this would not be needed.

**Comment by cfjedimaster** [comment]
Fair enough!

**Comment by zachleat** [comment]
Upvote this one, I agree that we need to get rid of (or minimize use of) that return object: https://github.com/11ty/eleventy/issues/1502

**Comment by cfjedimaster** [comment]
I think for me the biggest issue was not knowing that your eleventy config can have both setFoo stuff AND return an object. I don't believe the docs ever show this. They tend to always show a 'complete' file demonstrating one feature at a time, which is either a setSoAndSo or returning an object. 

If I'm right, I'd like to see that explicitly called out (and can file an issue.)

**Comment by zachleat** [comment]
Long term goal is to prefer API methods for everything currently in the Configuration return object and move away from the return object altogether.

**Comment by cfjedimaster** [comment]
Ah cool. My only concern is - if long term is a very long time - may be worthwhile to add a quick note someplace in the meantime. :)

**Comment by zachleat** [comment]
Yes, absolutely! Anything that improves clarity 🙌🏻
