### ISSUE TITLE
Using Jekyll theme in Eleventy

### ISSUE THREAD

**Issue by Aiyush-G** [11ty/eleventy#1286]
Hi Everyone, 

I am looking to port my custom Jekyll theme to 11ty, what changes do I need to make to my template if any or should I just restart building from the ground up. 

Kind Regards
Aiyush

**Comment by msahyoun** [comment]
I recently move a project from Jekyll to 11ty keeping the theme with minor adjustments:

Adding _posts as a collection. In `.eleventy.js` add:
```
eleventyConfig.addCollection("posts", function(collectionApi) {
  return collectionApi.getFilteredByGlob("./content/_posts/*.md");
});
```
Iterating through posts:
Instead of 
```
{% for post in site.posts %}
  {{ post.title }}
{% endfor %}
```
do
```
{% for post in collections.posts %}
  {{ post.data.title }}
{% endfor %}
```
and so on.

As you can see there are some subtle changes needed, overall it wasn't too much work. The way I worked through it was rendering everything using 11ty and adding the missing pieces in by changing the needed section.
Stuff I needed to work on was
- using sass in my build as this is not natively supported by 11ty
- changing some of the date calculation
- changing some of the liquid variables used as data in 11ty is kept in different variables compared to Jekyll

Total effort was no more than 1day.

**Comment by scottishstoater** [comment]
@paulrobertlloyd has [this great write up](https://24ways.org/2018/turn-jekyll-up-to-eleventy/) from just shy of two years ago which explains the differences in the very similar concepts :)
