### ISSUE TITLE
Double curly braces in .11ty.js templating?

### ISSUE THREAD

**Issue by brycewray** [11ty/eleventy#1291]
If using .11ty.js templating, how does one successfully include double curly braces in a code block within Markdown (i.e., without their content disappearing when rendered)? In Nunjucks, you can use `{% raw %}` and `{% endraw %}`, but I haven't located a successful way to do this in .11ty.js. Supposedly, you can escape them out like this &mdash; `\{\{ content here \}\}` &mdash; but the backslashes appear when I try that. Help, anybody?

**Comment by denisbrodbeck** [comment]
Not sure, what this has to do with `.11ty.js` templates.
If I understand you setup correctly, you build your output made up of `.11ty.js` templates. Your content is in classic `.md` format.

So what probably happens, is that your markdown gets processed in two stages:

- first pass: nunjuck/liquid runs over your raw markdown content and replaces/expands your double `{{ ... }}`
- second pass: the pre-processed markdown content gets rendered by your markdown parser (probably `markdown-it`)

Only after that you have access to this `content` within your `.11ty.js` templates.

*If* you only want to transform your markdown files (without preprocessing them with nunjucks/liquid), you're looking for [`markdownTemplateEngine: false`](https://www.11ty.dev/docs/languages/#overriding-the-template-language) or on a folder/file basis with [`templateEngineOverride: md`](https://www.11ty.dev/docs/languages/#templateengineoverride-examples).

**Comment by brycewray** [comment]
@denisbrodbeck So are you saying that Nunjucks/Liquid templating activity is in play regardless of which templating one chooses? Just making sure I understand.

**Comment by denisbrodbeck** [comment]
> So are you saying that Nunjucks/Liquid templating activity is in play regardless of which templating one chooses?

*If* that's what you've configured 😃 It's very flexible.

Here's an example config:

```js
// .eleventy.js

const htmlmin = require(`./src/_utils/htmlmin`);

module.exports = function (config) {
  // Base Config
  return {
    dir: {
      input: `src`,
      output: `dist`,
      includes: `_includes`,
      layouts: `_layouts`,
      data: `_data`,
    },
    templateFormats: [`njk`, `md`, `11ty.js`],
    htmlTemplateEngine: `njk`,
    markdownTemplateEngine: `njk`,
  };
};
```

The snippet `templateFormats: ['njk', 'md', '11ty.js']` tells 11ty to *only* consider template/content files with this file endings.

The snippet `htmlTemplateEngine: 'njk'` tells 11ty to treat each `*.html` template file as a `nunjucks` template (this is great, because although I use nunjucks as templating engine, I name all my files `*.html` which gives me basic `HTML` syntax highlighting without any extra plugins for `nunjucks` support).

The snippet `markdownTemplateEngine: 'njk'` tells 11ty to pre-process each `*.md` file with `nunjucks` (interpreting any embedded nunjucks-syntax) and only after that to pass it on to the `markdown-it` parser. With the docs linked above you can tune (or disable) this behavior.

**Comment by brycewray** [comment]
@denisbrodbeck Thanks. I guess what I'm asking is, if the page in question is using an `.11ty.js` template and not an `.njk` template, is there a JS-only equivalent to the `{% raw %} {% endraw %}` option in Nunjucks which would allow me to show double curly brackets, as in `{{ $some_var_here }}`? As you can see, it works in GitHub's Markdown handling. 😄

**Comment by brycewray** [comment]
Well, much to my surprise, the `{% raw %} {% endraw %}` thing works in `.11ty.js` templating, too! Who'd'a thunk it? Closing.
