### ISSUE TITLE
Replace browser-sync with new dev server

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#1305]
As our fearless `browser-sync` dependency may not be maintained any longer, we may want to investigate possible replacements—as I’d rather not implement this functionality in Eleventy myself though that is a possible option.

via https://github.com/11ty/eleventy/issues/1164#issuecomment-634623476

If you’ve heard of a good alternative, please list it here!

* https://github.com/svrxjs/svrx is pretty recent
* https://www.npmjs.com/package/live-server but actually this one may be even more outdated (2 years ago) 😅
* LiveReload
  * https://github.com/mklabs/tiny-lr
  * https://www.npmjs.com/package/livereload-js
  * https://www.npmjs.com/package/livereload
* https://www.npmjs.com/package/reload

**Comment by cristianl** [comment]
I'd like to collaborate on this. I've wanted a lightweight alternative (famous last words) to browser-sync and livereload, but it seems pointless to cobble together something that doesn't integrate well with future projects and other tools. Eleventy would be an amazing stress test/launchpad for this 🤗

Ghost mode is the main selling point of browser-sync, but it seems to account for most of the dependencies, and also adds jank on some pages/devices.

---

I've seen a simpler but effective implementation (sapper I think?) using Server Sent Events instead of websockets.

[DOM injection is really great for designing in the browser](https://github.com/shakyShane/html-injector) despite some edge cases. It makes for cool demo gifs too.

**Comment by cristianl** [comment]
In the meantime, would a fork of the browsersync server package with dep bumps be acceptable?

Only `yargs@15` needs a change to code [(`version()` no longer accepts a function as its argument)](https://github.com/BrowserSync/browser-sync/blob/d6198f92cccbb1945b5a0cff1a1a3328d3f505ce/packages/browser-sync/lib/bin.ts#L46).

Tests: 466 passing / 18 pending (on current node 10, 12 and 14), same as before bumps

**Comment by brycewray** [comment]
Thanks for the heads-up, @zachleat — have replaced `browser-sync` with `svrx` for my local testing builds, and am liking it quite a bit better already.

**Comment by cj81499** [comment]
One of my favorite `browser-sync` features is cross-browser synchronization (scroll/click in one window, and other windows opened to the same page will do the same).

I hope that if `browser-sync` is replaced, we can keep that functionality. It makes cross-browser testing (chrome/firefox/safari/etc) much easier.

**Comment by brycewray** [comment]
> One of my favorite `browser-sync` features is cross-browser synchronization (scroll/click in one window, and other windows opened to the same page will do the same).
> 
> I hope that if `browser-sync` is replaced, we can keep that functionality. It makes cross-browser testing (chrome/firefox/safari/etc) much easier.

That's the "ghost mode." I guess it's an to-each-his-own kind of thing. I found it creepy until I learned it was **supposed** to do that. 😄

**Comment by sjml** [comment]
With `browser-sync` updating, are you still interested in replacing it? Given #841 and #843, is there anything else it's doing that you would prefer to keep? (Something like svrx seems to have more flexibility, for instance, while still being actively developed). 

I definitely recognize the value in not breaking what is no longer broken, though...

**Comment by rdmurphy** [comment]
👋 I was equally frustrated with `browser-sync` for similar reasons (but eternally grateful for all its years of service 🙏 ) and ended up creating [`mini-sync`](https://github.com/rdmurphy/mini-sync). It uses [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events) instead of WebSockets to simplify messaging.

It's biggest flaw is it lacks the auto-injection into HTML files that `browser-sync` has. I can work around that in my uses because they often have a JS build step as well 😅 , but if anyone has any suggestions regarding that or whether it'd work for eleventy, let me know!

**Comment by brycewray** [comment]
Re the `svrx` pacakge, note the following for now: https://github.com/svrxjs/svrx/issues/191

**Comment by TigersWay** [comment]
My little 2 cents....
I have been using a few times a potential alternative - the only "ALIVE" one I found so far - which may be worth some investigation: [Modern Web Dev Server](https://modern-web.dev/docs/dev-server/overview/) or https://www.npmjs.com/package/@web/dev-server .

**Comment by nitin2953** [comment]
Five Server https://github.com/yandeu/five-server
But some great features only work in vscode extension

**Comment by brycewray** [comment]
Looks like @zachleat has got this:

https://www.youtube.com/watch?v=wWs38M38vr8

**Comment by zachleat** [comment]
Yeah, thanks @brycewray!

Look for this at https://github.com/11ty/eleventy-dev-server soon

**Comment by zachleat** [comment]
This is ready for testing on `2.0.0-canary.1`!

https://twitter.com/eleven_ty/status/1501586773834612747

**Comment by Hammadi31381** [comment]
Is there an android alternative ??
