### ISSUE TITLE
`&` inside attributes in a pug file got escaped 

### ISSUE THREAD

**Issue by myakura** [11ty/eleventy#1345]
**Describe the bug**

if a pug document has a string `&amp;` inside attributes, then eleventy escapes the `&` part, resulting `&amp;amp;`.

**To Reproduce**

1. create a pug file with an element with an attribute containing a string `&amp;`
2. process that pug file with eleventy
3. view-source the resulting HTML file and take a close look at the attribute

**Expected behavior**
the string `&amp;` stays the same.

**Screenshots**

![screenshot of the generated html page](https://user-images.githubusercontent.com/413984/89373685-4be03200-d724-11ea-8f2a-ad1f5f83a722.png)

**Environment:**

- OS and Version: WSL2 (Ubuntu 20.04)
- Eleventy Version 0.11.0

**Additional context**
I set up the comparison at https://github.com/myakura/test--pug-entity-processing-in-eleventy

the pug file is located at [pug.pug](https://github.com/myakura/test--pug-entity-processing-in-eleventy/blob/main/pug.pug) and the generated output is [_site/pug/index.html](https://github.com/myakura/test--pug-entity-processing-in-eleventy/blob/main/_site/pug/index.html
)

for comparison, I also put a nunjucks file ([njk.njk](https://github.com/myakura/test--pug-entity-processing-in-eleventy/blob/main/pug.pug)).  the output ([_site/njk/index.html](https://github.com/myakura/test--pug-entity-processing-in-eleventy/blob/main/_site/pug/index.html
)) does not escape `&` in the `&amp;`

**Comment by samuelpath** [comment]
This seems to be pug standard behavior and has nothing to do with Eleventy that simply passes your input to the pug compiler.

If I enter your input into a random online pug converter, I get the same output that you didn't expect.

![image](https://user-images.githubusercontent.com/6030745/89543197-eb72f280-d800-11ea-9ad0-d8e8936fc1e4.png)

Here is the [relevant Pug documentation](https://pugjs.org/language/attributes.html#unescaped-attributes) that speaks to that:

![image](https://user-images.githubusercontent.com/6030745/89543446-3db41380-d801-11ea-973a-eef3a8eac308.png)

So since Pug escapes attributes content by default, you do not need to do it beforehand.

You can leave you code in Pug without escaping it yourself.

I think this issue could be closed, right?

**Comment by samuelpath** [comment]
@zachleat you may close this issue, which was a question on Pug's internals but has nothing to do with Eleventy per se.

**Comment by myakura** [comment]
@samuelpath thank you for the investigation.
I didn't know that was what pug does by default... my colleague and I were migrating build script from our own node script to Eleventy and found the issue. Perhaps something's was wrong in our old build script. Sorry for the noise!

**Comment by samuelpath** [comment]
Dear @myakura,
Please do not be sorry for the noise, I enjoyed debugging this issue since this made me learn new stuff on the Eleventy's codebase's internals 😄.
One reason there might have been different behavior between your own node script and Eleventy could be that you do not use the same Pug version?
For your information, Eleventy 0.11.0 uses Pug 2.0.4.
Kind regards from France,
Samuel

**Comment by samuelpath** [comment]
Hi @myakura, since @zachleat is very busy these days, could you close the issue yourself since you're the one who opened it? Thanks! Samuel
