### ISSUE TITLE
Excerpt not rendering markdown tags

### ISSUE THREAD

**Issue by jonathanyeong** [11ty/eleventy#1380]
**Description**
I'm getting an excerpt that contains raw markdown when I use custom front matter parsing from the docs: https://www.11ty.dev/docs/data-frontmatter-customize/.

**To Reproduce**
1. Add this config to `.eleventy.js`
```
  eleventyConfig.setFrontMatterParsingOptions({
    excerpt: true,
    excerpt_separator: "<!-- excerpt -->",
    excerpt_alias: 'my_custom_excerpt'
  });
```
2. Add  to a markdown post that has a link `[test](example.com)` in the excerpt.
3. Call the custom excerpt `post.data.my_custom_excerpt`.

**Expected behavior**
I expect the link to render as a link

**Actual behavior**
It renders the raw markdown.

**Screenshots**
<img width="864" alt="Raw markdown in excerpt" src="https://user-images.githubusercontent.com/3861088/91521800-5a49e580-e8ad-11ea-80f5-07ea2280c6f3.png">

This is the markdown:

```
Last week I wrote up a [learning plan](https://www.jonathanyeong.com/blog-posts/phoenix-elixir-learning-plan/) for Phoenix & Elixir. In this post, I wanted to add an addendum to phase 1 of the plan and give a quick progress update.
```

**Environment:**

- Mac 10.15.6
- Eleventy Version - 0.11.0

**Additional context**
There are workarounds to this issue such as creating custom shortcodes, but would love to use the frontmatter excerpt.. 

Another, consideration is to render the markdown and then strip the tags. Stripping the tags is seen in frameworks such as Hugo (via `plainify` - https://gohugo.io/functions/plainify/). And can provide a more uniform excerpt. Totally my opinion though! Feel free to ignore if it won't provide value!

**Comment by jonathanyeong** [comment]
Doing a little bit of digging because I'm curious. Looks like this is where we generate the excerpt: https://github.com/11ty/eleventy/blob/79d09607d1c2b4bcf87b2c8297c240a1eb7459a2/src/TemplateContent.js#L98. I wonder if maybe we could call a TemplateRender on that excerpt? Your guess is better than mine though!

**Comment by revelt** [comment]
The excerpts indeed come as raw markdown. But that's not a problem! Just create a markdown rendering filter and pass the value through it. That filter will become handy in other places later...

In `.eleventy.js` I'm using only:

```
eleventyConfig.setFrontMatterParsingOptions({ excerpt: true });
```

The excerpt separator is default, `---` and it's shown in template using: 

```
{{ article.data.page.excerpt | md | safe }}
```

The `| md` filter looks like this:

```js
// .eleventy.js
const markdownIt = require("markdown-it");
// ...
eleventyConfig.addFilter("md", function (content = "") {
  return markdownIt({ html: true }).render(content);
});
```

Here's my excerpt with links:

![excerpt](https://user-images.githubusercontent.com/8344688/94172164-10dbbe80-fe8a-11ea-8966-42ccfdd8d863.png)

---

I've been thinking about this; in theory, getting raw markdown gives more freedom to process the excerpt before displaying it. For example, imagine if this was corporate blog and you were asked to add different tracking tags on URL's on excerpts, so that analytics team could separate internal links in articles from same-URL links in excerpts... That could be done tweaking this `markdownIt()` call...

I don't know, it could be an issue or it could be just that we need some more documentation instructions how to create and use `md` filter on https://www.11ty.dev/docs/data-frontmatter-customize/

**Comment by Noogic** [comment]
The filter @revelt mentions solve the problem in an elegant way and with minimum complexity. And it's true, it gives more flexibility.

**Comment by jonathanyeong** [comment]
Awesome! That filter looks awesome. I'm going to close this issue since there's an elegant way to solve the problem!
