### ISSUE TITLE
Upgrade to pug 3.0

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#1391]
Migration guide: 
https://pugjs.org/api/migration-v3.html

Node 10+

**Comment by Zearin** [comment]
This would be great.  Pug 3.x offers:

* better security (`read()` Buffers instead of strings)
* better (Pug-style) filters (usable on Buffers...including binary data, such as images!)
* better iteration (support for JavaScript built-ins `Map`, `Set`, etc.)

The Pug 3 Migration Guide (linked above) covers the essentials.  Compared with most semver-MAJOR increments, it looks like a pretty painless migration.

For anyone interested, [here are the official Release Notes for Pug 3](https://github.com/pugjs/pug/releases/tag/pug%403.0.0), listing the new features I’ve summarized here.

**Comment by zachleat** [comment]
This shipped with now-available v0.12.0 instead of 1.0.
