### ISSUE TITLE
Add twig templates

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#143]
https://github.com/twigjs/twig.js
https://github.com/ericmorand/twing

Relevant: https://twitter.com/zachleat/status/1009783307364720640

Twig is popular with PHP devs, I think? Wordpress/Drupal/etc

**Comment by alexcarpenter** [comment]
This would be super helpful! I have been wanting generate a static styleguide for a Craft CMS site that relies on Twig.

**Comment by fvsch** [comment]
I like Twig a lot, but JS implementations are not that great (at least Twigjs was not in my experience, it might have gotten better and Twing might be great).

Also when you have Nunjucks I’m not sure Twig is needed at all. (Both Nunjucks and Twig are inspired by jinja2.)

**Comment by zomars** [comment]
Twing > Twig.js any day!

**Comment by ericmorand** [comment]
I'd like to contribute on this.

**Comment by iparr** [comment]
Like @alexcarpenter - I would love to use 11ty for a Craft CMS styleguide / design system. I also build out static sites using https://github.com/zimmen/gulp-twig . I like to use Twig because I used Twig in a corporate setting and still stick with it when I can for the smaller projects I work on now.

As a trial of 11ty, I tried to convert an existing Twig project into Nunjucks. It's great, but support for things like checks for iterable variables, passing variables using with, all the shorthand if? stuff, using a block more than once in a template - and a bunch of more powerful stuff I'd probably discover if I tried to convert a more complex project - is all dearly missed.

11ty seems very flexible - all my other bits and bobs fell into place - so this is the one issue holding me back. I'll still use it on a fresh project, but I already miss using it on some of my other work.

(I don't want to devalue the work that has gone into this project thus far. (Was invited to contribute my thoughts)[https://twitter.com/eleven_ty/status/1094697181024579584])

**Comment by notpushkin** [comment]
I've thought Twig templates are rather easy to port to Nunjucks – are there any critical differences?

**Comment by SimonEast** [comment]
@notpushkin - they do appear very similar on the surface, but there are some differences when you get into details. One example I encountered today was that in Twig you can pass variables into an included file, whereas in Nunjucks the include just uses the scope of the parent. iparr also mentioned some differences above.

It seems like Twig is a more mature language compared to Nunjucks.

**Comment by zachleat** [comment]
It lives! https://www.npmjs.com/package/@factorial/eleventy-plugin-twig

**Comment by iparr** [comment]
Can't wait to take this for a spin. Nice one.

**Comment by zachleat** [comment]
Full credit to @dnnsjrng!
