### ISSUE TITLE
High severity vulnerability within Eleventy

### ISSUE THREAD

**Issue by noodlesatgithub** [11ty/eleventy#1458]
After scanning my website for vulnerabilities with Snyk, I saw a high severity vulnerability deeply nested within Eleventy.

<img width="840" alt="Screenshot 2020-10-17 094352" src="https://user-images.githubusercontent.com/59432937/96325839-fd251180-105d-11eb-916e-e722d0c771fa.png">

**Comment by noodlesatgithub** [comment]
I'm not sure if I should tell the authors of the tfunk package about this, or Eleventy abaout this

**Comment by Ryuno-Ki** [comment]
Hm, @shakyShane updated [tfunk](https://github.com/shakyshane/tfunk) 4 years ago for the last time …
Same with [eazy-logger](https://www.npmjs.com/package/eazy-logger)

So best bet would be to report it to @BrowserSync team.
https://github.com/BrowserSync/browser-sync

If you do, please leave a link to the issue here! Thanks in advance.

**Comment by Ryuno-Ki** [comment]
That being said, since `browser-sync` is only used during development (and not in the produced files), the severity for Eleventy should be low.

**Comment by shakyShane** [comment]
I will address this later - thanks for bringing it to my attention

**Comment by shakyShane** [comment]
Fixed as part of `browser-sync-client@2.26.13` 👍

**Comment by Ryuno-Ki** [comment]
https://github.com/11ty/eleventy/blob/878425b035e082e152c0e53963aa6788c3fcb0db/package.json#L95

should be picked up for new installations thanks to `^` in this repo.

@zachleat Perhaps worth to bump our deps nevertheless.

**Comment by noodlesatgithub** [comment]
Thanks!
