### ISSUE TITLE
how do I limit the number of posts parsed (not displayed)?

### ISSUE THREAD

**Issue by jacobheric** [11ty/eleventy#1542]
I have a site with a few hundred posts and it takes about 10 seconds to rebuild everything with each change, which makes local development difficult. I'm a recent convert from the jekyll world where we had the config option `--limit_posts` which was great as it allowed me to do fast local dev on a small sample of posts without having to structurally change anything.  

Does eleventy have a way to limit the number of posts parsed? 

I played around with the collections api, but that only appears to allow me to slice/limit *after* all the posts are parsed.

**Comment by HugoGiraudel** [comment]
One thing you could double check is where the performance bottleneck lies. From my experience, this is relatively unlikely that the issue lies in the amount of posts you have, because the template processing from 11ty is actually super fast.

11ty has some documentation on [debugging a build](https://www.11ty.dev/docs/debugging/). I had a similar problem with 300+ pages until I realised minification was the culprit, so I disabled it in development. Maybe it’s something similar, or a specific filter/transform that takes a lot of time?

**Comment by jacobheric** [comment]
Yeah, I was in-lining and minifying css even in dev. I disabled that and now it's just over a second. I also found an `--incremental` cli option that skips writing unchanged files that shaves off a bit more time. I didn't see that one in the docs, so not sure if it's officially supported. Anyway, my builds are plenty fast now. Thanks!

**Comment by edwardhorsford** [comment]
@HugoGiraudel once you get to a couple hundred / low thousand posts, having eleventy process those templates / collections can be lots of time. If you're making lots of iterative changes, waiting 10 - 30s per build is really cumbersome.

I've made really hacky workarounds to try to limit my collections when developing locally - but I'd love a 'cleaner' way.
