### ISSUE TITLE
Modular JS and CSS

### ISSUE THREAD

**Issue by shadowtime2000** [11ty/eleventy#1544]
**Is your feature request related to a problem? Please describe.**
If you have base template layout which takes content and puts it in the body with some wrappers and stuff, there isn't a way to allow page specific JS, such as searching. Same with CSS, if some CSS is used in one page you should only have it referenced in that page.

**Describe the solution you'd like**
In templates, when `<script>`, `<style>`, `<link>` or `<meta>` tags are used, don't output them in the output and instead apply them in there appropriate positions.

**Additional context**
Enabling could be a config option and where `<script>` tags go could also be a config option.

**Comment by BPScott** [comment]
You should already be able to handle this with multiple blocks per: https://mozilla.github.io/nunjucks/templating.html#template-inheritance

In your `base-layout.njk` layout that renders you head element, add a pair of empty blocks:

```
{% block css %}{% endblock%}
{% block js %}{% endblock%}
```

Then in your page template that contains template-specific content redefine those blocks so that they contain the content that is specific to just that template

```
---
extends: 'base-layout.njk'
---

{% block css %}
<link rel="stylesheet" href="only-in-this-template.css">
{% endblock%}

```
