### ISSUE TITLE
Shortcode adds 1 to integer parameter for certain integers

### ISSUE THREAD

**Issue by tulipa42** [11ty/eleventy#1554]
Using a shortcode that just returns the value of the parameter, returns a different integer for certain integers.

1. Add the following shortcode to `.eleventy.js`
```
eleventyConfig.addShortcode("returnsint", (n) => { 
    return n;
  });
```

2. Add the following to a markdown -md-file
```
{% returnsint 9200000110451665 %} 
{% returnsint 9200000008497066 %} 
```
3. This renders as

`9200000110451664 9200000008497066` . It also happens for the number `9200000001276027`.

**Expected behavior**
I expect to return `200000110451665 9200000008497066`.

**Environment:**

- OS and Version: Linux - Ubuntu 20.04
- Eleventy Version 0.11.1

**Comment by tannerdolby** [comment]
I'm completely spitballin here, but these values are very large and when you try to store a value that is outside a data types range, it will return 1. Maybe this leftover digit `1` is whats being added to your returned numbers from the shortcode. 

I'm not entirely sure how `Number` data types in JavaScript are specified in terms of ranges for values that an `int` or `Number` can hold. But I think this is definitely deeper down in the Eleventy core logic that this issue is rooting from.

**Comment by tulipa42** [comment]
@tannerdolby It seems you are right. The maximum safe integer is [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER](9007199254740991).

As a sidenote, the "integer" is an product id, so I guess I should treat it as a string anyway.
