### ISSUE TITLE
Order in which _data .js files are loaded.

### ISSUE THREAD

**Issue by philnind** [11ty/eleventy#1582]
I have a js file in my _data folder to basically collect all posts from a JSON and then create an MD for each post. However, when using my build command this process is being run after the website has built so therefore these pages aren't visible on the front page.

Is there a way to set the order in which these data files are run? So I can run it first then continue with the build process...

**Comment by pdehaan** [comment]
I’m intrigued. You have a repo you can share?
I’ve done something similar in the past where I added an npm “prebuild” hook which scraped a 3rd party API and downloaded hundreds of daily CSV reports (fear not, it was a nightly cron job only) so I could preprocess them and add them to my 11ty sites pages to be reprocessed and written to disk with the rest of my site.

**Comment by philnind** [comment]
> I’m intrigued. You have a repo you can share?
> I’ve done something similar in the past where I added an npm “prebuild” hook which scraped a 3rd party API and downloaded hundreds of daily CSV reports (fear not, it was a nightly cron job only) so I could preprocess them and add them to my 11ty sites pages to be reprocessed and written to disk with the rest of my site.

I have added you as a collaborator...thanks for your help

**Comment by philnind** [comment]
I have resolved the above by creating a script in my package.json and then calling this script at the start of my build command as follows...

` "fetch-posts" : "node ./src/content/posts/get-posts.js",
    "start": "cross-env ELEVENTY_ENV=dev npm-run-all fetch-posts scss --parallel watch:*",
    "build": "cross-env ELEVENTY_ENV=prod npm-run-all fetch-posts scss --parallel build:eleventy css",`

**Comment by pdehaan** [comment]
Yeah, that should work (prefetching before building the 11ty site). Not sure if it will re-fetch the posts each time the server restarts due to a watch:* task, or maybe it does. :shrug:

I got the invite, but I can't see the repo anymore, so maybe you revoked collaborator already. I might remember enough from quickly glancing on my iPad to see if I can rebuild a simple test case using `fetch` and a dynamic templated string and outputting the result to the /src/posts/ directory using fs-extra's `outputFile`. My initial thought there was maybe you weren't using `await` in enough places and it was exiting the /src/_data/posts.js file before all the files were finished writing to disk. I wouldn't be able to reproduce fetching from a Heroku site+CMS, but maybe fetching+parsing an RSS feed and writing static files from that is the same general idea to see if it's a _data file timing issue or not.

**Comment by pdehaan** [comment]
@philnind Here was my general idea: https://github.com/pdehaan/11ty-random-data

The data file basically just fetches the latest breach data from HaveIBeenPwned.com API and writes some templates to disk which 11ty then parses.

In hindsight, not sure if that's the best _best_ approach, or if the _data/fetcher.js should just return the breach array from the function and then you use pagination to loop over that data/array to generate the templates. (ref: https://www.11ty.dev/docs/pagination/#paging-an-array). Maybe I'll poke at that angle tomorrow and see how different the code looks.

**Comment by philnind** [comment]
Thanks for your detailed response. I appreciate your help but don't stress too much I have it working and that's all that matters thanks again

**Comment by pdehaan** [comment]
For future travellers, here's the same approach using pagination (which is a bit cleaner): https://github.com/pdehaan/11ty-random-data/tree/pagination (and I created an unmerged PR if you want to see the code diff a bit easier).

Now the src/_data/fetcher.js file only fetches the JSON data and returns it so it can be consumed by pagination later on:

```js
// src/_data/fetcher.js
const axios = require("axios");

const MAX_BREACHES = 10;

module.exports = async () => {
  const res = await axios.get("https://haveibeenpwned.com/api/v3/breaches");
  return res.data.slice(0, MAX_BREACHES);
};
```

And my [pagination code](https://github.com/pdehaan/11ty-random-data/blob/pagination/src/breach.liquid) (with `tags` (for collection support, see below), `eleventyComputed`, pagination `alias`, custom permalinks, etc) looks like this:

```liquid
---
pagination:
  data: fetcher
  size: 1
  alias: breach
  addAllPagesToCollections: true
layout: layouts/breach.liquid
permalink: "breaches/{{ breach.Name | slug }}/"
eleventyComputed:
  title: "{{ breach.Title }}"
  name: "{{ breach.Name }}"
  domain: "{{ breach.Domain }}"
  breachDate: "{{ breach.BreachDate }}"
  addedDate: "{{ breach.AddedDate }}"
  modifiedDate: "{{ breach.ModifiedDate }}"
  pwnCount: "{{ breach.PwnCount }}"
tags:
  - breach
---

<section>
  <h1>{{ title }}</h1>
  <dl>
    <dt>Pwn Count:</dt>
    <dd>{{ pwnCount }}</dd>
  </dl>

  {{ breach.Description }}
</section>
```

And if you want a generic /breaches/ index page, you can loop over the `collections.breach` collection (since we used `tags: ["breach"]` in our pagination file:

```liquid
---
title: breaches
permalink: /breaches/
---

<ul>
{% for breach in collections.breach %}
  <li><a href="{{ breach.url | url }}">{{ breach.data.breach.Name }}</a></li>
{% endfor %}
</ul>
```

---

![](https://i.giphy.com/media/Ld77zD3fF3Run8olIt/giphy.webp)
