### ISSUE TITLE
How to paginate homepage ?

### ISSUE THREAD

**Issue by LebCit** [11ty/eleventy#1587]
Hello,

I'm **relatively new** to JAMstack world, and I really like the power and freedom of 11ty.
Using [eleventy-base-blog](https://github.com/11ty/eleventy-base-blog), I was able to create my own theme, but I'm stuck with paginating the homepage.
What I want to achieve : having the default 4 posts of eleventy-base-blog, I want the homepage to display the first 3 and be able to paginate to the fourth (e.g. I click on an older posts button and I navigate to the fourth one).
I have read the documentation about pagination and pagination navigation, and searched a lot (issues/web/YouTube) before asking.
In the starter projects [vredeburg](https://github.com/dafiulh/vredeburg) has this option, I just don't want to grab it and restart all over just for a loop that I'm unable to figure out.
Thanks in advance for your help.

**Comment by pdehaan** [comment]
@LebCit Greetings!

I created https://github.com/pdehaan/11ty-1587-pagination and hopefully that helps point you in the right direction.

You can see in the https://github.com/pdehaan/11ty-1587-pagination/blob/master/src/pages/index.liquid file that we're looping over a [custom `collections.blogRecentByTags` collection](https://github.com/pdehaan/11ty-1587-pagination/blob/96a684a60006e769f93bb9ef7c94468e8029cd16/src/pages/index.liquid#L3-L6) (which fetches all posts tagged with "blog") and sorts them in date descending order in the [.eleventy.js config file](https://github.com/pdehaan/11ty-1587-pagination/blob/96a684a60006e769f93bb9ef7c94468e8029cd16/.eleventy.js#L8). So the root /index.html page should display 3 most recent blog posts, then /1/index.html should show the next 3 newest blog posts, and finally /2/index.html should show the oldest 1 blog post (since I had 7 dummy blog posts in total). If you want to adjust the URL structure of the archives, you can change the dynamic `permalink` key in the [/src/pages/index.liquid](https://github.com/pdehaan/11ty-1587-pagination/blob/96a684a60006e769f93bb9ef7c94468e8029cd16/src/pages/index.liquid#L7) file.

The blog posts in question are in the [/src/blog](https://github.com/pdehaan/11ty-1587-pagination/tree/master/src/blog) directory, and the "blog" tag gets set automatically to each blog post using the [/src/blog/blog.11tydata.js](https://github.com/pdehaan/11ty-1587-pagination/blob/master/src/blog/blog.11tydata.js) file which acts as a [directory specific data file](https://www.11ty.dev/docs/data-template-dir/).

**Comment by LebCit** [comment]
Hello @pdehaan 😊

First of all, I would like to thank you a zillion time !
I really can't thank you enough for your time, guidance and shared experience !

As Napoléon BONAPARTE once said :
>A good sketch is better than a long speech.

This example should definitely go into the [Tutorials](https://www.11ty.dev/docs/tutorials/).
I've learned **so much** about 11ty api and how things works together just by applying and modifying it.

Thank you once again.
### MAY THE CODE BE WITH YOU !
