### ISSUE TITLE
layout not used! content == layoutContent == _layoutContent! Where is my mistake???

### ISSUE THREAD

**Issue by MrKrautee** [11ty/eleventy#1589]
firstpost.md:
```
---
summary: Why contemplating our mortality can be a powerful catalyst for change
layout: layouts/post.njk
title: This is the first example post
date: 2019-01-01T00:00:00.000Z
author: John Appleseed
metaDescription: This is a sample meta description. If one is not present in
  your page/post's front matter, the default metadata.desciption will be used
  instead.
tags:
  - tech
  - environment
  - politics
  - sport
---
Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition. Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.

Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X is on the runway heading towards a streamlined cloud solution. User generated content in real-time will have multiple touchpoints for offshoring.

## Section Header

Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line.

Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.
```
postlist.njk should render the post with layout not only the body(content)!
```	
        {% for post in postslist %}
		<section>
			{{ post.data.content | safe}}
		</section>	
	{% endfor %}
``` 
content, layoutContent and _layoutContent only contains the body without using the specified layout ...
For each single post page, the layout is used like expected!
But how can I iterate over the full rendered posts using the specified post layout???

**Comment by zachleat** [comment]
Sorry to reply super late here but layouts are typically used for wrapper content not related to a specific piece of content. This is by design.

https://www.11ty.dev/docs/collections/#how-to-exclude-content-from-collections

If you want to supply your use case for why layouts should be included (or an enhancement request to access the layout rendered content), please let me know! It would be the first request I’ve heard of this in the years this project has been going so I am interested!

**Comment by robuved** [comment]
I might have a use case but I might also go about this the wrong way. I am trying to  internationalize a one page layout site with the i18n plugin.

Before i18n, I was using `index.njk` for my index which was including the content of  serveral pages named `section_*.njk`. These were discovered through the collection system and their content was added from the `templateContent` field (as discussed in #1588).

With i18n I tried to move both the index.njk and `section_*.njk` to the `layouts` dir and then internationalize them with the i18n filter from the i18n plugin (so now they contain both the layout and the data which is added automatically through the plugin from the `data `dir). 

Then I created files for each locale (e.g. `/en/index.md` and `/en/section_*.md` for the `en` locale) and only applied the corresponding layout on each. They are otherwise empty. In this case if I ever need a custom section for a particular locale, I can copy the layout file and edit it as I see fit. 
I understand this is likely not the intended use of layouts, but I think this approach has the obvious advantage of not having to duplicate the layout across every locale unless needed.

This approach actually kinda worked after I replaced `templateContent` (which was empty because the `.md `files are empty) with `data.content` (which seemed to contain the proper layout data, but it broke the --serve option because it only built correctly the first time). However I was unable to reproduce it in a clean project so it seems like this is not reliable.

I understand the pagination plugin might serve as an alternative, but I seem to be hitting the same wall with `templateContent `not being set and `data.content` only being set to the layout contents on some of  the sections.
