### ISSUE TITLE
Unrecognized files should be copied by default

### ISSUE THREAD

**Issue by alexgleason** [11ty/eleventy#162]
11ty is very nice, thank you!

However it was quite difficult to figure out how to get a normal site with images and CSS working. I don't really understand why configuration is required for this to work, which seems to go against 11ty being a "zero config" static site server.

In virtually every project I use this for, I am going to be required to include an .eleventy.js just so images and css copy over. I suggest making this the default.

**Comment by zachleat** [comment]
Before I leave a lengthier comment, be aware that we do offer the `--templateFormats` command line option https://www.11ty.io/docs/config/#template-formats

**Comment by zachleat** [comment]
Just so we’re clear up front—defaults changes are very contentious and require careful release management. And changing eleventy to copy _everything_ would be a hell of a default to change. It could potentially leak sensitive files to production sites unintentionally.

So, I’m not sure I’m on board with changing the global default here—but I’m happy to discuss it.

My preference would be to be more surgical and include file extension types that provide some kind of value.

For example:
* adding a `css` type that optionally outputs an additional minified file.
* a `png` or `jpg` type that runs imageoptim and maybe outputs some different resolutions for srcset
* a `ttf` type that outputs `woff` and `woff2`

I’d probably be open to just including the `css` and/or a few image types by default so that they’re copied without additional configuration. But global unrecognized files seems too broad and dangerous.

**Comment by jmegs** [comment]
There are a couple of patterns I noticed that might help with this

1. Jekyll copies directories and files relative to the source dir unless they're prefixed with an underscore. `./css/` is transferred `./_secrets/` isn't

2. A lot of others have the notion of a dump dir or 'static' folder where the contents are output to the site root. ex. `./dumpDir/foo.css` becomes `./foo.css` in the output.

**Comment by zachleat** [comment]
I did a bit of work just to try this out. It’s currently in the `passthroughall` branch and is not available by default. It’s enabled using the `--passthroughall` cmd line option. It will copy everything in the input directory but will only process files that have a valid template extension.

**Comment by zachleat** [comment]
`--passthroughall` will be included with the next minor version.

**Comment by zachleat** [comment]
Fixed by https://github.com/11ty/eleventy/commit/d44bfc725e35a9339d88bb3a7f93c34b47649913
