### ISSUE TITLE
Shortcodes variables

### ISSUE THREAD

**Issue by octoxalis** [11ty/eleventy#165]
**Congrats for the 0.5 version with the new shortcodes functionality!!!**
More than ever I'm glad having prefered 11ty to Hugo...

I'm trying to elaborate on a modularized design for my shortcodes putting them in a JS file as objects with two keys, the shortcode name and the shortcode code, for instance:
`{ name: "shcodeName",
code: "<div>${innerContent}</div>" }`

Therefore I can register this shortcode as:
`eleventyConfig.addPairedShortcode(shcodename.name, function(innercontent){ return shcodename.code; });`

However, I get no variable substitution for `innerContent`, only the output: `${innerContent}` within its html div tag.
And this is not the case when directly setting: `eleventyConfig.addPairedShortcode(shcodename.name, function(innercontent){ return "<div>${innerContent}</div>"; });`

Any idea about what I'm doing wrong with `innercontent` variable?
Is variable substitution enabled in a function argument?

**Comment by zachleat** [comment]
Hmm, when `innerContent` comes to the shortcode it will already be rendered (it gives you the result of the template rendering, not the raw tags).

So it seems unlikely that either of your examples will work. What template engine are you using?

Note that in the nunjucks example in the docs, it uses JavaScript Template Literals to do variable substitution in the shortcode. Note the backticks instead of quotes for strings.

https://www.11ty.io/docs/languages/nunjucks/#paired-shortcode

Read more about Template Literals: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

Please reopen the issue if you have more questions!

**Comment by octoxalis** [comment]
I'm using Nunjucks engine and backticks template literals, as in the Nunjucks paired shortcodes example (unlike the code of my issue#165).
I confess that I've to refresh my memory about template literals to probably find what's wrong in my code.
Thanks for helping!
