### ISSUE TITLE
Posts in the future have read-only file permissions

### ISSUE THREAD

**Issue by stanlemon** [11ty/eleventy#1653]
**Describe the bug**
Posts with a future date and permalink have read-only file permissions.

**To Reproduce**
Create a file with frontmatter like:

```markdown
---
layout: post
title: Post
date: 2021-03-04T10:00-04:00
permalink: /2021/03/04/post-in-the-future
---

Hello!
```

When you serve this page up the file will be written to disk with read-only permissions, which will result in the browser downloading the page.

For example:

```shell
❯ ls -lsah _site/2021/03/04
total 16
 0 drwxr-xr-x  3 stan  staff    96B Feb 21 16:03 .
 0 drwxr-xr-x  3 stan  staff    96B Feb 21 16:03 ..
16 -rw-r--r--  1 stan  staff   7.5K Feb 21 16:03 sanctus-org-javascript-edition
```

You can see this in action on my site:
https://github.com/stanlemon/stanlemon.github.com

When this file is processed it has read-only permissions:
https://github.com/stanlemon/stanlemon.github.com/blob/master/_posts/2021-03-04-sanctus-org-javascript-edition.md

Which causes the browser to download the file here:
https://stanlemon.com/2021/03/04/sanctus-org-javascript-edition

**Expected behavior**
Permissions match those of posts created in the past.

For example:

```shell
❯ ls -lsah _site/2021/02/04
total 0
0 drwxr-xr-x  3 stan  staff    96B Feb 21 16:03 .
0 drwxr-xr-x  4 stan  staff   128B Feb 21 16:03 ..
0 drwxr-xr-x  3 stan  staff    96B Feb 21 16:03 super-bowl
```

**Environment:**

- OS and Version: macOS 11.2.1
- Node Version: v14.15.5
- Eleventy Version: 0.11.1

**Comment by pdehaan** [comment]
I'm slightly confused. I can somewhat reproduce the issue locally (using built-in <kbd>npm run serve</kbd> script and local webserver). 

I _think_ the problem is that your file has a `permalink: /2021/03/04/sanctus-org-javascript-edition` without a trailing `/`, so it tries to create an extensionless file named "sanctus-org-javascript-edition" vs a folder named sanctus-org-javascript-edition/" with a nested "index.html", like your other blog posts.
After I add that trailing "/" to the `permalink` and run <kbd>npm run build</kbd> then <kbd>npm run serve</kbd>, I can see http://localhost:3000/2021/03/04/sanctus-org-javascript-edition/ fine.

A quick little `grep` shows that it seems to be the only blog post in ./_posts/ that doesn't have a trailing `/` for the `permalink`:

```sh
grep -irn "permalink:" _posts | grep -Ev "/$"

_posts/2021-03-04-sanctus-org-javascript-edition.md:9:permalink: /2021/03/04/sanctus-org-javascript-edition
```

**Comment by stanlemon** [comment]
Oh my. I am so embarrassed. I was racking my brains on this. What a silly mistake. Thank you so much!

**Comment by pdehaan** [comment]
Don’t be embarrassed, it was a very tricky and subtle bug.

I was wondering if Eleventy should have warned you on a weird `permalink` value, but possibly that’s out of scope for Eleventy (since I vaguely recall some other thread about somebody explicitly wanting no extensions on file names).
