### ISSUE TITLE
Adding comments to documentation pages

### ISSUE THREAD

**Issue by octoxalis** [11ty/eleventy#169]
For one of the blogs I'm building using Eleventy, I've chosen [Hypothesis](https://web.hypothes.is), based on the annotation standards for digital documents developed by the [W3C Web Annotation Working Group](https://www.w3.org/annotation/), as a commenting system. It is not only very simple to add to my pages (a simple [script link](https://web.hypothes.is/for-publishers/#embedding) to add), but also very efficient and powerful.
I think that adding this web annotation tool to Eleventy documentation would be of great value, to be able to  add comments (questions, solutions, code snippets, etc.) to every page.

**Comment by zachleat** [comment]
Hmm, I’m not sure. I browsed around a bit on the site and wasn’t even able to see a demo without installing a browser extension. Strange that the service would place a larger burden on the end user than on the site owner!

I’m very wary of adding third party JavaScript to the documentation. Performance is a huge concern and privacy concerns are a close second. I’ve even been thinking about removing that GitHub star widget we have on there now.

I do like the idea but I think I’m going to have to decline this one for now—in part for the performance of the site and also because I’d like to funnel questions to GitHub issues if possible. Some of this was discussed in #149.

Sorry!
