### ISSUE TITLE
unable to install eleventy-plugin-rss with v0.12.1

### ISSUE THREAD

**Issue by huphtur** [11ty/eleventy#1703]
**Describe the bug**
Tried to install official RSS plugin after upgrading to v0.12.1 and got some errors.

**To Reproduce**
`npm install @11ty/eleventy-plugin-rss --save-dev`

**Error log**
```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: 11ty12@1.0.0
npm ERR! Found: @11ty/eleventy@0.12.1
npm ERR! node_modules/@11ty/eleventy
npm ERR!   dev @11ty/eleventy@"^0.12.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @11ty/eleventy@"^0.11.0" from @11ty/eleventy-plugin-rss@1.1.0
npm ERR! node_modules/@11ty/eleventy-plugin-rss
npm ERR!   dev @11ty/eleventy-plugin-rss@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/mappelman/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mappelman/.npm/_logs/2021-03-19T23_58_36_331Z-debug.log
```

**Environment:**
- OS and Version: macOS Big Sur 11.2.3 + Node v15.2.1
- Eleventy Version: 0.12.1

**Additional context**
Tested all other official plugins, they all seem to install fine.

**Comment by dafiulh** [comment]
I think it's because `eleventy-plugin-rss` uses Eleventy [`^0.11.0`](https://github.com/11ty/eleventy-plugin-rss/blob/master/package.json#L36) as peer dependency.  Meaning that it will only work with Eleventy `0.11.x` according to [this semver rule](https://github.com/npm/node-semver#caret-ranges-123-025-004).

Maybe we should update the required Eleventy peer dependency to a looser version like the one in [this plugin](https://github.com/11ty/eleventy-plugin-syntaxhighlight/blob/master/package.json#L37)? @zachleat
