### ISSUE TITLE
Can't install eleventy globally

### ISSUE THREAD

**Issue by DavosMarsha** [11ty/eleventy#1746]
**Describe the bug**
Can install eleventy locally but not globally

**To Reproduce**
1. npm install -g @11ty/eleventy
2. eleventy -version
3. eleventy --version
bash: eleventy: command not found

**Expected behavior**
expected to see version and be able to build

**Screenshots**
![image](https://user-images.githubusercontent.com/47117266/115941278-bc75dd00-a472-11eb-9417-36d008ca0b12.png)
![image](https://user-images.githubusercontent.com/47117266/115941290-c8619f00-a472-11eb-86d9-2a27ec9b01c9.png)

**Environment:**

- OS and Version: [e.g. Windows/Mac/Linux] Mac Big Sur
- Eleventy Version [via `eleventy --version` or `npx @11ty/eleventy --version`]

**Additional context**

**Comment by pdehaan** [comment]
@DavosMarsha It might also depend on how you installed Node/npm (for example, Homebrew, nvm, and other installation methods might put the global packages in different locations, and you'll need to make sure your $PATH includes that directory).

See https://flaviocopes.com/where-npm-install-packages/ 

Personally I like installing packages locally in the project's package.json so I know which version it will be using if myself or somebody else clones a project; versus everybody potentially having slightly different versions of @11ty/eleventy installed globally.

**Comment by DavosMarsha** [comment]
@pdehaan I read the docs, little swril on steps forward.

" might also depend on how you installed Node/npm" ----- Node lives /users/.node

"and you'll need to make sure your $PATH includes that directory" ---- not sure what path / how to proceed?

"Personally I like installing packages locally in the project's package.json " ---- makes a lot of sense but I don't have a package.json, should I create one or install Node in this project and then that will create package.json?

**Comment by pdehaan** [comment]
I use [nvm](https://github.com/nvm-sh/nvm), and haven't installed Node via Homebrew or directly from https://nodejs.org/en/download/ in a while, so I might be a bit rusty on how to set it up. My main development is on an Intel-based MacBook Pro w/ 10.15.7 (Catalina), but I remember it was a bit trickier setting it up a long time ago on a BigSur M1 Mac Mini (so might further be complicated by your system, or maybe they've all fixed M1 support now that its a lot older).

Re: installing, the 11ty docs do a great job of setting up a new project w/ 11ty: https://www.11ty.dev/docs/getting-started/#step-2-install-eleventy

```sh
# Create a new package.json with defaults
npm init -y

# Install Eleventy as a devDependency
npm install --save-dev @11ty/eleventy 
```

They also have an excellent section on installing globally (and why it's discouraged) https://www.11ty.dev/docs/global-installation/

The docs also have a section on using <kbd>npx</kbd> to run 11ty (and some pitfalls): https://www.11ty.dev/docs/usage/
Personally, I don't really like that usage of npx, so I rely on package.json `scripts` instead for my local installation:

```js
"scripts": {
  "build:dev": "MAX_PAGES=2 eleventy",
  "build:prod": "eleventy",
  "serve": "eleventy --serve",
  "test": "echo \"Error: no test specified\" && exit 1"
},
```

So instead of having to run <kbd>npx @11ty/eleventy --serve</kbd>, I just have to remember <kbd>npm run serve</kbd>. Plus, depending on your IDE, they might have support for running package.json scripts directly. I use VS Code and there is a little sidebar panel where I can run any of my scripts with a click of a button (which is much faster than typing commands in Terminal/iTerm).

![package_json_—_11ty-post-slice_and_loadtests_py_—_molotov-tests](https://user-images.githubusercontent.com/557895/115964703-92f09c00-a4da-11eb-967e-a0fbea6dcc0c.png)

**Comment by pdehaan** [comment]
And just for fun, I installed @11ty/eleventy globally (but again, I'm using **nvm** so it probably handles all the paths and global installation differently than other installations):

```sh
# Let's see what I have installed globally currently. (Only `npm`)
npm ls -g --depth 0
> /Users/pdehaan/.nvm/versions/node/v14.16.1/lib
> └── npm@6.14.12

# Install latest "canary" prerelease build of 11ty globally.
# NOTE: I don't recommend this and would say stick with the stable 0.12.x channel for production work.
npm i @11ty/eleventy@canary -g

> /Users/pdehaan/.nvm/versions/node/v14.16.1/bin/eleventy -> /Users/pdehaan/.nvm/versions/node/v14.16.1/lib/node_modules/@11ty/eleventy/cmd.js
> + @11ty/eleventy@1.0.0-canary.15
> added 374 packages from 362 contributors in 19.979s

# Confirm it's installed globally (and see where it installed to).
eleventy --version # 1.0.0-canary.15
which eleventy # /Users/pdehaan/.nvm/versions/node/v14.16.1/bin/eleventy

# Check to see what we have installed globally. (Both `npm` and `@11ty/eleventy` now)
npm ls -g --depth 0
> /Users/pdehaan/.nvm/versions/node/v14.16.1/lib
> ├── @11ty/eleventy@1.0.0-canary.15
> └── npm@6.14.12
```

**Comment by DavosMarsha** [comment]
@pdehaan thank you so much! The info on the package.json and the scripts within VS Code really is helpful.

**Comment by DavosMarsha** [comment]
We can close this issue if you like, I'm in a great place thank you again for the help.
