### ISSUE TITLE
Unable to access collection data when using variable collection name

### ISSUE THREAD

**Issue by mhayes57** [11ty/eleventy#1788]
**Describe the bug**
I am unable to get a property from the collection data object when I try to access the data object from a variable collection name. This is occurring on a page with pagination, but not sure if that is related to the problem. It is odd because I can access the collection fields outside of the data object when I use a variable, but cannot access the parameters inside the data object. Apologies if this is something obvious as I am not a javascript developer, and am new to eleventy but I have banged my head against this for hours and it seems like it might be a bug in eleventy.

**To Reproduce**

1. I created the following  simple markdown page (Using ejs for template processing)  in order to output a list of articles associated with a variable tag:
``` js
---
title: Tag Articles
layout: layout.ejs
tags: _pages
pagination:
  data: collections
  size: 1
  alias: tag
permalink: /tags/<%- tag %>/
---
## Articles associated with <%= tag %>:
<% let length = collections[tag].length %>
<div>
<% for (var i = 0; i < length; i++) { %>
  <% let articleURL = collections[tag][i]["url"] %>
  <% let articleTitle = collections[tag][i]["data"]["title"] %>
  <p> <%= articleURL%> </p>
  <p> <%= articleTitle %> </p>
<% } %>
</div>
```
{END OF PAGE}

**Expected behavior**
Expected this to output the collection URL and the title from the collection data object. 

** Actual **
```js
`TemplateContentRenderError` was thrown
> ./src/tag_articlesBug.md:6
    4| <% for (var i = 0; i < length; i++) { %>
    5|   <% let articleURL = collections[tag][i]["url"] %>
 >> 6|   <% let articleTitle = collections[tag][i]["data"]["title"] %>
    7|   <p> <%= articleURL%> </p>
    8|   <p> <%= articleTitle %> </p>
    9| <% } %>
Cannot read property 'title' of undefined
```

** Notes **
1. If I remove the lines with articleTitle, I am able to get the expected articleURL values using the collections[tag] variable. So it seems the collection object can be accessed via the variable, but not the data object properties.
2. If I replace collections[tag] with a literal tag value, then I can get the expected url and the title value from the collections data object. For instance, if you have a tag called "books" then the replacing the following (everything outside the frontmatter) will work:

```js
## Articles associated with <%= tag %>:
<% let length = collections["books"].length %>
<div>
<% for (var i = 0; i < length; i++) { %>
  <% let articleURL = collections["books"][i]["url"] %>
  <% let articleTitle = collections["books"][i]["data"]["title"] %>
  <p> <%= articleURL%> </p>
  <p> <%= articleTitle %> </p>
<% } %>
</div>
```

**Environment:**

- OS and Version: Ubuntu 20.04
- Node Version: v14.16.1
- Eleventy Version: 0.12.1 

** Additional Comments **
1. While debugging this, I output a the typeof the collection[tag]["data"] object and it came back as an object, and it would not throw an error if I just tried to access the data object, but as soon as I tried to access the title or date or other data properties it throws the error and indicates that the data object is undefined.

**Comment by mhayes57** [comment]
Sorry, this was my first github issue and it seems the code got formatted such as to be barely readable. Let me know if you need me to upload a file.

**Comment by pdehaan** [comment]
Interesting. I'm not very familiar w/ EJS template engine, but it looks like this works w/ LiquidJS in Markdown as expected:

```md
---
title: Tag Articles
tags: _pages
pagination:
  data: collections
  size: 1
  alias: tag
permalink: /tags/{{ tag | slug }}/
---

# Articles associated w/ {{ tag }}

{%- for post in collections[tag] %}
- [{{ post.data.title }}]({{ post.url | url }})
{%- endfor %}
```

**Comment by pdehaan** [comment]
This might work... Turns out I was getting the same error as you, but seemingly because a couple of my pages didn't have `title` attributes defined in the frontmatter because reasons.

```ejs
---
title: Tag Articles
tags: _pages
pagination:
  data: collections
  size: 1
  alias: tag
permalink: /tags2/<%- tag %>/
---

Articles associated with <%= tag %>:
<% let pages = collections[tag] %>
<% pages.forEach(function (page) { %>
  <a href="<%= page.url %>"><%= page.data?.title || "No title" %></a>
<% }); %>

{END OF PAGE}
```

I think you might also be able to do without that intermediate `<% let pages = collections[tag] %>` tag, and just loop over the pages directly using the following (if you want to reduce it by one line of code):

```ejs
<% collections[tag].forEach(function (page) { %>
  <a href="<%= page.url %>"><%= page.data?.title || "No title" %></a>
<% }); %>
```

**Comment by pdehaan** [comment]
@mhayes57: Sorry for my brief responses last night (it was late).

---

> this was my first github issue

Congrats on a big milestone!

---

> it seems the code got formatted such as to be barely readable

When dumping huge blocks of code, it's often useful to put them in a code block:

<pre><code>
```js
// Big code block goes here
```
</code></pre>

Otherwise, the frontmatter delimiters and other characters might get interpreted as Markdown and everything ends up as an H1 or H2 or `<hr>` tags.

---

> I am not a javascript developer, and am new to eleventy

```ejs
<% let articleTitle = collections["books"][i]["data"]["title"] %>
<%= page.data?.title || "No title" %>
```

What I _think_ is/was the problem is that one of your posts doesn't have a "data" property defined for some reason. I would have assumed that would happen automatically, but 🤷 .

From the looks of your error message, we know it's coming from ./src/tag_articlesBug.md:6 template, which is:

```ejs
<% let articleTitle = collections[tag][i]["data"]["title"] %>
```

It'd probably take some debugging to see if we could figure out which exact file that we're looping over in a collection has a missing value. I can help you debug if you have a public repo, but otherwise, I think my workaround might work.

What is `<%= page.data?.title || "No title" %>`?

The `?.` is a newish [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining), which "enables you to read the value of a property located deep within a chain of connected objects without having to check that each reference in the chain is valid." (to quote MDN docs).

So, in our case above, it is essentially saying "return the `page.data.title` value, but if the `data` property is [nullish](https://developer.mozilla.org/en-US/docs/Glossary/Nullish) (`null` or `undefined`) it will return `undefined` early instead of trying to access the `.title` property on an undefined object and throwing an error. The `|| "No title"` is just a cheap way of saying "if the left hand part of this expression is [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy), return this string as a default value". For more information, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR.

**Comment by mhayes57** [comment]
@pdehaan Thank you so much for the helpful suggestions, I will review your suggestions and update this ticket soon.

**Comment by mhayes57** [comment]
@pdehaan, Your solution solved my issue. Thank you so much for your generous time and advice. Cheers!
