### ISSUE TITLE
Unexpected pagination.pageNumber behavior

### ISSUE THREAD

**Issue by EatonZ** [11ty/eleventy#1888]
**Describe the bug**
When accessing `pagination.pageNumber` in a paginated post, it doesn't seem to represent the actual page number. It seems to represent the index of the paginated post in the collection, making it seemingly impossible to find out the page number the post is in.

**To Reproduce**

1. [Download this sample project](https://github.com/11ty/eleventy/files/6796057/Headless-WordPress-11ty-main.zip) and run `start`.
2. The top of the page will list 5 posts. Click on one, like the 3rd one.
3. Under the header, it will say _**This post is on page 2**_.

**Expected behavior**
It should say _**This post is on page 0**_.

**Environment:**

- Windows 10
- Eleventy Version 0.11.1

**Comment by pdehaan** [comment]
I'm a bit lost here since I think I'm seeing two sets of pagination here&hellip;

So, if I put `{{ pagination.pageNumber }}` in index.njk, it will correctly say "page 0" or "page 1" since there are only two pages (with 5 links each since `size:5`) worth of content (or 10 total posts from the API).

```yaml
---
# index.njk
pagination:
  data: posts
  size: 5
layout: layout.njk
title: Latest Posts
---
```

posts.njk already has some `This post is on page {{ pagination.pageNumber }}` debugging, and if I click the "next" button on the /index.html page (re: http://localhost:8080/1/) and then click on a result I see:

```
Doctorow on&nbsp;IP
This post is on page 8
```

But I think that is expected, per the front matter and the pagination `size:1` for rendering individual posts from the data file (and posts.njk would have no idea what pagination page size is being used in index.njk):

```yaml
---
# posts.njk
pagination:
    data: posts
    size: 1
    alias: posts
permalink: "posts/{{ posts.title.rendered | slug }}/"
layout: layout.njk
---
```

So in that case, the individual page is page 8 (of 10).

In the context of index.njk pagination (`size:5`), the post is on page 1, but in the context of the posts.njk pagination (`size:1`), the post is on page 8.

I think this is all working correctly (since you're using pagination in two different places with two different page sizes; so each one is correct in isolation).

---

If you want to use pagination `size:1` on the posts.njk, but have it still report page 0 or 1 (to match the pagination values in index.njk), you might be able to use a custom filter [which calculates the page number based on an arbitrary page size] to do what you want:


```js
// .eleventy.js snippet
eleventyConfig.addFilter("nested_pagination", (pageNumber = 0, perPage = 1) => Math.ceil((pageNumber + 1) / perPage));
```

Then in your .njk template, pass the desired pagination size you want to use to calculate the revised page number:

```njk
<p>Tweaked page number {{ pagination.pageNumber | nested_pagination(5) }}</p>
```

So if your posts.njk pagination `size` is 1, and you're on the 8th page of the collection, it'll try calculating that as:
`Math.ceil((8 + 1) / 5)` or `Math.ceil(9/5)` or `Math.ceil(1.8)` or `2`


| `pagination.pageNumber` | nested_pagination `perPage` | tweaked page number
|----:|:-----:|-----:|
| 0 | 5 | `Math.ceil((0+1)/5)` or **`1`**
| 1 | 5 | `Math.ceil((1+1)/5)` or **`1`**
| 2 | 5 | `Math.ceil((2+1)/5)` or **`1`**
| 4 | 5 | `Math.ceil((4+1)/5)` or **`1`**
| 5 | 5 | `Math.ceil((5+1)/5)` or **`2`**
| 7 | 5 | `Math.ceil((7+1)/5)` or **`2`**
| 9 | 5 | `Math.ceil((9+1)/5)` or **`2`**
| 10 | 5 | `Math.ceil((10+1)/5)` or **`3`**
| &hellip; | &hellip; | &hellip;

**Comment by EatonZ** [comment]
Hi @pdehaan, thanks for your in-depth comment!

> I'm seeing two sets of pagination here

Is anything the sample project doing incorrect? Is there another way to access the paginated post data in `posts.njk`?

> you might be able to use a custom filter [which calculates the page number based on an arbitrary page size] to do what you want:

I had thought about using a little math, but wanted to check if this was intended behavior before I added a workaround.

**Comment by pdehaan** [comment]
> Is anything the sample project doing incorrect? Is there another way to access the paginated post data in posts.njk?

No, I think the sample project is good and nothing wrong with the approach.
I can’t think of a way to have a paginated collect be aware of a different pages paginated info and don’t see anything wrong with using a custom filter (or whatever else) to get the paging info you want. Only potential issue that came to mind is that if you ever change the pagination page `size` from 5 to something else, you’ll need to remember to change it in at least 2 places.

**Comment by EatonZ** [comment]
Ok, then since this doesn't seem to be a bug, and I have an acceptable solution in place, I'll close this.
Thank you for your help!
