### ISSUE TITLE
Include outputPath for serverless templates when passed through a transform

### ISSUE THREAD

**Issue by BenDMyers** [11ty/eleventy#1901]
**Is your feature request related to a problem? Please describe.**
I have a transform that I'd like to apply to all of my HTML output, including serverless templates. This transform uses the `outputPath` to ensure that it only applies that transform to HTML output. However, for my serverless templates, both the pre-1.0 `outputPath` argument and the post-1.0 `this.outputPath` property are `undefined`, causing the transform to throw an error.

I could remove that check in the transform, but it feels like that would risk applying my changes to non-HTML output.

**Describe the solution you'd like**
`this.outputPath` could be populated with the on-request address the user hit, or where the HTML output would be written in an on-demand builder context (a la #1877), or maybe even set to just `".html"`. This would reduce the changes required for preexisting transforms.

**Describe alternatives you've considered**
In #1877, you mention that it's odd to specify `outputPath` when a file isn't necessarily being _written_ to that path. We could have a `this.outputExtension` property alongside `this.inputPath` and `this.outputPath` that's always supplied. This way, regardless of whether we write the output to disk or not, transforms can always safely check `this.outputExtension === 'html'`.

**Additional context**
Current transform logic, which attempts to reconcile pre-1.0 and post-1.0 `outputPath`s:

```js
function myTransform(content, legacyOutputPath) {
    const outputPath = this.outputPath || legacyOutputPath;

    if (!outputPath.endsWith('.html') {
       return content;
    }

    // We know it's HTML; do HTML transformations
}
```

**Comment by zachleat** [comment]
Had a go at this and I’m not sure there is an obvious path forward here, unfortunately.

There just isn’t a clean way to determine the output of the content from a serverless path, we would need to add something to help here.

**Comment by zachleat** [comment]
I will say that the standard --json and --ndjson modes make more sense to have an outputPath because they operate the same as the standard build (without writing but with all of the same behavior as if a write would happen).

All this hesitation to say, I’m not sure here.

Thinking out loud:

If your serverless permalink was `/:color/index.html` you could test the URL.
If your serverless permalink was `/:color/` would that be the same as above? My hunch is no.
If your serverless permalink was `/:color/` could we imply an HTML output? I don’t think so.

The Content-Type returned from `render` in the default serverless bundle file is HTML by default: https://github.com/11ty/eleventy/blob/21630bfc292a5d42cf61b86f3b51841419c7cd67/src/Plugins/DefaultServerlessFunctionContent.js#L19

Okay, I think I’m making mental progress here 😅

I think we should allow overriding the default content type of (serverless?) templates and we can key off of that for a new `outputFormat` property.

**Comment by zachleat** [comment]
Unfortunately I’m going to punt this out of 1.0 for now, I think this is a new feature and really trying to get to 1.0.

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by BenDMyers** [comment]
Makes sense to me — thank you so much for looking into this, @zachleat! I really appreciate the time.

In the meantime, could we adjust the serverless docs to call out that you won't be able to use transforms and serverless at the same time if the transforms depend on the `outputPath`?

**Comment by zachleat** [comment]
I put a note on the transforms docs on the config page and will add something more to the serverless page too!

**Comment by BenDMyers** [comment]
Thank you!

**Comment by zachleat** [comment]
Removing from the enhancement queue, per retirement of serverless plugin https://www.11ty.dev/docs/plugins/serverless/
