### ISSUE TITLE
getFilteredByGlob() doesn't work when custom dir.input is used

### ISSUE THREAD

**Issue by awei01** [11ty/eleventy#191]
When changing the `.eleventy.js` `dir.input` configuration path, the `getAll()` function doesn't seem to work properly. 

Please see this repo for reproduction:  https://github.com/awei01/eleventy-getAll-issue. Hopefully, you can understand what's going on.

**Comment by awei01** [comment]
Ok, I think the issue is with the `glob` pattern. The `item.inputPath` with which the `glob` pattern is to be matched is the full path from the project root. 

Perhaps a note should be added to the documentation.

**Comment by jevets** [comment]
I do have a case where I'm consuming data outside of the `config.dir.input` folder, so I'd vote against automatically prepending `dir.input` here, though I do see the value.

**Comment by awei01** [comment]
The responsible code is here: https://github.com/11ty/eleventy/blob/master/src/TemplatePath.js#L85-L96

One can work around the issue by using an absolute path.

**Comment by zachleat** [comment]
Ah sorry @awei01 it looks like your link context got lost with some code changes?

**Comment by zachleat** [comment]
Thanks for the excellent issue! I think the root cause here is at:
https://github.com/11ty/eleventy/blob/e4435f6ca1010eeae45d6ea9f3e23a48e5b6a33c/src/TemplateCollection.js#L42

I believe your diagnosis is correct. It may be slightly unintuitive there that `inputPath` includes the input directory, but it does. I’m not sure I could change in a way that would benefit without potentially awkwardly breaking code that already exists. If this is confusing to others, _please weigh in here!_ Maybe we could add another method to `getFilteredByGlobRelativeToInputDir` or something (name will probably need to be improved). (If this interests you—please file a new feature request ticket so others can vote on it)

Docs changed applied to make this clearer:
* https://www.11ty.io/docs/collections/#individual-collection-items-(useful-for-sort-callbacks)
* https://www.11ty.io/docs/collections/#getfilteredbyglob(-glob-)

Thank you!

**Comment by zachleat** [comment]
Sounds like maybe this new method should be called `getUrlFilteredByGlob`. `url` is the collection key is a closer match to what you’re going for, maybe.

See the example on https://www.11ty.io/docs/collections/#individual-collection-items-(useful-for-sort-callbacks)
