### ISSUE TITLE
Only some HTML files are minified

### ISSUE THREAD

**Issue by rolandtoth** [11ty/eleventy#199]
I have this html minification setup in .eleventy.js:

```js
  eleventyConfig.addTransform("htmlmin", function (content, outputPath) {
    if (outputPath.indexOf(".html") > -1) {
      let minified = htmlmin.minify(content, {
        useShortDoctype: true,
        removeComments: true,
        collapseWhitespace: true
      });
      return minified;
    }
    return content;
  });
```

However, only some of the final .html files are minified. The "collection.work" items are minified (.md files), others are not (.njk files):

https://rolandtoth.hu/portfolio/
https://rolandtoth.hu/portfolio/works/innobloom/

Any idea why not all files are affected?

**Comment by kleinfreund** [comment]
In order to debug this, I would `console.log` the `outputPath` object at the start to see whether this function is called for all the files you expect it to. I tried it with my test site and it’s called for all HTML files that are being generated without exception.

It could be that this filter is never called for your `.njk` files. Are these `.njk` files actually generating output HTML files?

@zachleat Do you want to change the example at [Configuration: Transforms](https://www.11ty.io/docs/config/#transforms) to check for `outputPath.endsWith(".html")` instead of `outputPath.indexOf(".html") > -1`? Reads way nicer and has less side-effects.

**Comment by kleinfreund** [comment]
Looking at this closer, I can see quite a couple of HTML files being generated for my test site that aren’t being transformed as well.

- pagination pages
- the root `index.html` file

**Comment by rolandtoth** [comment]
Thanks, outputPath is not logged at all for the root index.html and pagination index.html at all:

```
OUTPUTPATH: dist/works/tescobaba/index.html
OUTPUTPATH: dist/works/testszobrasz/index.html
Writing dist/index.html from ./input/index.njk.
Writing dist/page-2/index.html from ./input/index.njk.
Writing dist/page-3/index.html from ./input/index.njk.
Writing dist/page-4/index.html from ./input/index.njk.
Writing dist/page-5/index.html from ./input/index.njk.
OUTPUTPATH: dist/search.json
Writing dist/search.json from ./input/search.njk.
OUTPUTPATH: dist/works/index.html
Writing dist/works/index.html from ./input/works.njk.
OUTPUTPATH: dist/works/carussel-dwt/index.html
Writing dist/works/carussel-dwt/index.html from ./input/works/carussel-dwt.md.
```

**Comment by zachleat** [comment]
Hmm, seems like paginated templates may be skipping transforms. Logging as a bug.

**Comment by kleinfreund** [comment]
This works as expected now. Cool! :+1:

**Comment by rolandtoth** [comment]
I was about to reopen this issue but fortunately there was a silly mistake in one of the html files, that's why it failed here (this bug was not there before when I opened this issue). Once I fixed it the minification is fine, thanks!

**Comment by zachleat** [comment]
was there an error message?

**Comment by rolandtoth** [comment]
Yes, the html minifier's htmlparser was choking on the markup, reading it more thoroughly gave the clue that it could be something on my end.
