### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by rocc-o** [11ty/eleventy#2065]
Every time I `npx @11ty/eleventy --serve` I get:

```
(node:19432) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19432) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:19432) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
```
However the site builds fine with no errors except this warning. What does it mean?

**Comment by pdehaan** [comment]
This looks like an `eleventy-critical-css` or `critical` memory leak issue possibly.

- https://github.com/gregives/eleventy-critical-css/issues/7
- https://github.com/addyosmani/critical/issues/121
- https://github.com/addyosmani/critical/pull/59

Lots of info if you search https://www.google.com/search?q=MaxListenersExceededWarning%3A+Possible+EventEmitter+memory+leak+detected&shem=ssmd, although most of it so far seems focused on if it's an issue with an EventEmitter in your code, not a 3rd party's code.

At any rate, you'll probably want to file it upstream in one of the repos above since it isn't happening in Eleventy [as far as I can tell].

**Comment by rocc-o** [comment]
Thanks Peter. I will check how it evolves in the above repos. I see someone is suggesting to add `process.setMaxListeners(0)` in the code, which will mute this warning. But this event emitter memory leak can be considered just a "warning" or is something worse?

**Comment by pdehaan** [comment]
If the build finishes and generates your site, I wouldn’t worry too much about the warning (since the deployed static files wouldn’t be affected, unless you’re using some Eleventy serverless deploy). If the warning fails the build, I’d probably remove that plug-in and find another library/solution.

**Comment by rocc-o** [comment]
Ok. Thanks Peter!
