### ISSUE TITLE
Template extension aliasing, use `.markdown` for markdown files

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#207]
Some mechanism to allow extension of existing template engines with additional file extensions.

@paulrobertlloyd surfaced this in https://github.com/11ty/eleventy/issues/117#issuecomment-388576364 with the desire to use `.markdown`.

I wonder if it would be useful to remove the original `.md` if you’re using something else or if supplementing is sufficient.

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

The enhancement backlog can be found here: https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+

Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
Also a request in #223 to use `.mst` as a mustache alias via @coolshaurya

**Comment by coolshaurya** [comment]
The default file extension used for template engines should be the most commonly used extension - `.md` for markdown , `.hbs` for handlebars , `.mst` for mustache ,`.html` for HTML etc. which mostly happens to be the shortest extension among the 2 file extensions that some template engines have.

**Comment by zachleat** [comment]
cc @medfreeman can you upvote here instead of #124? Thanks!

**Comment by zachleat** [comment]
Please see the limitation of the current implementation at #207 and let me know what you think. Wondering how deep to go here.

**Comment by zachleat** [comment]
Sorry but this is being punted out of 0.7.0 for now. I’m not happy with my implementation and I think it will cause headaches so I will revisit for a future release!

**Comment by zachleat** [comment]
Keep in mind the relevant (closed) discussion at https://github.com/11ty/eleventy/issues/319. We’ll coalesce at this issue.

**Comment by zachleat** [comment]
Related: #826 #827

**Comment by montanaflynn** [comment]
I would love to add aliases for existing formats. We have a custom markdown file format called mathpix markdown which is supported through markdown-it plugin but the extension is `.mmd`. We want to support both `.md` and `.mmd` with eleventy. 

I think there was some progress on this at https://github.com/11ty/eleventy/issues/319, I really don't think anyone wants to not use the default and only pick up the added aliases.

**Comment by tobyspark** [comment]
Yes please to aliasing. Don’t need replacement.

I’m pro `.markdown` ([as is its creator, if pushed to requiring an extension at all](https://daringfireball.net/linked/2014/01/08/markdown-extension)).

**Comment by zachleat** [comment]
This is shipping with 2.0.0-canary.19 https://www.11ty.dev/docs/languages/custom/#aliasing-an-existing-template-language

**Comment by KholdStare** [comment]
Just some feedback on documentation. I've found eleventy to be one of the _the most_ frustrating projects to work with. The functionality is all there, but finding how to do anything specific usually involves scouring github issues, bouncing around multiple documentation pages, and actually reading the source code of the eleventy config to make sense of anything.

As one example, I am porting an old blog from Jekyll which had all posts as `.markdown` files. The TL;DR solution for 11ty 3.0.0 is

```js
export default async function (config) {
  config.addTemplateFormats("markdown");
  config.addExtension("markdown", {
    key: "md",
  });
};
```

Why it took me forever:
- This github issue is the first result when I did a web search, and the actual solution _is not anywhere in the issue_. There are links to the documentation, or other issues/pull requests.
- This leads to https://www.11ty.dev/docs/languages/custom/#aliasing-an-existing-template-language . This uses `addExtension` command, with an ad-hoc condition that if `key` is the only entry it is treated as an alias. There is no explanation what `key` actually means in this case, with no link to the documentation of `addExtension` and what it takes. From the context I infer that `key` here is the original template format... Ok, I'll just add `key: "md"`
- `.markdown` files are still ignored. At this point I am running with `DEBUG=Eleventy*` and looking through logs to try and understand why `.markdown` files are still being ignored.
- ` Eleventy:EleventyFiles Searching for: [ './**/*.{liquid,md,njk,html,11ty.js,11ty.cjs,11ty.mjs}' ] +1ms ` is in the log, which means the extension is still ignored for sure.
- I search some more in the documentation and eventually stumble on the same documentation page, but a section higher up https://www.11ty.dev/docs/languages/custom/#introductory-example-clowd . Turns out a call to `addTemplateFormats` is needed. Why is this not mentioned directly next to `addExtension` if the two go hand in hand?

This is only one issue I've ran into out of probably a dozen. These "special case" documentation sections need to be always reviewed from the perspective of someone who is unfamiliar with the rest of the documentation and nuances. The entire solution should be given directly, not piecemeal.

Thanks for listening to my rant 😅
