### ISSUE TITLE
Async options for BrowserSync config

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#2103]
Some discussion with @Holben888 prompted the Slinkity/Vite need to do some async work to generate middleware options for browsersync.

https://github.com/slinkity/slinkity/blob/main/src/plugin/index.js#L101-L125

Note `server = await viteSSR.createServer()`

Because async config init is a _very_ hefty task (no async in class constructors), we thought perhaps a more specialized case might be warranted here, because the browsersync init happens so late in the order of operations.

Note sure what that looks like yet.

Eleventy->watch is already async https://github.com/11ty/eleventy/blob/50203907b05e3575fc26550a41cb8dfe21914443/src/Eleventy.js#L798

Eleventy->serve is not yet async https://github.com/11ty/eleventy/blob/50203907b05e3575fc26550a41cb8dfe21914443/src/Eleventy.js#L886 but could be changed. Called via `cmd.js` https://github.com/11ty/eleventy/blob/50203907b05e3575fc26550a41cb8dfe21914443/cmd.js#L113

**Comment by Holben888** [comment]
Did some initial investigation here! It seem we can't safely resolve async configs from the user config side of things, since that opens a huge "async everything" can of worms. However, it _is_ safe to resolve async configs inside async-ready functions like `elev.serve`.

We'll likely need to touch 2 functions:
https://github.com/11ty/eleventy/blob/1ea3a90cc49b636a4c838852a9103e9fe6d2135d/src/EleventyServe.js#L54

Adding an `await` before the `Object.assign` statement

https://github.com/11ty/eleventy/blob/1ea3a90cc49b636a4c838852a9103e9fe6d2135d/src/EleventyServe.js#L136

Adding an `await` before the `this.getOptions` call

There's just 1 snag left to fix: **merging browsersync configs.** This is currently handled from the user-facing `setBrowserSyncConfig`, so it could only work when `options` is synchronous 😬 

https://github.com/11ty/eleventy/blob/1ea3a90cc49b636a4c838852a9103e9fe6d2135d/src/UserConfig.js#L676-L682

We'll likely need to move `merge` into the `getOptions` call mentioned earlier. We'll also need to change `UserConfig.browserSyncConfig` to an _array_ of configs so we can delay merging until later (when it's safe to perform async operations).

Will check back on this, but it seems doable!

**Comment by bholmesdev** [comment]
Should be good to close with [new 11ty 2.0 server "setup" option](https://www.11ty.dev/docs/watch-serve/#eleventy-dev-server)!

**Comment by zachleat** [comment]
Indeed `setup` is async-friendly! https://github.com/11ty/eleventy/blob/0611393b62c789cb805a4ce9e62e3dea0086b492/src/EleventyServe.js
