### ISSUE TITLE
Using Serverless without Netlify or Lambda functions: Possible? How?

### ISSUE THREAD

**Issue by baptiste-roullin** [11ty/eleventy#2162]
Hi,

Currently, the documentation for the Serverless plugin states that "_As of right now, On-demand Builders are a Netlify specific feature._"

The rest seems to be agnostic hosting-wise, but I am bit lost on how to use the plugin without Netlify functions.  The official page and every demo or tutorial I could find seems to assume a Netlify environment. No luck also in past Github issues.

Using `eleventy --serve` seems to work for local dev purposes but what about a production environment? I have a self-hosted Nginx server, can I make this work by manually setting the ELEVENTY_SERVERLESS variable, some routing setup and with a script running something like  `node ./[function]/index.js` on hits? Can the result be a proper HTTP response? 

Or is it one of those bad ideas™?

More generally, can the plugin be realistically used without Netlifly or without, for that matter, any plateform using AWS Lambda stuff ? 
If it's the case, could the documentation be expanded for that use case? If not, can the documentation come with a warning? 

PS: Congrats on the recent "1.0" commit. 🎉

**Comment by araphiel** [comment]
https://www.11ty.dev/docs/programmatic

Generate your page via the lambda and return the dynamic HTML to the client.

It's not exactly hard, just cumbersome because the lambda needs access to your templates and config.
You'd need to lean on Terraform/CDK/Serverless in part of your CI/CD builds to keep things in sync.

If I get time this weekend, I'll see about spinning up an example repo.

**Comment by zachleat** [comment]
Improvements here are ongoing! Definitely open to folks contributing more compatibility layers here.

Related: https://github.com/11ty/eleventy/issues/1866
