### ISSUE TITLE
addGlobalData should execute once per build, currently executing once per template file

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#2179]
cc @dleatherman

**Comment by dleatherman** [comment]
**Describe the bug**

Plugin should run once per build, not once per layout.

**To Reproduce**

I created a simplified version of the bug here: https://github.com/dleatherman/eleventy-plugin-async-test where the build outputs 3 console logs (one for each of the layouts).

1. Clone above repo
2. `npm install && cd demo && npm install && npm run build`
3. See output from plugin and async function (1 time for each layout: `base.njk`, `index.njk`, and `page.njk`)
4. See error

**Expected behavior**

I would expect the plugin to run once per eleventy build, not once per layout. I am awaiting content and then building individual pages via pagination. Each of the pages generated via pagination gets another instance of the plugin's function run causing my build to continue calling the content API exponentially.

**Screenshots**
Plugin content:
![image](https://user-images.githubusercontent.com/730173/149988111-636c1b98-da1a-4ee2-89a9-7dca292217df.png)

**Environment:**

- OS and Version: Mac OS (12)
- Eleventy Version 1.0.0

**Additional Context**

Possibly related to https://github.com/11ty/eleventy/issues/1729

**Comment by pdehaan** [comment]
@mattbloomfield Not a direct answer to your question, but a couple approaches I've used in the past:
- using https://www.11ty.dev/docs/plugins/cache/ for caching network requests, or 
- move the API requests outside of eleventy into a separate Node/Bash script so I can download a bunch of data, do some light processing, and then storing the results (as a big ol' JSON blob) in the /_data/ directory. Sometimes this is easier because the data I'm scraping might only change daily so there's no need to always refetch locally while debugging, etc.
    - Then i can just run <kbd>npm run fetchdata</kbd> whenever I need to update the random data I'm using.

**Comment by dleatherman** [comment]
Stellar! Thank you!!
