### ISSUE TITLE
Confusion over permalink docs

### ISSUE THREAD

**Issue by edwardhorsford** [11ty/eleventy#218]
I think the docs could be clearer about using permalinks.

My use case:
I had a bunch of pages in `/src/pages/` that I wanted to map to the root of my dist. It looked like permalinks would allow this.

I ultimately worked out that what I needed was `permalink : /{{page.fileSlug}}/index.html` - however this wasn't obvious from the docs.

After reading the docs, the first thing that jumped out at me was the line **"What to leave out…
File name extension."** - this seemed to strongly imply not using the extension in the permalink.

Things I tried:
1: `permalink : /{{page.fileSlug}}` - this produces a file in the root but with with no extension. Links here try to download it
2. `permalink : /{{page.fileSlug}}.html` - sort of works, but has an extension unlike other pages

---

Other thoughts:
I'm guessing a common need will be to remap `foo/bar` to `baz/bar` - the current function would require `baz/bar/index.html` I think. I wonder if eleventy could automatically add the `/index.html` if no extension is provided.

**Comment by zachleat** [comment]
Thanks for logging your confusion! I agree this is confusing, in part related to your issue in #213 I think!

Did you try `/{{ page.fileSlug }}/`? (note the trailing slash)

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for documentation requests. This means documentation issues will now be closed instead of leaving them open.

View [the documentation queue backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Areactions-%2B1-desc+is%3Aclosed+label%3Adocumentation+label%3Aneeds-votes). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
Some error messaging around this added with #3399 shipped with v3.0

Also pushed some minor changes to https://www.11ty.dev/docs/permalinks/#changing-the-output-location
