### ISSUE TITLE
Liquid: Unable to pull include path from front matter

### ISSUE THREAD

**Issue by patrulea** [11ty/eleventy#2181]
I’m trying to list all scripts in the pages’ front matter to include them as inline.

My base template `/_includes/base.liquid` currently looks like this:

```
{% for script in scripts %}
{% if script contains "http://" or script contains "https://" %}
<script src="{{ script }}"></script>
{% else %}
{% capture inlineScript %}{{ script }}{% endcapture %}
<script>
    {% render inlineScript %}
</script>
{% endif %}
{% endfor %}
```

While front matter in posts look like this:

```
---
scripts:
    - "https://cdn.jsdelivr.net/npm/jquery@3/dist/jquery.min.js"
    - "_morpho.js"
---
```

LiquidJS options are all default (meaning `dynamicPartials` is set to `true`). Yet, my code won’t compile:

```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] > Having trouble writing template: _site/morpho/index.html

`TemplateWriterWriteError` was thrown
[11ty] > unexpected token at "#data.values", file:C:\Users\hey\Documents\GitHub\los-hopper\_includes\_morpho.js, line:30, col:22, file:./_includes/base.liquid, line:49, col:13

`RenderError` was thrown
[11ty] > unexpected token at "#data.values", file:C:\Users\hey\Documents\GitHub\los-hopper\_includes\_morpho.js, line:30, col:22

`ParseError` was thrown
[11ty] > unexpected token at "#data.values"
```

**Comment by patrulea** [comment]
I saw #209 but not even the [fix](https://github.com/11ty/eleventy/issues/209#issuecomment-948443007) @rupl proposed at the end of the thread would work.

**Comment by pdehaan** [comment]
I wasn't able to reproduce locally (see https://github.com/pdehaan/11ty-2181).
But I guess it might depend on the contents of the mysterious `_morpho.js`. If that has something that LiquidJS can't parse, it will probably explode.

I also don't understand this in your debug output:

```
Having trouble writing template: _site/morpho/index.html
```

Why is it trying to write a "_site/morpho/index.html" file? Seems suspicious.
If you have a public repo I can take a look at your source and see if it's possibly something else. Otherwise, maybe try erasing the contents of your _morpho.js file and replace w/ some `// testing` to eliminate the possibility that it's a liquid trying to render JavaScript issue.  You could wrap the JavaScript file in a `{% raw %}..{% endraw %}` tag, but then it isn't strictly JavaScript and might break some ESLint or other tooling that may be using the file.

**Comment by patrulea** [comment]
Thank you for your detailed response 🙏

Indeed, `_morpho.js` has some troublesome mustache templating going on. It built effortlessly without it.

`morpho.html` was just `morpho.liquid` trying to come by. Its script just happened to have the same slug in the filename.
