### ISSUE TITLE
Environment variables example

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#221]
https://www.11ty.io/docs/data-js/

**Comment by zachleat** [comment]
Discussion https://twitter.com/zachleat/status/1039167721433440256

**Comment by zachleat** [comment]
Fixed by @kleinfreund https://github.com/11ty/11ty.io/pull/15

Deployed https://www.11ty.io/docs/data-js/#example%3A-exposing-environment-variables

**Comment by edwardhorsford** [comment]
This is great, thanks @kleinfreund.

Could I suggest mentioning it in https://www.11ty.io/docs/data/ ? I'm not sure a new user would think to look in data-files as a means to get something they might otherwise expect to use directly.

I think my first port of call when I tried to access them was to add something to `.eleventy.js` like this:
![screen shot 2018-09-16 at 20 07 01](https://user-images.githubusercontent.com/2204224/45599934-1d4ff580-b9ec-11e8-89e4-e127552e91fc.PNG)

**Comment by kleinfreund** [comment]
> I think my first port of call when I tried to access them was to add something to `.eleventy.js` like this:
> ![Adding `env: process.env.Node_ENV` to the Eleventy configuration](https://user-images.githubusercontent.com/2204224/45599934-1d4ff580-b9ec-11e8-89e4-e127552e91fc.PNG)

I did exactly the same.
