### ISSUE TITLE
Use shortcode inside a included block? 

### ISSUE THREAD

**Issue by Okkido** [11ty/eleventy#2244]

**Comment by zachleat** [comment]
Moving to `11ty/eleventy`

**Comment by joepavitt** [comment]
> Just confirmed locally that async image shortcodes work inside of an include in Nunjucks in Eleventy 1.0.

Am hitting this issue at the moment with Eleventy 2.0.1. We have an `eleventyConfig.addAsyncShortcode` that trips when inside the included `.njk` file. Can also confirm that changing it to an `nunjucksShortcode` rather than `async` fixes the rendering, which is not a solution for us as we need the async functionality.

**Comment by pdehaan** [comment]
@joepavitt If you can create a simple test case/repo I can take a look.
Sometimes it's a matter of using the undocumented Nunjucks [`ifAsync`](https://github.com/mozilla/nunjucks/issues/838) tag or using [`asyncEach`](https://mozilla.github.io/nunjucks/templating.html#asynceach) instead of a `for` loop.

**Comment by joepavitt** [comment]
Thanks @pdehaan will give those a go, have both `for` and `if` inside the included `.njk` file

**Comment by joepavitt** [comment]
[asyncEach](https://mozilla.github.io/nunjucks/templating.html#asynceach) was the key! I had the `{% include %} inside a `{% for %}, switching this to a `{% asyncEach %} got it working for me.

Thank you so much @pdehaan

**Comment by adamduncan** [comment]
Thanks @pdehaan. `asyncEach` is exactly what we needed too 🙌
