### ISSUE TITLE
Meta Generator Shortcode

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#2293]
As we move toward making the Leaderboards opt-in via `<meta name="generator">` to solve the issue of folks changing their tech stack to another generator (and tanking their scores 😅), we should provide a shortcode to easily automate this.

Name TBD, but here’s how it might work:

```
<!-- Not real code yet, so don’t use this -->
{% metaGenerator %}
```

```html
<meta name="generator" content="Eleventy v2.0.0">
```

or:

```
<!-- Not real code yet, so don’t use this -->
<meta name="generator" content="{% eleventy.version %}">
```

```html
<meta name="generator" content="Eleventy v2.0.0">
```

https://www.11ty.dev/speedlify/

Features:

* Should strip off canary release suffixes

**Comment by pdehaan** [comment]
Big +1 to having **_both_** solutions.
1. I can never remember the exact syntax for `<meta>` tags since they can sometimes be inconsistent, so a shortcode would be awesome.
2. There are plenty of times I want to know/display which version of Eleventy I'm running, and using something like `eleventy.version` is easier than `require("@11ty/eleventy/package.json").version` and then putting that version in a global data file or using `eleventyConfig.addGlobalData("eleventyVersion", require("@11ty/eleventy/package.json").version)`.

**Comment by coelmay** [comment]
I feel `{% metaGenerator %}` as a shortcode fits perfectly for the intended usage/output.

**Comment by nhoizey** [comment]
I think `{% metaGenerator %}` is not specific enough, there might be an issue with existing shortcodes.

What about `{% eleventyVersionMeta %}`?

I also agree with @pdehaan that `{% eleventy.version %}` (or `{% eleventyVersion %}`) would be useful.

**Comment by zachleat** [comment]
Going with `eleventy.version` and `eleventy.generator` Eleventy supplied global data for this one to keep the spirit of full control of markup.

Usage: `<meta name="generator" content="{{ eleventy.generator }}">`

Docs pending on https://www.11ty.dev/docs/data-eleventy-supplied/#eleventy-variable

**Comment by zachleat** [comment]
1.0.1 and 2.0.0-canary.5
