### ISSUE TITLE
Equivalent for site.static_file in a loop

### ISSUE THREAD

**Issue by mittelgrau** [11ty/eleventy#234]
Playing around with Eleventy and stumbled about finding a equivalent for this Jekyll/Liquid loop
 ```
{% for image in site.static_files %}
      <img src=""{{ image.url }}>
{% endfor %}
``` 
any quick hint where to look?

**Comment by kleinfreund** [comment]
What do you expect `site.static_files` to contain?

You can use [Data files](https://www.11ty.io/docs/data/) or even [JavaScript data files](https://www.11ty.io/docs/data-js/) to provide your templates with additional data.

**Comment by mittelgrau** [comment]
Group of images that are not part of a specific Blog post. But i will make sure to read through your links :)

**Comment by zachleat** [comment]
This looks like what @mittelgrau is referencing: https://jekyllrb.com/docs/static-files/

I don’t believe that we’ll ever have this idea of static versus dynamic files because we decide what to process based on file extension, not on whether or not the file has front matter.

@kleinfreund is right that you can build an array of files using https://www.11ty.io/docs/data-js/ JavaScript Data Files to iterate over files in a directory.

Eventually we might be able to do this with #117 and data files to assign [Tags](https://www.11ty.io/docs/collections/) to these new file types. But that’s later on.

Please reopen if you have more questions!

**Comment by kleinfreund** [comment]
That said, pass-through files serve a similar if not the same purpose. We could make pass-through files available as an implicit collection.

**Comment by zachleat** [comment]
> We could make pass-through files available as an implicit collection.

Oh now there’s a very interesting idea indeed.

**Comment by zachleat** [comment]
Opened as #237
