### ISSUE TITLE
eleventy.edge.query only returns the last of multiple querystring keys 

### ISSUE THREAD

**Issue by philhawksworth** [11ty/eleventy#2422]
## Description

The data captured by `eleventy.edge.query` should include all values for a given key in the querystring, but currently only the last instance of any repeated key is returned.

## To reproduce

1. Visit https://test-eleventy-edge-querystring.netlify.app/?status=Open&status=Closed&status=Other
2. Note that there are multiple `status` keys in the querystring
3. The data captured by  `eleventy.edge.query` is shown on the page in the _Result_ section
4. the data should include each value passed for `status`, but only the final one will be returned
5. You can experiment with the form on the page to see different permutation giving the same result

## Expected behavior

All values of each repeated key in the querystring should be returned, perhaps as an array.

## Isolated and replicated

- Test site: https://test-eleventy-edge-querystring.netlify.app/
- Test repo: https://github.com/philhawksworth/test-eleventy-edge-querystring

 ## Eleventy Version
 
 v2.0.0-canary.11

**Comment by pdehaan** [comment]
Interesting. I wonder if there is a way to get the raw request URL somewhere (sorry, I haven't looked at the new Edge stuff yet).

But from the looks of this rough code, it seems possible to parse multiple keys from a query string using the Node native "querystring" module:
```js
const qs = require("node:querystring");

const params = qs.parse("status=Open&status=Closed&status=Other&age=ok");
console.log(params); // { status: ["Open", "Closed", "Other"], age: "ok" }

console.log(params.status); // ["Open", "Closed", "Other"]
```

Similarly, if we use the `new URL(href).searchParams.getAll('status')` API, that returns the array values. But if we use `.get('status')` we only get the first value:

```js
const href = "https://test-eleventy-edge-querystring.netlify.app/?status=Open&status=Closed&status=Other&age=ok";

const u = new URL(href);
for (const [k, v] of u.searchParams.entries()) {
  console.log(`${k} == ${v}`);
}
// "status == Open"
// "status == Closed"
// "status == Other"
// "age == ok"

console.log(u.searchParams.get("status")); // "Open"
console.log(u.searchParams.getAll("status")); // [ "Open", "Closed", "Other" ]
```

https://github.com/11ty/demo-eleventy-edge/blob/fcc4eb5a3a7210f769d97595ff2eb2495605c64d/netlify/edge-functions/repeat.js#L2

**Comment by pdehaan** [comment]
Thinking about this a bit more, not sure if this is related/relevant, but definitely seems a bit suspicious:
https://github.com/11ty/eleventy/blob/1db6a10a98f35b6f6bcac94222cdd8597e6f7928/src/Plugins/ServerlessBundlerPlugin.js#L151

I did some lazy guesswork and if this code is even relevant to the original topic, `Object.fromEntries()` seems to be flattening the object and removing duplicated keys (like JSON/objects can):

```js
const query = "name=peter&name=zaach&name=phil&bool=true&num=17";
const params = new URLSearchParams(query);
const url = new URL(`?${query}`, "http://localhost");

/*
  { href: 'http://localhost/?name=peter&name=zaach&name=phil&bool=true&num=17' }
*/
console.log({href: url.href});

/* Note the duplicated `name` params in the URLSearchParams object.
  {
    aa: URLSearchParams {
      'name' => 'peter',
      'name' => 'zaach',
      'name' => 'phil',
      'bool' => 'true',
      'num' => '17' }
    }
  }
 */
console.log({aa: url.searchParams});

/* But, running `Object.fromEntries(url.searchParams)` flattens and only returns the last `name`.
  { bb: { name: 'phil', bool: 'true', num: '17' } }
*/
console.log({bb: Object.fromEntries(url.searchParams)});

const res = {};
for (const key of url.searchParams.keys()) {
  let value = url.searchParams.getAll(key);
  if (value.length === 1) {
    value = value[0];
  }
  res[key] = value;
}

/* Gross loop, but still keeps the array of `name` search params.
  { cc: { name: [ 'peter', 'zaach', 'phil' ], bool: 'true', num: '17' } }
*/
console.log({cc: res});
```

There's probably a better/cleaner way to parse some potentially duplicated query params. In fact, the original `querystring.parse()` seems to do the trick:

```js	
// Remove leading `?`.
const $tmp = {...qs.parse(url.search.replace(/^\?/, ""))};
/* Much nicer, still retains the array of `name` search params without needing loops+`.getAll()`.
  { name: [ 'peter', 'zaach', 'phil' ], bool: 'true', num: '17' }
*/
console.log($tmp);
```

**Comment by zachleat** [comment]
Awesome investigative work @pdehaan—makes me wish Deno had a `querystring` package.

We will need to apply this fix to both the Serverless and the Edge plugins!

**Comment by zachleat** [comment]
The Edge plugin code lives here: https://github.com/11ty/eleventy-edge-cdn/blob/7c1c725bbebff10edef9e2217021b42e1fae1b49/esbuild-entry-point.js#L176

**Comment by zachleat** [comment]
Forgot to reference this one upstream but fixed with Eleventy Edge 2.0.0. (You can update your import directly to point to `https://cdn.11ty.dev/edge@2.0.0/eleventy-edge.js` if you’d like, otherwise you’ll need to wait for another canary to pick up the import_map changes for `eleventy:edge`)

https://github.com/11ty/eleventy-edge-cdn/commit/1fd2c154f7fa5a8496fdc9da4c2113b669881c0d

Serverless work pending!

**Comment by zachleat** [comment]
Working on the Serverless piece and looking at the production behavior of AWS Lambda (independent of Eleventy)

https://heroic-marzipan-99689b.netlify.app/?test=1&test=2

```js
  "queryStringParameters": {
    "test": "1, 2"
  },
  "multiValueQueryStringParameters": {
    "test": [
      "1",
      "2"
    ]
  },
```

More at: https://aws.amazon.com/blogs/compute/support-for-multi-value-parameters-in-amazon-api-gateway/

Here’s how we can improve compatibility there moving forward:

1. Fix the default serverless function that gets generated to prefer the `multiValue…` version first before the raw string (`query: event.multiValueQueryStringParameters || event.queryStringParameters,`) This will only apply to new serverless functions.
2. Fix the local development behavior to match the production behavior. Duplicate strings will now be comma separated by default (instead of de-duped). And we’ll add the `multiValueQueryStringParameters` property to our fake event in the serverless middleware to match as well.

That way local development will match production behavior and will adapt to folks wanting to use either query param variant (`event.multiValueQueryStringParameters` or `event.queryStringParameters`)

**Comment by zachleat** [comment]
Shipping with 2.0.0-canary.12

**Comment by pdehaan** [comment]
> The Edge plugin code lives here: [11ty/eleventy-edge-cdn@`7c1c725`/esbuild-entry-point.js#L176](https://github.com/11ty/eleventy-edge-cdn/blob/7c1c725bbebff10edef9e2217021b42e1fae1b49/esbuild-entry-point.js#L176)

FWIW: This seems to 404 for me from my iPad and seems to be a private repo.

**Comment by zachleat** [comment]
Oh, huh. it needn’t be private any longer. I’ll open it up

**Comment by zachleat** [comment]
The Edge CDN repo is public now 👀
