### ISSUE TITLE
Support for liquid 'sort' filter

### ISSUE THREAD

**Issue by silveltman** [11ty/eleventy#2447]
I ran into this problem multiple times: sorting a collection based on a frontmatter value. I don't understand why the liquidjs sort filter is not doing anything and can't seem to find any explanation for this. It really doesn't make sense to me, since it should be available in  Liquid v1.9.1+.

I would like to be able to use the LiquidJS sort filter as described here: https://liquidjs.com/filters/sort.html
So like this:

```
{% assign sorted = collections.mycollection | sort: "mykey" %}
{% for item in sorted %} 
   ...............
{% endfor %}
```

I know there are already alternatives (11ty-filters and the collection API), but these are suboptimal imo.

Would love to hear what I'm doing wrong, or an explanation of why this feature is missing. Thanks!

**Comment by pdehaan** [comment]
Sorting works in Eleventy 1.0.1 (liquidjs@9.37.0), but you need to use `sort: "data.mykey"` since you're sorting by front matter.
Also, while LiquidJS might have had the `sort` filter since 1.9.1, it might have added new features/fixes in later versions. For example, https://github.com/harttle/liquidjs/issues/227 (https://github.com/harttle/liquidjs/commit/4f17c94988ea32f305261e40f761dacb79c59777) is when the support for sorting by nested keys was added, and wasn't added until [9.12.0](https://github.com/harttle/liquidjs/blob/master/CHANGELOG.md#9120-2020-05-15) (which means if you're using Eleventy 0.12.x, it wouldn't be supported yet; since eleventy@0.12.1 seems to include an older liquidjs@6.4.3).
