### ISSUE TITLE
Nunjucks not rendering result of Markdown

### ISSUE THREAD

**Issue by NickColley** [11ty/eleventy#2610]
If I have a markdown file that has:

```markdown
# Hello, {{ "world" }}
```

I get the result:

```html
<h1>Hello, world</h1>
```

However if transform some markdown for example by using [a directives plugin](https://github.com/remarkjs/remark-directive) then it no longer works:

```markdown
# Hello, {{ "world" }}

:directive
```

When transforming the markdown I turn `:directive` into `{{ "Bill gates" }}`, so I expect that by the time it hits Nunjucks both lines are the same but instead this happens:

```html
<h1>Hello, world</p>
<p>{{ "Bill Gates" }}</p>
```

When I expect instead:

```html
<h1>Hello, world</p>
<p>Bill Gates</p>
```

Any ideas?

**Comment by zachleat** [comment]
I’ll probably need an example of those directives plugins to say more!

**Comment by NickColley** [comment]
I'll make a reduced test case 🤓

**Comment by NickColley** [comment]
Okay I've made one:
https://github.com/NickColley/markdown-template-issue

The reason I want to do this by the way is to have a directive like:

```markdown
::include(footer.html)
```

And replace it with

```nunjucks
{% include footer.html %}
```

**Comment by pdehaan** [comment]
OK, this is getting a bit interesting&hellip;

Let's say I modify @NickColley's sample repo slightly and set `templateEngineOverride: to md,njk` (since the default .md template engine is LiquidJS anyways):

```md
---
templateEngineOverride: md,njk
---

# Content to render as markdown

- I am the _wizard_.

{{ "_Bonjour, Monde_" | upper }}
```

**NOTE:** The above template should fail if you were using the LiquidJS engine, since liquid uses an [`upcase`](https://liquidjs.com/filters/upcase.html) filter versus the Nunjucks engine's [`upper`](https://mozilla.github.io/nunjucks/templating.html#upper) filter.

Next, if I add slightly more logging to the custom .md parsing library in .eleventy.js config file:
```js
module.exports = function (eleventyConfig) {
  eleventyConfig.setLibrary("md", {
    render: (content) => {
      console.log({content});
      return `<p>${content.trim()}</p>\n\n{{ "Hello, world" }}\n\n`;
    },
  });
};
```

It will log out the following:
```js
{
  content: '\n' +
    '# Content to render as markdown\n' +
    '\n' +
    '- I am the _wizard_.\n' +
    '\n' +
    '_BONJOUR, MONDE_\n' +
    '\n' +
    '\n'
}
```

Specifically, note that `{{ "_Bonjour, Monde_" | upper }}` has already been converted to `_BONJOUR, MONDE_`. If I'm reading this correctly, Nunjucks has already parsed the template before sending it to the Markdown rendering engine. So, if your Markdown engine converts some directives back into Liquid/Nunjucks code, it'd have to be reprocessed by Liquid/Nunjucks.

I saw no difference between these front matter configs, so I don't think the order is relevant to the order in which templates get processed (or number of times they'd be potentially re-processed):
```md
templateEngineOverride: njk,md
templateEngineOverride: md,njk
templateEngineOverride: njk,md,njk,md,njk
```

**Comment by NickColley** [comment]
So I guess the question is the order intended to matter or was it just an assumption of mine that it mattered.

That determines if this is a bug or a feature request I guess.

**Comment by pdehaan** [comment]
Per https://www.11ty.dev/docs/languages/markdown/
> _"**INFO:** Markdown files are by default **pre-processed** as Liquid templates. [You can change this default in your configuration file](https://www.11ty.dev/docs/config/#default-template-engine-for-markdown-files) (or disable it altogether). To change this for a single template and not globally, read [Changing a Template’s Rendering Engine](https://www.11ty.dev/docs/languages/)."_

**Comment by NickColley** [comment]
Ah so it's just not a thing and this is a feature request to be able to render it afterwards I guess 😭

**Comment by pdehaan** [comment]
🤷 I defer to @zachleat.

I'm not sure how easy it'd be to have your custom markdown processor send everything back through LiquidJS or Nunjucks engine for postprocessing.
In theory it sounds somewhat easy (although probably not great performance wise) but in practice I assume it's trickier than that since you'd have to handle data cascade and include paths, etc. Unless there is a way you could get this working w/ https://www.11ty.dev/docs/plugins/render/

> _"The first argument to renderTemplate can be any valid [templateEngineOverride](https://www.11ty.dev/docs/languages/#templateengineoverride-examples) value. You can even use "liquid,md" to preprocess markdown with liquid. You can use [custom template types](https://www.11ty.dev/docs/languages/custom/) here too, including [the Vue plugin](https://github.com/11ty/eleventy-plugin-vue)!"_

**Comment by NickColley** [comment]
https://www.11ty.dev/docs/languages/#special-case-pairing-a-templating-engine-with-md-markdown this one suggests the ordering is intentional "Nunjucks and then Markdown"

**Comment by NickColley** [comment]
This is where the magic happens:

https://github.com/11ty/eleventy/blob/master/src/Engines/Markdown.js#L74-L78

**Comment by NickColley** [comment]
If you re-order it like this, then it works how I'd hoped:

```javacript
let finishedRender = mdlib.render(str, data);
let fnReady = engine.compile(finishedRender, inputPath);
let fn = await fnReady;
let postTemplateRender = await fn(data);
return postTemplateRender;
```

**Comment by NickColley** [comment]
I'd be down for implementing this if we could agree on an interface for it.
Do you think it makes sense to use the order they're specified?

**Comment by pdehaan** [comment]
I honestly always assumed the order mattered, but guess I never verified (but also I never tried injecting Nunjucks/Liquid code into Markdown during compilation).

But I'd try confirming w/ @zachleat before coding anything up. It does feel like a potentially risky change since it could break existing workflows if template engine override orders are suddenly relevant.

**Comment by NickColley** [comment]
Yeah does seem like it could be risky, but 2.0.0 is a a breaking change after all so along as we communicate that the order now matters it could work.

See what Zach thinks

**Comment by NickColley** [comment]
I ended up implementing it like this:

https://github.com/NickColley/eleventy-remark-directives/blob/26e2d440be85112f7b63a06a4e5f9df849bdf894/.eleventy.config.cjs#L1-L13

https://github.com/NickColley/eleventy-remark-directives/blob/26e2d440be85112f7b63a06a4e5f9df849bdf894/lib/markdown.js#L14-L19

https://github.com/NickColley/eleventy-remark-directives/blob/26e2d440be85112f7b63a06a4e5f9df849bdf894/lib/directives.js#L5-L32

https://github.com/NickColley/eleventy-remark-directives/blob/26e2d440be85112f7b63a06a4e5f9df849bdf894/lib/utils.js#L44-L59
