### ISSUE TITLE
Feature request: support yaml for data files

### ISSUE THREAD

**Issue by edwardhorsford** [11ty/eleventy#265]
Would it be possible to support reading yaml files in as data?

I can write a js data file that imports the yaml, but it would be cool if yaml files in the `_data` got imported directly.

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

The enhancement backlog can be found here: https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+

Don’t forget to upvote the top comment with 👍!

**Comment by gwangyi** [comment]
I wrote simple plugin that support yaml data files by monkeypatching.

https://github.com/gwangyi/eleventy-plugin-yamldata

**Comment by matthewjumpsoffbuildings** [comment]
is this a possibility or has it been decided against?

**Comment by zachleat** [comment]
This has been fixed in #635 #798 and will be released with 0.10.0
