### ISSUE TITLE
Extensionless layout in 2.0 canary 20

### ISSUE THREAD

**Issue by flaviotordini** [11ty/eleventy#2704]
### Operating system

macOS

### Eleventy

2.0.0-canary.20

### Describe the bug

I'm using liquid layout names without extension.

```js
    eleventyConfig.setLiquidOptions({
        extname: ".liquid"
    });
```
Just updated to canary 20 and got this error:

```
[11ty] You’re trying to use a layout that does not exist: base (undefined) (via Error)
  Eleventy:EleventyErrorHandler (error stack): Error: You’re trying to use a layout that does not exist: base (undefined)
  Eleventy:EleventyErrorHandler     at TemplateLayoutPathResolver.getFullPath (/Users/.../node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:102:13)

```

**Comment by pdehaan** [comment]
See https://github.com/11ty/eleventy/issues/2700

**Comment by zachleat** [comment]
Whew, a few more of these and I will revert the default 😅

**Comment by zachleat** [comment]
https://www.11ty.dev/docs/layouts/#omitting-the-layouts-file-extension

**Comment by flaviotordini** [comment]
Thanks! I missed that.

**Comment by reubenlillie** [comment]
> Whew, a few more of these and I will revert the default 😅

@zachleat, I think there just needs to be a really clear notice, since it's   a pitentially breaking change. Maybe a clearer error message like "It looks like the layout file you specified is missing a file extension."

If memory serves, previous documentation made it sound like omitting the file extension was a preferable, nifty feature, to promote the flexibility of Eleventy's flexible templating language options. I agree that specifying an extension is a significant performance improvement. If there is a default that can forego specification, it should be *.11ty.js (though I'm obviously biased).

**Comment by pdehaan** [comment]
@zachleat What about reverting the build error and seeing if we can flag it as a noisy warning in https://github.com/11ty/eleventy-upgrade-help and possibly say we'll change the default behavior in 2.1 or 3.0.

Not sure if we need to add that eleventy-upgrade-help plugin to the https://www.11ty.dev/docs/ sidebar to increase visibility (since I knew about it, but still took some googling to find it).

**Comment by zachleat** [comment]
Restoring this in #2708! This is more popular than I thought 😅

**Comment by paulshryock** [comment]
I do like the change to require the extension, and I agree that a more clear error message explaining that the file extension is missing would make it easier. I mean that's the point of a canary/alpha release is that there will be API-breaking changes as the design is iterated on.
