### ISSUE TITLE
Is there an existing way to know the path of the Markdown file in Markdown-it (and its plugins)?

### ISSUE THREAD

**Issue by nhoizey** [11ty/eleventy#2883]
I'm using a bunch of Markdown-it plugins, and face [an issue with `markdown-it-image-size`](https://github.com/boyum/markdown-it-image-size/issues/404) which looks for an image in my project's root folder instead of the folder where the Markdown file is.

Is there an existing way to know the path of the Markdown file in Markdown-it (and its plugins)?

I might use it with [`markdown-it-replace-link`](https://www.npmjs.com/package/markdown-it-replace-link) to add the Markdown path to the image, for example.

**Comment by nhoizey** [comment]
It looks like there is a solution described here:
https://github.com/11ty/eleventy/issues/1510#issuecomment-1046128400

@manunamz do you know any Markdown-it plugin that already used this?

**Comment by manunamz** [comment]
Hiya @nhoizey !

Yep! [`markdown-it-wikirefs`](https://github.com/wikibonsai/markdown-it-wikirefs/) is setup to look for urls in a configurable way via its [`resolveHtmlHref`](https://github.com/wikibonsai/markdown-it-wikirefs/tree/main#resolvehtmlhref-env-any-fname-string--string--undefined) option.

You can also see it in action in [`eleventy-wikibonsai`](https://github.com/wikibonsai/eleventy-wikibonsai/blob/main/wikibonsai/markdown.js#L15), which gives several examples of how to access the `inputPath` in its configuration.

Since you might be looking for image urls, I ended up doing [something sort of hacky](https://github.com/wikibonsai/eleventy-wikibonsai/blob/main/wikibonsai/markdown.js#L24) to just get it up and running, but it works if files are placed where the code expects them to be.

**Comment by nhoizey** [comment]
@manunamz thanks a lot, I'll look at these examples! 🙏

**Comment by nhoizey** [comment]
And now there's also `markdown-it-image-size` thanks to @boyum:
- https://github.com/boyum/markdown-it-image-size/issues/404#issuecomment-1483759243

It works without adding anything to my code, just adding the plugin. 🤩
