### ISSUE TITLE
Hook

### ISSUE THREAD

**Issue by kleinfreund** [11ty/eleventy#290]
You know what would be cool? A static site generator that provides hooks for specific points in time during processing the files.

Especially hooking into before or after rendering a template would be helpful. The current API (like `collections.getAll()`) doesn’t really make it clear in which state my documents exist.

That said, which stages exist during one run of `eleventy`?

This would also be helpful for all sorts of build tool shenanigans.

![Captain Hook grinning](https://user-images.githubusercontent.com/5774638/47723230-5f5b9080-dc54-11e8-863c-adba0e214ee4.gif)

**Comment by zachleat** [comment]
Ah, good questions! Just for my information, what sort of build tool shenanigans are you trying to facilitate here? Or maybe ideas stuff will pop out after you know the lifecycle?

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

The enhancement backlog can be found here: https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+

Don’t forget to upvote the top comment with 👍!

**Comment by kleinfreund** [comment]
Right now, I have no specific idea in mind. Always happens when I work on an Eleventy project.

What I can think of right now: A `beforeRender` and `afterRender` hook for all files Eleventy renders.

But let’s wait if there is any specific ideas. We shouldn’t implement something because it sounds nice.

**Comment by robdodson** [comment]
I was also wondering if it's possible to diagram the lifecycle of an eleventy build (maybe this already exists?) so I know when _data files get processed and when collections get processed. I recently ran into a chicken and egg problem because I was trying to access my collections from one of my directory data files and it said the collection didn't exist yet.

**Comment by Ryuno-Ki** [comment]
@robdodson Something I might tackle at some point.
At the moment I am contributing JSDoc strings (which can be used for type checking down the road).

I guess, I will hit the lifecycle code at some point also.
Once I grokked it I'd like also to make a chart from it. What would you use for that? GraphViz/dot lang?

**Comment by zachleat** [comment]
Removing from the queue, this exists now: https://www.11ty.dev/docs/events/
