### ISSUE TITLE
Async plugins are not supported

### ISSUE THREAD

**Issue by ryanccn** [11ty/eleventy#3138]
### Operating system

macOS Sonoma 14.2.1

### Eleventy

3.0.0-alpha.3

### Describe the bug

Asynchronous functions used as plugins are not awaited!

https://github.com/11ty/eleventy/blob/b5411c4ba42e92bde2555ee4eb6fbb0711dc3748/src/UserConfig.js#L408-L409

**Comment by Snapstromegon** [comment]
I think async plugins should not be awaited here. If the plugin function is async, `_executePlugin` returns a promise already, since the return value `ret` is set to the result of the call of `plugin`. This means that the _TemplateConfig.js_ process plugins correctly and the `addPlugin` function of the UserConfig also supports them that way.

Do you have a usecase where this doesn't work?

**Comment by ryanccn** [comment]
I don't know much about the internals of Eleventy, but from my tests `addPlugin` seemed to be pushing to `this.plugins` instead of executing the plugin straight up, so awaiting on the returned futures from `addPlugin` calls don't really work.

**Comment by Snapstromegon** [comment]
Yes, that's correct. They get executed and awaited later on here: https://github.com/11ty/eleventy/blob/main/src/TemplateConfig.js#L283

Since async plugins are new in 3.0, do you have an example (maybe even with code) of something that doesn't work, that you expect to work?

**Comment by ryanccn** [comment]
Ah, I see. I made some tweaks to my code and it seems to work now; sorry for the inconvenience!
