### ISSUE TITLE
Pagination - is it confusing?

### ISSUE THREAD

**Issue by edwardhorsford** [11ty/eleventy#334]
I find pagination somewhat confusing, and I wonder if others do too. It took me quite a while to get my head around it - particularly the 'sizes' bit (actually I'm still confused how sizes works). It's really **flexible and capable**, but I feel like this capability non-obvious.

I think this is because it's meeting two distinct needs - doing page-per-thing (dynamic pages), and doing pagination of a thing in groups of n (pagination).

Possibly the name isn't right? Pagination has very specific connotations - but can do so much more! Dynamic pages might be better? Or Both? Pagination was the solution to #326 - but I don't think it's the obvious place to look - dynamic pages *might* have been.

I've run against this when trying to list all the pages created by pagination ([not currently possible](https://github.com/11ty/eleventy/issues/253), as they're not listed in `collections.all`). It's intentionally not supported because the original thinking was that when you're paginating in groups of n, only the first is relevant - but when you're doing page per thing, it's very relevant.

What do others think?

Is there potential for it to be split out? this might help for supporting things like #332?

**Comment by edwardhorsford** [comment]
@jevets no more thoughts really. I didn't get much response to this - so perhaps others don't find it confusing (which is good obviously). More than anything, I feel like my confusion is around the name.

> Do you still feel confused about the size parameter?
Half and half - I guess half my issue is that it doesn't make as much sense when you're doing a page per thing. I just leave at 1 and it seems to work.

More tips / tutorials would definitely be good. Eleventy is so capable, it's hard to know where to start!

My personal biggest issue remains that items created with pagination aren't listed in `collections.all` - which is very awkward for me as so many of my pages are dynamic (#253).

**Comment by braco** [comment]
I found this confusing, yes. Creating pages from data is a common use case in building sites, and "pagination" isn't the right terminology.

It also seems half-formed as a feature since it's impossible(?) to create dynamic titles, etc. from the pagination data since frontmatter is static outside of permalink? Lot's of gotchas. If that's wrong, take that as another point toward this being confusing :)

**Comment by zachleat** [comment]
Added some additional documentation around this to help with the confusion (which to be fair, is a bit ongoing)

https://github.com/11ty/11ty.io/commit/2ad3d49b28063cdbc66332e5fad1643f5ece05c1

Note also that the `collections.all` has also been documented since this issue was filed https://www.11ty.io/docs/collections/#the-special-all-collection

Please let me know if there are additional steps we should take here?
