### ISSUE TITLE
Stop .txt files from rendering as HTML

### ISSUE THREAD

**Issue by ibnaleem** [11ty/eleventy#3366]
### Operating system

macOS, Arch Linux, Windows 11

### Eleventy

2.0.1

### Describe the bug

My `.txt` file is displaying as HTML, but I want it to display as raw text. I renamed it to `pgp.md`, which changed its *formatting*, but it still downloaded the HTML elements, including tags, instead of just the content.

### Reproduction steps

1. Download the text file: `curl -o pgp.txt https://shaffan.dev/pgp.txt`
2. Move the downloaded `pgp.txt` file to your source directory (wherever your index file resides), and link it.
3. Navigate to `localhost:8080/pgp` in your browser. It should render the content in HTML which is not like https://shaffan.dev/pgp.txt.
4. Rename the file from `pgp.txt` to `pgp.md`.
5. Check the display again at `localhost:8080/pgp`. It should now display like https://shaffan.dev/pgp.txt.
6. Download the file: `curl -o pgp.txt http://localhost:8080/pgp`
7. Verify the contents of `pgp.txt`. It should contain HTML tags. This should not happen; only the contents of the file should be downloaded (not the HTML)

### Expected behavior

1. Should display like https://shaffan.dev/pgp.txt
2. Should download only the contents (and not the HTML) like  `curl -o pgp.txt https://shaffan.dev/pgp.txt`

**Comment by zachleat** [comment]
I think there’s probably some misunderstandings here. Primarily, Eleventy does not process or copy `.txt` files to your output. So the only thing you should see in your output folder (default: `_site`) is the output from `pgp.md`. Eleventy also does not erase or delete files from `_site`. So the `/pgp` you’re seeing in your browser is likely from a previous build of `pgp.md`.

The thing you want to do, instead of using `.md` here, is to use passthrough file copy to put `pgp.txt` into your output folder: https://www.11ty.dev/docs/copy/
