### ISSUE TITLE
eleventyComputed added via config does not follow deep data merge

### ISSUE THREAD

**Issue by LeaVerou** [11ty/eleventy#3389]
_(Thanks @dmitrysharabin for debugging this issue!)_

I was using two plugins, both of which were doing something like this.

Plugin 1:

```js
config.addGlobalData("eleventyComputed", {
	foo (data) {
		// stuff
	}
});
```

Plugin 2:
```js
config.addGlobalData("eleventyComputed", {
	bar (data) {
		// stuff
	}
});
```

I expected that deep data merge should take care of merging the objects, but it turned out that each plugin was overriding the previous one.

a) This shouldn't happen and 
b) Is there a better way for plugins to add global computed data?

**Comment by zachleat** [comment]
I’ll update the docs but `addGlobalData` does take a lodash set selector.

The awkward part of `addGlobalData` is that when you pass in a function we’ll run it so when you want to _return_ a function as part of eleventyComputed you need to nest it, like so:

```js
config.addGlobalData("eleventyComputed.foo", () => {
	return (data) => { /* stuff */ };
});
config.addGlobalData("eleventyComputed.bar", () => {
	return (data) => { /* stuff */ };
});
```

I would like to improve that for `eleventyComputed` specifically but I don’t see a clear path forward yet that won’t break stuff.

The problem is this section right here: https://github.com/11ty/eleventy/blob/e45040e63c12107490ffc7d7339d5cf8b083a9ac/src/Data/TemplateDataInitialGlobalData.js#L27-L29

**Comment by zachleat** [comment]
Oh, I forgot to say to your original point: I agree that we should merge objects passed to `addGlobalData` so I’ll work on that change too.

**Comment by zachleat** [comment]
Merging of objects passed to `addGlobalData` will ship with 3.0.0-alpha.18

**Comment by zachleat** [comment]
One more note here is that this will happen independent of whether or not deep data merge is enabled. We’re trying to phase out/discourage use of the `dataDeepMerge` feature.

**Comment by zachleat** [comment]
Docs are updated: https://www.11ty.dev/docs/data-global-custom/

**Comment by LeaVerou** [comment]
Wow, that was fast! Color me impressed!
