### ISSUE TITLE
Remove support for `$INPUT/.gitignore` (0.7.0 added `$ROOT/.gitignore`)

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#364]
Breaking change, but almost certainly not necessary.

Changed in https://github.com/11ty/eleventy/issues/229#issuecomment-452213141

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
Just for extra clarity, this means we look for ignores in these files in 1.0:

```diff
$ROOT/.gitignore
- $INPUT/.gitignore
$ROOT/.eleventyignore
$INPUT/.eleventyignore
```

**Comment by szegheo** [comment]
For me, this change has made some trouble after the upgrade to 1.0 but I can understand my use-case is not typical.

For my needs (technically identical microsites) I made a private wrapper package around `11ty` and `webpack` with all my helpers, shortcodes, and a lot of custom stuff...

Because of this my `$ROOT` never matches `$INPUT` - for reason - and I cannot change this.
Since `1.0` in my `$INPUT` dir I MUST duplicate items in `.eleventyignore` because its `.gitignore` pair is ignored.

I can live with it, just wondering if some new API could bring back the old behavior or make it possible to manually add a `.gitignore` file? May I expect this feature to be added?
