### ISSUE TITLE
Documentation Request: How to Contribute to Eleventy

### ISSUE THREAD

**Issue by clottman** [11ty/eleventy#387]
I want to attempt to implement & PR a feature that I'd like to see in Eleventy. I've never worked on a Node CLI tool before though, and I'm not sure how to get started. 

Things I've done: 
1. Clone this repository locally
2. `$ cd eleventy` (cd into the new directory created by the clone)
3. `$ npm install` 
4. `$ npm run default` 
   I get the following error after this command: 
```
npm ERR! missing script: eleventy
```

If I add `"eleventy": "./cmd.js",` to the scripts/ section in package.json, I can successfully `npm run eleventy`. But since that line isn't already there, it feels like it probably isn't the way that core contributors are typically working. 

What am I doing wrong?

**Comment by clottman** [comment]
Ah! Next I ran `sudo npm link` and after that, `npm run default` runs successfully.

**Comment by zachleat** [comment]
ah I think I usually `npm install ~/Code/eleventy --save` into a project that uses it if I’m trying things locally

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for documentation requests. This means documentation issues will now be closed instead of leaving them open.

View [the documentation queue backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Areactions-%2B1-desc+is%3Aclosed+label%3Adocumentation+label%3Aneeds-votes). Don’t forget to upvote the top comment with 👍!
