### ISSUE TITLE
Use SASS (node-sass) as a template engine for CSS/SCSS files

### ISSUE THREAD

**Issue by jonsage** [11ty/eleventy#408]
It would be good to be able to optionally use node-sass as the template renderer for .css/scss files...

It seems to similar fit the same architectural pattern as any other template engine, albeit for a different type of file...

What would be the difficulty in supporting this as an option?

Thanks :)

**Comment by chrisdmacrae** [comment]
@zachleat what's the opportunity on opening a plugin API for engines?

If the engine API could be partially standardized, I think this could easily be done through plugins, allowing us to add less, sass, and more support.

**Comment by chrisdmacrae** [comment]
I see this API binding a node module to a set of file extensions. This module would basically tell eleventy how to:

- load the file
- pass data to the file
- render the file

**Comment by zachleat** [comment]
This is exactly the thing proposed by #117. After this API becomes available, we can defer this to plugins (some first party, some third party).

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by djmtype** [comment]
👍
Any site, large or small, needs sass sourcemaps.

**Comment by Kryptonov** [comment]
👍

**Comment by SimonEast** [comment]
It's been nearly 2 years since a comment on this thread, but just noting that if this does go ahead, be aware that `node-sass` is deprecated (and I could never get it to work on Windows, anyway). [`sass`](https://www.npmjs.com/package/sass) (aka "Dart SASS") is the version to use now and is pure Javascript rather than Python.

In the meantime, for those looking, I found `eleventy-plugin-sass` to be unusable (it uses the deprecated `node-sass` mentioned above), but [this guide](https://dev.to/jkc_codes/using-sass-with-eleventy-21le) was helpful in getting SASS up and running. Would be nice to see that bundled into a clean plugin, but at least I understand what it's doing.

**Comment by einomi** [comment]
Hey @SimonEast, you can check out my 11ty starter that features Gulp and Dart SASS https://github.com/frontenso/frontenso-11ty-starter

**Comment by zachleat** [comment]
This finally lives on the docs proper https://www.11ty.dev/docs/languages/sass/

A big shout to https://11ty.rocks/posts/process-css-with-lightningcss/ too
