### ISSUE TITLE
Eleventy doesn't unlink deleted files during watch

### ISSUE THREAD

**Issue by chrisdmacrae** [11ty/eleventy#409]
Eleventy does not unlink the output file associated with an input file during watch.

Given that we have a map of the input -> output permalinks, can we act on unlinks as well?

This can create issues with additional software that processes after the fact.

**Comment by zachleat** [comment]
Ah, interesting. Yeah. This is a good idea.

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by starikcetin** [comment]
I am experiencing this issue. Watch is constantly bothering me for generated source files. If you point me to the right place, I might take a stab at it.
