### ISSUE TITLE
Alphabetical Sorting

### ISSUE THREAD

**Issue by andreacorinti** [11ty/eleventy#411]
Hello! 

I'm using the great [eleventy-base-blog](https://github.com/11ty/eleventy-base-blog), and I would like to know if there is a convenient way to sort the collections alphabetically overriding the "date" yml and file creation date.

I've experimented with nunjucks and the default postlist used for tag-collections:

`{% for post in postslist | sort(attribute='post.data.title') %}`

but it does not seem to work: the posts continue to use the default "date" order! 

So I was thinking of making a custom Collection [as explained here]https://www.11ty.io/docs/collections/#advanced%3A-custom-filtering-and-sorting) but I can't understand what is the best sorting Function to use for my purposes (I still don't know JavaScript very well), any suggestions ? 

Thank you!

PS: Sorry for my English!

**Comment by okitavera** [comment]
you can just grab the `post.data.title` and sort it regularly:
```javascript
  eleventyConfig.addCollection("postsAscending", (collection) =>
    collection.getFilteredByGlob("_posts/*.md").sort((a, b) => {
      if (a.data.title > b.data.title) return -1;
      else if (a.data.title < b.data.title) return 1;
      else return 0;
    })
  );
```
- Eleventy https://github.com/11ty/eleventy/issues/338
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Comment by andreacorinti** [comment]
> you can just grab the `post.data.title` and sort it regularly:
> 
> ```js
>   eleventyConfig.addCollection("postsAscending", (collection) =>
>     collection.getFilteredByGlob("_posts/*.md").sort((a, b) => {
>       if (a.data.title > b.data.title) return -1;
>       else if (a.data.title < b.data.title) return 1;
>       else return 0;
>     })
>   );
> ```
> 
>     * Eleventy #338
> 
>     * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

it worked like a charm! thank you very much!

**Comment by StarfallProjects** [comment]
I hope it's ok to add to closed issues? This was a high result when googling this problem.

For anyone coming across this while trying to sort posts from A -> Z, and struggling to get it to work:

- Watch out for lowercase/uppercase. `sort() ` treats lowercase as "less than" uppercase.
- You may need to switch the < > in the example above.
- Make sure 11ty is happy with the path to your files.
- You may need to stop and restart (I found changes to the collection code in `.eleventy.js` weren't reliably picked up by the hot reload)

This worked for me:
```
    eleventyConfig.addCollection("conceptsAlpha", function(collection) {
        return collection.getFilteredByGlob("src/concepts/*.md").sort(function(a, b) {
            let nameA = a.data.title.toUpperCase();
            let nameB = b.data.title.toUpperCase();
            if (nameA < nameB) return -1;
            else if (nameA > nameB) return 1;
            else return 0;
        });
    });
```

Result was my three test posts in` concepts`, sorted as:
lifeworld 
Welcome 
Zebra

**Comment by Ryuno-Ki** [comment]
In case you are using non-Latin characters, you might also want to look into [localeCompare](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare).

**Comment by ritms** [comment]
Can someone please give example how to create function with localeCompare?

Code below gives error `collection.getFilteredByGlob(...).from is not a function`
```
const alphabet = ['a','ā','b','c','č','d','e','ē','f','g','ģ','h','i','ī','j','k','ķ','l','ļ','m','n','ņ','o','p','r','s','š','t','u','ū','v','z','ž'];
    eleventyConfig.addCollection("postsDescending", function(collection) {
        return collection.getFilteredByGlob("src/posts/*.md").from(alphabet).sort(function(a, b) {
           return a.localCompare(b, 'lv', { sensitivity: 'base' });
        });
    });
```

**Comment by larsingerlars** [comment]
> 

Just wanted to add that your proposed way of using the built-in Nunjucks sort filter works as expected.

Only needs a little adjustment: 
```nunjucks
{% for post in postslist | sort(false, false, "data.title") %}
```
The posts listed will be sorted alphabetically. Overriding the previous sorting order, which was probably in this case sorted by date.

Since the [sort filter as mentioned in the official Nunjucks docs can hold up to 4 arguments](https://mozilla.github.io/nunjucks/templating.html#sort-arr-reverse-casesens-attr) - **arr, reverse, caseSens and attr** - you need to pass also the other arguments, to make it work. 

The **_arr_** argument (e.g. postlist) is automatically passed to it, but both **_reverse_** and **_caseSens_** need to be passed as well to get the desired output - sorting by a particular attribute. 

Here a lengthy notation (which surprisingly did not work, when I tried it) to illustrate my explanation above:
```nunjucks
{% for post in postslist | sort(reverse=false, caseSens=false, attr="data.title") %}

// Remember: the arr argument (postlist in this case) is passed automatically and is therefore not needed inside the parenthesis
```
If anyone has an idea, why the written-out variant does not work, I would be happy to know.

**Comment by pdehaan** [comment]
@larsingerlars Does this work for you?
```njk
{% for post in collections.posts | sort(attribute="data.title") %}
  <p>{{ post.data.title }}</p>
{% endfor %}
```

This also seems to work:

```njk
{% for post in collections.posts | sort(attribute="data.title", case_sensitive=true) %}
  <p>{{ post.data.title }}</p>
{% endfor %}
```

(where I'm grabbing the attribute names from https://github.com/mozilla/nunjucks/blob/fd500902d7c88672470c87170796de52fc0f791a/nunjucks/src/filters.js#L448-L449)

You might also want to try asking on https://github.com/mozilla/nunjucks/issues since the named attributes seems Nunjucks specific and not something in Eleventy.

**Comment by larsingerlars** [comment]
@pdehaan Both variants work.

> (where I'm grabbing the attribute names from https://github.com/mozilla/nunjucks/blob/fd500902d7c88672470c87170796de52fc0f791a/nunjucks/src/filters.js#L448-L449)

Interesting. I was also checking the source code of Nunjucks filters before writing my first comment. But I only tried out the attribute names provided in the docs, not the ones used in the makeMacro function.

But you are right - this is definitely more a Nunjucks thing than related to Eleventy. Nonetheless, thanks for providing an answer.
