### ISSUE TITLE
Front matter dates using "Created" and "Last modified" not working

### ISSUE THREAD

**Issue by iampeterbanjo** [11ty/eleventy#415]
I have front matter like this
``` yaml
---
date: Created
updated: Last Modified
---
```

and it outputs `date` and `updated` as the strings "Created" and "Last modified" respectively. I expected that the dates would be parsed as per [the docs](https://www.11ty.io/docs/dates/).

When I change the front matter date to
``` yaml
---
date: 2019-01-24
---
```

The date is output as `Thu Jan 24 2019 00:00:00 GMT+0000 (Greenwich Mean Time)`. Is there a way to humanize this date format?

As a fallback I tried using JavaScript front matter like this using [Luxon formatting](https://moment.github.io/luxon/docs/manual/formatting.html)

``` JavaScript
date: function() {
    return (new Date('2019-01-24')).toLocaleString({ month: 'long', day: 'numeric', year: 'numeric' })
}
```

But I get the error 
```
[static-watch] Problem writing Eleventy templates: (more in DEBUG output)
[static-watch] > data.date.toLowerCase is not a function (TypeError):
[static-watch]     TypeError: data.date.toLowerCase is not a function
```

This is my project config if it helps

├── @11ty/eleventy@0.7.1
├── @11ty/eleventy-plugin-syntaxhighlight@2.0.1
├── autoprefixer@9.4.7
├── ejs-lint@0.3.0
├── fs-extra@7.0.1
├── good@8.1.2
├── good-console@7.1.0
├── good-squeeze@5.1.0
├── got@9.6.0
├── gulp@4.0.0
├── gulp-imagemin@5.0.3
├── gulp-less@4.0.1
├── gulp-postcss@8.0.0
├── gulp-sass@4.0.2
├── gulp-sourcemaps@2.6.4
├── hapi@18.0.0
├── inert@5.1.2
├── node-sass@4.11.0
├── nodemon@1.18.9
├── npm-run-all@4.1.5
├── precss@4.0.0
└── tachyons-sass@4.9.5

**Comment by zachleat** [comment]
```
---
date: Created
updated: Last Modified
---
```

I’m not sure what `updated` means there but using `date` will just return the YAML value for the front matter and nothing more. If you use a string, it will be that string. Eleventy performs no transformation on this variable but does use its value for other things. `date: 2019-01-24` is an actual date object because that value is converted as a YAML date.

If you’re looking for the date object of the page, try using `page.date` which is the resolved date that Eleventy uses based on your `date` front matter (or file creation date, which is the default if `date` is not specified).

Does that make sense? Your issue does make me think we should cross reference `page.date` from the content dates docs, I’ll take care of that https://www.11ty.io/docs/dates/

`page` variable docs: https://www.11ty.io/docs/data/#page-variable-contents%3A

**Comment by iampeterbanjo** [comment]
ok thanks.

**Comment by miklb** [comment]
@zachleat 4 years later and I'm my searches for now to display both `Created` and `Last Modified` for a post results in closed issues like this one. Currently `page.date` is relegated to only one option. Is there something I'm missing as to avoiding hardcoding a modified date in YAML front matter?

**Comment by aloxe** [comment]
@milkb I tried to find a way too but the `page` has only one `date` so there is no way to both have both `Created` and `Last Modified`. Hardcoding modification date in front matter is what I ended up doing.
