### ISSUE TITLE
plugin: menus

### ISSUE THREAD

**Issue by DirtyF** [11ty/eleventy#419]
`11ty-plugin-menus`helps defining and managing navigation menus.

/cc @chrisdmacrae

**Comment by Ryuno-Ki** [comment]
How do you imagine this to be used?

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
@Ryuno-Ki I’ve had questions around how 11ty.io handles its nested navigation, so a nice common use case would be that type of thing. Top level nav, secondary nav, sorting menu items in the nav, etc

**Comment by zachleat** [comment]
This is now available at https://github.com/11ty/eleventy-navigation.

I put it in the next milestone purely for release notes purposes but this is available now.
