### ISSUE TITLE
URL filter doesn't work on Windows

### ISSUE THREAD

**Issue by AndrewAsquith** [11ty/eleventy#485]
When building on Windows and using the URL filter the resulting url ends up with the windows path separator.

This just started recently, so my guess is a dependency was overwriting node's path with upath and has stopped doing that.  

The fix is to use the posix namespace in TemplatePath.normalizeUrlPath,

**Comment by d2s** [comment]
@zachleat Any idea when Eleventy `v0.8.3` will be released?
This bug is causing me issues while developing on a Windows machine.

Are there still other changes that have to be finished before it can go out?
([0.8.3 Milestone](https://github.com/11ty/eleventy/milestone/28) seems to be 100% at the moment.)
