### ISSUE TITLE
Can't load WOFF2 fonts

### ISSUE THREAD

**Issue by danchristian** [11ty/eleventy#511]
I'm having trouble getting my fonts to show. 

I have my `.woff2` files in `_includes/assets/fonts`

I then link to them in my `_includes/assets/css` file, so:

```
@font-face {
  font-family: "Feijoa";
  font-style: normal;
  font-weight: 400;
  src: url("/assets/fonts/FeijoaWeb-Medium.woff2") format("woff2");
  font-display: swap;
}

html,
body {
  font-family: "Feijoa", system-ui;
}
```

Then in `eleventy.js` I have some config for the fonts folder:

`  eleventyConfig.addPassthroughCopy("_includes/assets/fonts");`

However they are still not showing up. I've had a look around the docs and other exmaple sites and the only other example I can find using custom fonts was @paulrobertlloyd's personal website [config](https://github.com/paulrobertlloyd/paulrobertlloyd-v4/blob/e787267f5faa00e4e1150b8273ab2b1b4213033b/src/assets/styles/config/webfonts.css), which seems to have a similar set up to me.

**Comment by kleinfreund** [comment]
The fonts are static content that’s not used by Eleventy directly so the do not need to be in the `_includes` directory. Move them out into `assets/css`, adjust your passthrough copy rule accordingly and they should appear in the output directory under `_site/assets/fonts`. Your CSS already refers to the correct files.

**Comment by danchristian** [comment]
I'm using the [Eleventy + Netlify CMS Boilerplate](https://templates.netlify.com/template/eleventy-netlify-boilerplate/) so I moved them into the `static` folder and they now work! Thanks @kleinfreund

**Comment by accaplan** [comment]
Hi, I am having a similar issue and tried this. The font is on my local, woff and woff2. It works fine on my homepage. I notice in my console that it is "adding" a route and this is probably why the page can't find the font required. However, I 'm not sure what that issue lies. I was hoping someone could have a look.

[https://github.com/accaplan/eleventy-netlify-fun]

Forked from the Eleventy+ Netlify CMS Boilerplate, fonts are in the static folder.

I have added a passthrough. I am preloading in my head.njk. Using @font-face in my .css.

To reproduce: npm install
                       npx @11ty/eleventy --serve

Homepage loads with font and then click on any of the other pages and check developer tools console.

**Comment by pdehaan** [comment]
> I notice in my console that it is "adding" a route and this is probably why the page can't find the font required. However, I 'm not sure what that issue lies.

I think you got it.
The problem seems to be at https://github.com/accaplan/eleventy-netlify-fun/blob/6d940851ba35c5a7feb62182bc7531c1bbd9f967/_includes/assets/css/inline.css#L200-L201

If you add a `/` to the front of the static directory, it should always look at the absolute /static/ directory instead of a non-existent relative static/ directory.

```diff
diff --git a/_includes/assets/css/inline.css b/_includes/assets/css/inline.css
index ff890ac..5d6dfdd 100644
--- a/_includes/assets/css/inline.css
+++ b/_includes/assets/css/inline.css
@@ -197,8 +197,8 @@ button {
 }
 @font-face {
        font-family: Karrik;
-       src: url('static/fonts/Karrik-Regular.woff2') format('woff2'),
-                       url('static/fonts/Karrik-Regular.woff') format('woff');
+       src: url('/static/fonts/Karrik-Regular.woff2') format('woff2'),
+                       url('/static/fonts/Karrik-Regular.woff') format('woff');
 }
```

**Comment by accaplan** [comment]
This solved it for me! Was so close. Appreciate the tip! I followed @pdehaan advice.
