### ISSUE TITLE
pagination (in a layout) producing garbled results

### ISSUE THREAD

**Issue by smth** [11ty/eleventy#519]
When I try to limit results in a collections loop (in a Nunjucks template), ~~either~~ using pagination, ~~or `.slice()`,~~ the unwanted items are geting dumped at the end of the document, along with everything that would follow them (closing tags).

So if I am limiting to two items, I get something like:

```html
<html>
  <head>
  </head>
  <body>

    <main>
      <article>
        <p>Item one</p>
      </article>

      <article>
        <p>Item two</p>
      </article>
    </main>

    <footer>
    </footer>
  </body>
</html>

 partial content of item three</p>
 </article>
<article>
  <p>Item four</p>
</article>
<article>
  <p>Item five</p>
</article>
</main>
<footer>
</footer>
</body>
</html>
```

**Comment by kleinfreund** [comment]
Please tell us how you produce this output.

**Comment by smth** [comment]
It seems to reproduce this you'd have to have conflicting templates. I had a second template file (that I thought I'd deleted) trying to resolve to the same location. Things are working as expected now I have removed that template, so will close this issue.

**Comment by smth** [comment]
I spoke too soon @kleinfreund, it still happens with pagination. I've put my code here https://github.com/smth/11ty-pagination-issue

You might find that when running the server you need to make a change before you see the issue.

**Comment by kleinfreund** [comment]
Pretty sure this is a bug with pagination. Chaning around the `size: 2` property in the front matter affects the results in strange ways. What I can tell so far: Before the pagination can finish to insert its HTML, the surrounding document is closed or something. Maybe something to do with asynchronous code?

**Comment by smth** [comment]
It does seem to be pagination specific. I'm not getting it with `.slice(0, 2)`.

**Comment by kleinfreund** [comment]
Can you try something? Open your `home.njk` template and remove the `alias: news` key from the front matter. Use `pagination.items` in the for loop instead of `news`. Does that fix the output?

**Comment by zachleat** [comment]
Great test case—thanks!

Here’s the issue:

<img width="518" alt="image" src="https://user-images.githubusercontent.com/39355/59558175-bfb7fc00-8fb1-11e9-88ec-aa11645a24e2.png">

Note that `home.md` has the following front matter:
<img width="310" alt="image" src="https://user-images.githubusercontent.com/39355/59558199-158ca400-8fb2-11e9-87c4-be9e2fb71440.png">

Note that when it combines with the layout’s front matter, it looks _something_ like this:
```
---
title: 'Home'
permalink: /
layout: "layouts/home.njk" (which points to) layouts/base.njk
pagination:
  data: collections.news
  size: 2
  alias: news
---
```

That means that every pagination page is going to try to write to `/`.

Changing `permalink` to this will fix it:

```
permalink: /{% if pagination.pageNumber > 0 %}page-{{ pagination.pageNumber }}/{% endif %}
```

and give you this:
<img width="553" alt="image" src="https://user-images.githubusercontent.com/39355/59558205-51c00480-8fb2-11e9-9bd9-5e12f352e6d3.png">

In the next minor version this will be much more obvious, because writing to the same file multiple times will result in an error: Read more at https://github.com/11ty/eleventy/issues/562

**Comment by zachleat** [comment]
Read more about permalink and pagination here: https://www.11ty.io/docs/pagination/#remapping-with-permalinks
