### ISSUE TITLE
How to render raw HTML on page?

### ISSUE THREAD

**Issue by danchristian** [11ty/eleventy#523]
I am getting raw HTML from my CMS that I want to render as code on the page - not a string of HTML - but actual rendered code. I can't find much and my attempts at using Shortcodes are half working. Perhaps I've misunderstood what Shortcodes are meant for?

**eleventy.js**
```
eleventyConfig.addShortcode("testCode", function(code) {
    return `<div class="some-class">{% code %}</div>`;
});
```

**page.njk**
{% testCode code %}

**Firefox**
`{% code %}`

**Dev Tools**
`<div class="some-class">{% code %}</div>`

**What I expect in Dev Tools**
`<div class="some-class"><p>Test Code</p></div>`

**What I expect in Firefox**
`Test Code`

**Comment by AndrewAsquith** [comment]
based on your example, assuming that in your page the code variable contains `<p>Test Code</p>`

your shortocde just needs to interpolate "code" properly and should be
``return `<div class="some-class">${code}</div>`;``

**Comment by danchristian** [comment]
Of course, now looking at it in the morning with fresh eyes. Not sure why I ever expected my code to work.

All working now, thanks @AndrewAsquith

**Comment by jsimplicio** [comment]
@AndrewAsquith How do you assign something to ${code}?

**Comment by pdehaan** [comment]
@jsimplicio 

> How do you assign something to ${code}?

The `code` variable could come from your frontmatter or directory/global data file, or anywhere fine data is found. The `${…}` syntax is just the JavaScript [template literals (template strings)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) syntax when using backticks (<code>`</code>) instead of single or double quotes for a string (to interpolate values).
