### ISSUE TITLE
Error-out on failure with `eleventy --serve`

### ISSUE THREAD

**Issue by shreyasminocha** [11ty/eleventy#525]
Since `eleventy --serve` continues to attempt to generate output and does not error-out on failures, I'm often confused by how making changes doesn't seem to reflect on the output only to realise that an error was encountered long back but the server continued to serve an old copy of the output. I use [hotel](//github.com/typicode/hotel), which will display a clear error message in the browser when attempting to access the site after the server crashes with an non-zero error code. 

Having `eleventy --serve` error-out on failure (at least by default) would be awesome.

**Comment by Ryuno-Ki** [comment]
Hm, I can see your point …
But a crash would make you restart `eleventy` by hand, wouldn't it?

**Comment by shreyasminocha** [comment]
@Ryuno-Ki better than staying in the illusion that my code's output isn't updating for some mysterious mistake of mine :)

**Comment by Ryuno-Ki** [comment]
Hm, I'm biased.
Yeah, I ran into the same situation (my broken template didn't get updated because of an error), but I'd rather expect to keep eleventy running in watch mode, so I could fix it without switching to a terminal again and again.
For me, the issue lies into _too much logging after an error_.
Maybe there would be a way to fold them („N lines suppressed”) without hiding _all_ output?

**Comment by jevets** [comment]
You can opt into only a few of Eleventy's modules for debug messages.
https://www.11ty.io/docs/debugging/

I often run locally:

```
DEBUG=Eleventy:TemplateContent,Eleventy:EleventyErrorHandler npx eleventy --serve
```

I agree I'd rather let Eleventy keep running during these errors, since I often fix em pretty quickly. But it would certainly be useful to have some kind of notifier either in the browser or OS notification or even a terminal chime of sorts when an error pops up so you know it happened.

**Comment by Ryuno-Ki** [comment]
Like https://github.com/alextucker/grunt-growl ?

Maybe @zachleat can steal from there?

**Comment by zachleat** [comment]
Here is @stowball’s comment from #542 (hopefully we can combine his issue with this one):

---

Currently, unless you're watching the terminal output on every save, you have no idea if you've accidentally introduced a syntax error to your templates because for all intents and purposes, the browser reloads and appears to have worked. Unfortunately, it just reloads with the last good, cached version, which then causes extra frustration as you try to debug new code which you think should be rendered, but isn't.

Here's an example of what happens on an "unsuccessful" save:

```sh
File changed: _includes/components/header/link-level-1.ejs
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering ejs template ./style-guide/header.ejs (TemplateContentRenderError)
> ./style-guide/header.ejs:2
    1|
 >> 2| <%- include('../_includes/components/header/index'); %>

…

Processed 0 files in 0.03 seconds
Watching…
[Browsersync] Reloading Browsers...
```

which, apart from the number of files processed, is essentially the same as what happens on a successful save.

What I'd like to see is something like what Create React App does, where the error is logged to both the terminal and the browser, like this:

![image](https://user-images.githubusercontent.com/853552/58368117-d5468280-7f2b-11e9-9111-297e40e03e87.png)

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by stowball** [comment]
I wonder how much effort it is to integrate a tool like [node-notifier](https://github.com/mikaelbr/node-notifier) to throw an OS notification on error?

**Comment by kleinfreund** [comment]
I do not wish for a development tool to trigger any kind of notification, especially not on the OS level.

**Comment by stowball** [comment]
We could make it configurable and off by default?

It could be a semi-decent stopgap…?

**Comment by edwardhorsford** [comment]
I've run across this too a few times - eleventy has crashed, but everything seems normal.

I don't much mind the solution, but agree _something_ would be good. Notifications / stop serving / serve error, etc.

**Comment by zachleat** [comment]
https://twitter.com/stevenpetryk/status/1246614147749384195

**Comment by stevenpetryk** [comment]
Hey folks, here's an (incomplete) PR to get the error overlay into the core. Feedback on some decisions, as well as advice on how/what to test would be much appreciated.

https://github.com/11ty/eleventy/pull/1070

**Comment by patricknelson** [comment]
It'd be awesome if we had at least _some_ kind of way to easily listen to errors on our own via our `.eleventy.js` config. Maybe at minimum some kind of simple API, like an error callback we can pass so we can do something on our own.  As a new user, I'm having some difficulty with this myself and I tried looking up existing solutions and landed here. However, the `eleventy-plugin-error-overlay` is nearly 2yrs old and is already broken (per https://github.com/stevenpetryk/eleventy-plugin-error-overlay/issues/3).

For example, I just want a simple terminal bell notification. That way, if I hear the bell sound I can at least know something went wrong instead of wasting time wondering why nothing is happening. Others may prefer something more OS integrated like [node-notifier](https://github.com/mikaelbr/node-notifier) or the overlay in #1070. This would at least be a great little v1.1 stopgap until something a bit more robust comes along later on. 🤔

**Comment by stevenpetryk** [comment]
Oh I didn't even notice it was broken. Lol. I'll see if I can fix it soonish.

**Comment by patricknelson** [comment]
Thanks @stevenpetryk!

p.s. I'm digging into this a bit and I was wondering: Does this only render errors that end up in `EleventyErrorHandler`? Right at this particular moment I'm primarily focused on seeing errors associated with one of the SASS compiling plugins, `eleventy-plugin-sass`. From what I can tell, when it errors, 11ty doesn't know about it at all.

This makes me wonder: Is there no standard way for plugins to hand off errors to 11ty? I was considering issuing a PR on that plugin to ensure it uses `eleventyInstance.errorHandler.error(error, error.message);` instead of letting `gulp-sass` log the error so that (in the outer layers, i.e. in `.eleventy.js`) you can attach your own event listeners, or utilize 11ty's API's to avoid having to dig deep into the inner guts of these plugins.

**Comment by patricknelson** [comment]
Here's my attempt at fixing it, @stevenpetryk: https://github.com/stevenpetryk/eleventy-plugin-error-overlay/pull/4

Maybe @zachleat we could work on incorporating events for improved error handling? For example, allowing the ability to emit and subscribe to events like `eleventy.error`, `eleventy.warn` and `eleventy.fatal`.  This could be via the standard `eleventyConfig.on(...)` syntax which is exposed both to plugins and `.eleventy.js`, making it reasonably accessible to everyone and hopefully _far easier_ to reason about in the future. 

Fundamentally, the issue I'm encountering here is due to a lack of standardized API for communicating errors. For example:  The  specific approach that plugin `eleventy-plugin-error-overlay` above has to use right now to listen to errors is to [monkey-patch](https://github.com/stevenpetryk/eleventy-plugin-error-overlay/blob/v1.0.2/index.js#L44-L45) over `EleventyErrorHandler.error` (and other core methods) to essentially override it with a custom wrapper. I feel like it might be far easier to reason about if we just used an event-based model to handle these situations. I've seen this pattern arise elsewhere [in other plugins](https://github.com/Sonaryr/eleventy-plugin-sass/blob/master/index.js#L29-L37), too.

This would also be _super_ useful in situations where you have other plugins that need to _emit_ errors that this plugin could render for us. In the long term, instead of calling or overriding core 11ty methods, plugins (and regular users) could just communicate with events, just to hopefully make things a little less complicated.

What do you think? 🤔
