### ISSUE TITLE
Throw an error when multiple files have the same permalink

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#562]
Starting in 0.9.0, Eleventy will warn when multiple files try to write to the same output file but I think this should probably be an error.

Related: #322

**Comment by zachleat** [comment]
Docs at https://www.11ty.io/docs/permalinks/#remapping-output-(permalink)

**Comment by edwardhorsford** [comment]
My build just failed when upgrading to 0.9.0 due to this (and my code).

Error looked like this:
<img width="1063" alt="Screen Shot 2019-10-27 at 15 03 09" src="https://user-images.githubusercontent.com/2204224/67636675-ed4f7300-f8ca-11e9-87d8-4e84437cd18b.PNG">

So a _single_ template threw this error. I've eventually tracked it down - I had a tag used with two capitalisations - so pagination tried to write out that tag page twice.

I wonder if anything could be done to watch out for these situations?

**Comment by starikcetin** [comment]
> My build just failed when upgrading to 0.9.0 due to this (and my code).
> 
> Error looked like this: <img alt="Screen Shot 2019-10-27 at 15 03 09" width="1063" src="https://user-images.githubusercontent.com/2204224/67636675-ed4f7300-f8ca-11e9-87d8-4e84437cd18b.PNG">
> 
> So a _single_ template threw this error. I've eventually tracked it down - I had a tag used with two capitalisations - so pagination tried to write out that tag page twice.
> 
> I wonder if anything could be done to watch out for these situations?

I am also getting a similar error. What is going on?

```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] Output conflict: multiple input files are writing to `dist/projects/categories/cicd/index.html`. Use distinct `permalink` values to resolve this conflict.
[11ty]   1. ./src\projects\categories\_pggenerated\cicd.pug
[11ty]   2. ./src/projects/categories/_pggenerated/cicd.pug (via DuplicatePermalinkOutputError)
```
