### ISSUE TITLE
Allow specifying of timezone in .eleventy.js

### ISSUE THREAD

**Issue by Ryuno-Ki** [11ty/eleventy#573]
I'm currently looking into porting my blog posts to eleventy.

Therefore I noticed, that the default timezone is `utc`:
https://github.com/11ty/eleventy/blob/f014f56f26c3df71de3520558c0034e9cae8fb59/src/Template.js#L609

Would it be possible to define another timezone in `.eleventy.js` and have it respected in Template.js?
To me, it's about CET / CEST (so a per-post option, i.e. frontmatter would be neat).

**Comment by Ryuno-Ki** [comment]
Related to #413

**Comment by zachleat** [comment]
What functional benefit would this provide?

**Comment by Ryuno-Ki** [comment]
I could leave away the timezone shift in `date` frontmatter for blog posts.

Plus, scheduled posts would benefit from it.

**Comment by chriskrycho** [comment]
I'd actually be curious if it'd be feasible to let the user specify how they want the date to be parsed—I'd much prefer to be able to use Luxon's `fromSQL`, for example. I have a long-standing habit (thanks to [my previous static site generator experience][pelican]) of writing my dates like `date: 2019-11-18 06:17`. Switching from that to `2019-11-18T06:17:00T-0700` is… not great. 😆 It's definitely *better* if you're using an actual CMS like Netlify CMS or Forestry, but part of the appeal of tools like Eleventy is that they don't *require* that. The UTC default is a good *default*, but perhaps something like this?

Using a standard format/helper:

```js
eleventyConfig.parseDateWith(Luxon.fromSQL)
```

Doing your own thing, because for some reason you really like writing out your dates like `Monday, November 18, 2019 @ 6:20AM`:

```js
eleventyConfig.parseDateWith(date => DateTime.fromFormat(
  "EEEE, MMMM d, yyyy @ h:mma",
  { zone: "America/Denver" },
);
```

The type of that config argument (for those like me who are inclined that way) would just be a function `(date: string) => Luxon.DateTime`.

If that proposal seems reasonable, I may be able to poke at it a bit and implement it sometime this week or next. I would get a lot of value out of it myself, and I imagine it would be useful to others as well.

[pelican]: https://blog.getpelican.com

**Comment by Ryuno-Ki** [comment]
Hm, your example isn't [stftime-formatted](http://www.strftime.net/), is it?
I'd like to use [date-fns' parser](https://date-fns.org/v2.7.0/docs/parse) if possible.

**Comment by chriskrycho** [comment]
It definitely isn't. I used my old style of string as an example because it *does* parse with Luxon's `DateTime.fromSQL`, and I used Luxon examples in general because that's what 11ty is using for all of this internally at present. Really, given that it all ends up with a JS `Date` object, the implementation could actually just let the user supply *any* way of building a JS date, i.e. a function of `string => Date`. So my above examples would be something like this:

```js
eleventyConfig.parseDateWith(dateString => DateTime.fromSQL(dateString).toJSDate())

eleventyConfig.parseDateWith(date =>
  DateTime.fromFormat(
    "EEEE, MMMM d, yyyy @ h:mma",
    { zone: "America/Denver" },
  ).toJSDate()
);
```

**Comment by zachleat** [comment]
Moving this into the enhancement queue.

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by nhoizey** [comment]
I'm (still) struggling with timezones in Eleventy… 😅

In my Markdown files, Front Matter is written like this:

```yaml
date: 2020-10-15 01:02:19 +02:00
```

Eleventy (via Luxon?) converts it to `2020-10-14T23:02:19.000Z`.

*(I don't really understand how it works as it seems Luxon's `DateTime.fromISO()` should not be able to parse the date format I use… 🤔)*

I would like to keep the original date to get a `15` instead of a `14` in the permalink for example, because I wrote it on the 15th, not the 14th.

I'm in Paris, GMT+2 in summer, GMT+1 in winter. I can live with GMT+2 dates all year, but I've had issues with wrong day numbers a few times since I use Eleventy, it's frustrating.

**Comment by zachleat** [comment]
Sorry about this confusion @nhoizey! Keep in mind that YAML has their own date specific parsing that you might be hitting up against.

![image](https://user-images.githubusercontent.com/39355/153074182-c64ca5c8-705e-42f8-81ca-24fe5402da22.png)

If you want to use Luxon parsing instead, force a string in your front matter:
![image](https://user-images.githubusercontent.com/39355/153074246-ea549b4f-2722-4771-a943-88bfa587eae5.png)

**Comment by nhoizey** [comment]
@zachleat TIL! 👍 (maybe once again, I tend to forget such subtleties…)

I'm writing dates without quotes, so it looks like YAML understands it as a date, but converts it to UTC, right?

I know Eleventy uses Luxon, so is it recommended to write dates with quotes?
Will it make Eleventy keep the timezone from my YAML, like with Luxon's `{ setZone: true }` in `fromISO()` or `fromJSDate()` functions?

**Comment by nhoizey** [comment]
I think I've managed to get the intended result with Luxon and these two functions I call first when computing dates:

```javascript
const isoToDateTime = (date, lang = 'en') =>
  DateTime.fromISO(date, { setZone: true })
    .setZone('Europe/Paris')
    .setLocale(lang);

const jsToDateTime = (date, lang = 'en') =>
  DateTime.fromJSDate(date, { setZone: true })
    .setZone('Europe/Paris')
    .setLocale(lang);
```

There are a few ways I use them here: https://github.com/nhoizey/nicolas-hoizey.com/blob/main/src/_utils/dates.js

**Comment by praesongprasit** [comment]
@nhoizey Your suggestion worked for me!! Thank you. I've been scratching my head over this for ages.

**Comment by zachleat** [comment]
The home base for this one moved to #3668!
