### ISSUE TITLE
Filters: how to get access to additional params when used in a content?

### ISSUE THREAD

**Issue by borisschapira** [11ty/eleventy#579]
Hi! I don't know if it's a bug or if I missed something in the configuration…
Here's the code I'm talking about: https://github.com/borisschapira/eleventy-base-blog/commit/5469387b718068e6caae299093b173ae8b88359b

I made a universal filter named test, that take two parameters: the input it's applied on and an additional one. In a template, everything works ok. But when I use the filter inside a content (in this example, the first post), the parameter becomes `undefined`.

![Capture d’écran 2019-06-20 à 07 33 51](https://user-images.githubusercontent.com/284742/59838530-5a686000-934f-11e9-8d7c-73bf30d3d817.png)

I don't understand why…

**Comment by jevets** [comment]
I think it's because you're calling `include` from an `njk` file, but the include uses `liquid` syntax.

Eleventy currently doesn't have a universal `include` (one that's agnostic to template languages).

**Comment by borisschapira** [comment]
I've tried with `njk` template, I've also tried to change the `markdownTemplateEngine` to `njk` in the configuration. Nothing works.

**Comment by jevets** [comment]
1. Nunjucks won't process/compile an included file that's written in a different template language.
It's like including a PHP file from a JS file and expecting it to work. I *think* this is the problem you're facing.
`nunjucks: {% include 'liquid-file.liquid' %}`: you're trying to use two different languages.
Try switching to `_includes/test.njk` instead of liquid (and change the syntax to njk).

2. A nunjucks `include` should have its filename quoted, as well:
`{% include 'my-quoted-filename.njk' %}`


3. If you're only using the filter in the one include file and nowhere else, you probably don't need the filter; you could just rely on `include`s.

**Comment by borisschapira** [comment]
Oh, I understand, thanks Steve, it works!

![Capture d’écran 2019-06-21 à 22 37 08](https://user-images.githubusercontent.com/284742/59950054-30a95900-9475-11e9-8c62-2be969d11f96.png)

> If you're only using the filter in the one include file and nowhere else, you probably don't need the filter; you could just rely on `includes`.

I plan on using my filter multiples times, I'm using it as a translation filter:

```
locale: en_US
---
{{ "Year" | translate(locale) }} 
{# => Year #}
```

```
locale: fr_FR
---
{{ "Year" | translate(locale) }} 
{# ==> Année #}
```
