### ISSUE TITLE
page.fileSlug on index.11ty.js templates

### ISSUE THREAD

**Issue by reubenlillie** [11ty/eleventy#588]
Is there a reason that `page.fileSlug` is not returning the parent directory name for `index.11ty.js` templates? (See https://www.11ty.io/docs/data/#fileslug)

When using `permalink: {{page.fileSlug}}/index.html` (inherited from a template directory JSON file) in `index.11ty.js` templates,  the output file is being saved in a directory named `{{page.fileSlug}}` rather than the actual parent directory name.

**Comment by jevets** [comment]
I think it's because `.11ty.js` files don't support front matter (yes, even though it's not YAML front matter and even though it is in a separate JSON file). Something similar tripped me up the other day.

https://www.11ty.io/docs/languages/javascript/#optional-data-method

Happy to have a look / stab if you've got a repo available

**Comment by zachleat** [comment]
Note that `permalinks` render with the sample template language as the parent template. So the `{{ page.fileSlug }}` syntax would only be available on Liquid and Nunjucks templates.

Check out the docs for permalink examples specific to 11ty.js templates: https://www.11ty.io/docs/languages/javascript/#permalinks

That being said, I did add a test case around this and even when you’re using it correctly it was reporting the wrong thing! It was reporting `slug.11ty` and not `slug`. This will be fixed in the next version.

**Comment by hayatbiralem** [comment]
I just made a related comment on #642, maybe it helps someone. Here is [the comment](https://github.com/11ty/eleventy/issues/642#issuecomment-1231352819).
