### ISSUE TITLE
Add MDX support

### ISSUE THREAD

**Issue by chrisdmacrae** [11ty/eleventy#636]
MDX support would open 11ty up to the react ecosystem in an extremely elegant way for 11tys current landscape. 

MDX can be added into vanilla JS projects without a bundler by using babel and react Dom directly. 

It would allow users to:

- Map react components to markdown syntax, allowing us to customize the output HTML of markdown
- Use JSX directly in markdown
- Import JavaScript directly into templates and content files

Caveats:

- People will expect or build in dynamic functionality that won't work for prerendered HTML from react
- Generating a bundle to deal with the above caveat gets complicated. 

https://mdxjs.com/getting-started#do-it-yourself

**Comment by Ryuno-Ki** [comment]
Related to #117?

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by MadeByMike** [comment]
I've got you covered here: https://github.com/jamshop/eleventy-plugin-mdx

**Comment by zachleat** [comment]
Official docs deploying to https://www.11ty.dev/docs/languages/mdx/

Shipping with 3.0.0-alpha.11

Very open to others adding alternate approaches there, via plugins or otherwise! (Already added Mike’s plugin in the community links)
