### ISSUE TITLE
Allow includes directory to contain sub folders

### ISSUE THREAD

**Issue by paulrobertlloyd** [11ty/eleventy#72]
Hey Zach! Trying this out, as I’ve long hoped for a good-as-Jekyll-but-in-Node static site generator, and this project looks very promising. In attempting to convert my Jekyll site, have come across an issue where it would appear that includes can’t be organised in sub-directories.

For example, in a document I have: `{% include form/contact %}`

However, the following error suggests sub-directories are not recognised:

`Failed to lookup form.liquid in: src/_includes`.

Is this the case? If so, can I make a feature request to allow for the includes directory to contain sub-folders… or will that break things?

**Comment by zachleat** [comment]
Hey @paulrobertlloyd! Well, that’s disappointing—sorry! I assume you’re sticking with Liquid syntax there? I know it works as expected in Nunjucks.

Note that there are a few minor differences between Ruby Liquid and the liquidjs library we’re using here (unfortunately). This looks to be one of them.

I’ve filed issues upstream with them in the past and they’ve been very good about fixing! See also https://github.com/harttle/liquidjs/issues/51

I’ll plan on filing one for this a little later (or you can, if you want to beat me to it).

**Comment by zachleat** [comment]
Filed in https://github.com/harttle/liquidjs/issues/61

Thanks!

**Comment by zachleat** [comment]
The other option we have here is to expose an API to configure liquid rendering options so that individual applications could override `dynamicPartials` to `true`. This would require that all includes paths be quoted as strings.

**Comment by zachleat** [comment]
Alright, I added 16 new tests for this, 9 of which are currently skipped in the test suite but will apply after https://github.com/harttle/liquidjs/issues/61 is fixed.

For now (after Eleventy 0.2.15 is released), you can use the Configuration API to enable `dynamicPartials` in the liquid options, and this will work as expected—but **will require all of your include paths to be quoted.**. So, instead of `{% include form/contact %}` you’d need to do `{% include "form/contact" %}`.

Your `.eleventy.js` config file might look something like this:

```
module.exports = function(eleventyConfig) {
  eleventyConfig.setLiquidOptions({
    dynamicPartials: true
  });

  // your other config stuff
};
```

I’m tempted to make this the default, but want to make Jekyll migrations as easy as possible—so I’ll probably end up banking on this being easier if it’s fixed upstream in `liquidjs` for now.  Hope this is an ok solution for you!

**Comment by zachleat** [comment]
Closing this, filed a longer term issue for the upstream fix here if you’d like to subscribe: https://github.com/11ty/eleventy/issues/73

**Comment by paulrobertlloyd** [comment]
Wow, thanks @zachleat! Still investigating 11ty, but if I were to migrate I’d likely move to using Nunjucks soon after. But in terms of being able to support Jekyll sites, I think this is a really helpful addition. Thanks again!
