### ISSUE TITLE
Apache Content Negotiation and Eleventy

### ISSUE THREAD

**Issue by rachelandrew** [11ty/eleventy#761]
There is a method of internationalizing content which uses Apache Content Negotiation - explained in [this post](http://fantasai.inkedblade.net/web-design/l10n).

To do this you need to name your files with a language code eg about/history.en.html, about/history.fr.html and then linking to about/history uses a rewrite to return the version for the language of the user.

I am working on a site where they wish to use this method and I really want to use Eleventy. I can use the overrides in Eleventy to create the named files, but then this makes actually working with the site in development impossible, as all my links go to the bare main file name (e.g. about/history) and there is no way to go to the internationalized versions.

If anyone has any ideas as to how I can get this working I would be very grateful. I'm aware there are other ways of doing internationalization, I'm interested as to whether this one is possible.

**Comment by Ryuno-Ki** [comment]
Related to #243 and #420: We should keep this use case in mind when tackling i18n.

**Comment by adamduncan** [comment]
Hey @rachelandrew, really interesting approach!

I've made up a proof-of-concept repo ([eleventy-l10n-demo](https://github.com/adamduncan/eleventy-l10n-demo)), which includes the files/config to support the approach explained in the post you referenced.

We can get creative with Eleventy's `permalink`, and how we author and output `.htaccess` files. That should result in us having the `LANGCODE.html` suffixes we're after in the site output. Some nice ideas out there around [maintaining relative links](https://github.com/11ty/eleventy/issues/648#issuecomment-596718708) in Eleventy sites, too!

This demo site leverages [Netlify's `redirects`](https://docs.netlify.com/routing/redirects/) to achieve the same as what we'd configure with `.htaccess` in Apache (see [demo's `netlify.toml`](https://github.com/adamduncan/eleventy-l10n-demo/blob/master/netlify.toml)):

https://eleventy-l10n-demo.netlify.app/
https://eleventy-l10n-demo.netlify.app/about

[Quick Accept-Language Switcher](https://addons.mozilla.org/en-GB/firefox/addon/quick-accept-language-switc/) is handy for ensuring the language settings are being honoured (`en`, `ja` and `es` in this case).

I hope that helps you or someone else exploring this approach. Definitely one to keep in mind as an alternative to a [more manual i18n approach](https://github.com/adamduncan/eleventy-plugin-i18n). Thanks for highlighting it! 👍

**Comment by zachleat** [comment]
Sorry I’m so late to this party but I was able to dig into this today and made a few changes as a result.

For this style of approach I do think it’s better to swap your default permalink behavior to use `.html` instead of `index.html` for everything, so I’d start there:

https://www.11ty.dev/docs/data-eleventy-supplied/#changing-your-project-default-permalinks

The new stuff I added for this use case specifically is available on the docs here: https://www.11ty.dev/docs/permalinks/#mapping-one-url-to-multiple-files-for-internationalization

I think this will clean up the example you linked to a bit @adamduncan in that you don’t need to hardcode permalinks throughout your files and you will be able to use `page.url` (et al) as expected without other changes.

I’m at close of business today but I’m curious to hear y’alls thoughts!

**Comment by zachleat** [comment]
This is now officially discussed on our new i18n docs page https://www.11ty.dev/docs/i18n/ though we really recommend the `folder` based approach for file organization but both will work!

**Comment by fromjasonstuff** [comment]
@zachleat sorry if this isn't the place to ask, still getting use to github. I was wondering why the folder approach is recommended for file organization over an extensionless url like described in [this article](https://btrem.com/2021/02-content-type-11ty). I'm trying to decide what is best and honestly have no idea.
