### ISSUE TITLE
Eleventy favorite markdown editor

### ISSUE THREAD

**Issue by TigersWay** [11ty/eleventy#765]
Hi,
As the title says, I am wondering if anyone found an open-source markdown-it based editor?

Any tip, idea... is always welcome!

**Comment by dixonge** [comment]
Your title doesn't mention open source, but your comment does. I'm using Typora, but while it's free in beta it's not open source, I don't think. Code is on Github tho...

Main reason I love this editor is because the editor is also a live preview - just as soon as you type modifiers (like bold, italic, etc.) the code disappears and you just see the words bolded or italicized. If you want to get back to raw markdown you can toggle that on and off. I find I like it better than having a separate pane for preview.

**Comment by TigersWay** [comment]
> Your title doesn't mention open source, but your comment does. I'm using Typora, but while it's free in beta it's not open source, I don't think. Code is on Github tho...

Yes, I clearly hesitated.... I also use Typora, because nothing better, and no, there is no source on github!

I am still dreaming about some markdown editor or fork of it, which would allow "us" to use eleventy path of images, use current css theme file(s), etc... Just being a dreamer :-/

**Comment by brycewray** [comment]
Note also the Typora-like [Mark Text](https://marktext.app/), which is open-source (MIT-licensed).

**Comment by dixonge** [comment]
> Note also the Typora-like [Mark Text](https://marktext.app/), which is open-source (MIT-licensed).

Wow, didn't even know you could do diagrams in Markdown! This looks like a great app. Downloading now. If it can handle opening/navigating folders better than Typora I'm all in!

Gracias.

**Comment by TigersWay** [comment]
Nice application, but not happy yet...
- I still prefer the markdown/source button of Typora
- and like Typora, can't really succeed to manage images, uploaded or already local.

**Comment by TigersWay** [comment]
Have been writing too quickly, and discovered:
- typora-copy-images-to
- typora-root-url

Not ideal, but much better!

**Comment by zachleat** [comment]
Thanks for the discussion! Feel free to keep posting here after this issue is closed

**Comment by nhoizey** [comment]
@TigersWay I'm a little late in this discussion, but I wanted to mention the Markdown editor I use: [MacDown]()

It's not based on Markdown-it though, and only works on macOS.

For images, which seem to be one of your main concerns:

I keep them either in the same folder as my Markdown files:
https://github.com/nhoizey/nicolas-hoizey.com/tree/master/src/articles/2017/10/27/chrome-fails-showing-big-emojis

Or in a shared one:
https://github.com/nhoizey/nicolas-hoizey.com/tree/master/src/assets/logos

So that I can use simple relative or absolute URLs in Markdown for images.

In the example above, there's this for the shared logo:

```markdown
![Chrome logo](/assets/logos/chrome.png){.logo}
```

And this for the article illustration:

```markdown
![](chrome-emoji-65px-scale-2-either.png "Chrome doesn't show a `65px` emoji scaled twice either")
```

The logo is unfortunately not shown, but the illustrations are:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/78213/77899943-9a188c80-727d-11ea-8147-23e8fdd743b3.png">

**Comment by DirtyF** [comment]
If you're looking for a way for editors to edit Markdown, you can import your eleventy website in [forestry.io](https://forestry.io) which provides a simple user interface to edit Commnomark, JSON, or YAML files.

![eleventy-forestry](https://user-images.githubusercontent.com/103008/77912064-2fbe1700-7292-11ea-9458-b5acd496d429.png)

**Comment by nhoizey** [comment]
I can confirm that Forestry is really nice for content authors, I'm already using it for one site with authors without any technical knowledge. 👍

**Comment by diogeneshamilton** [comment]
Following up here- I just got TinaCMS (formerly Forestry) working locally with Eleventy, and liking it! Probably going to use this as my flow locally for now, and then perhaps deploy this to edit my site from anywhere.

**Comment by diogeneshamilton** [comment]
Additionally playing around with https://reprose.pp.ua, which might be a bit slimmed down and easier to integrate into my flow. https://github.com/jmas/reprose
