### ISSUE TITLE
--serve without BrowserSync OR --watch with a built-in Web Server

### ISSUE THREAD

**Issue by hteumeuleu** [11ty/eleventy#770]
Hello! I'm new to Eleventy and so far liking it. The one thing I hate though is the use of BrowserSync. It makes everything super slow, doesn't work on older browsers and makes it harder to audit pages for web performance. 

Is there a way to use Eleventy without BrowserSync? I run my site locally using the default command (`npx @11ty/eleventy --serve`).

**Comment by ogdenstudios** [comment]
I don't know about configurable options off the top of my head, but you could change up your workflow to be: 

1. Make changes 
2. Run the `npx @11ty/eleventy` (without `--serve`) 
3. Point your browser to the eleventy `_site` folder 
4. Reload the pages there 

Since 11ty generates a static site, you don't even really need a server to be running - your browser should be able to connect to the flat files by themselves.

**Comment by zachleat** [comment]
Are you familiar with `eleventy --watch`? I use this when I have sites already running on my local Apache

**Comment by hteumeuleu** [comment]
I didn't know about `--watch`, and that might do it for now. But I like the fact that `--serve` builds its own local server. Is this fundamentally impossible to dissociate with BrowserSync or more something you don't mind about because it's more of an edge case?

**Comment by zachleat** [comment]
Naw it’s certainly in the realm of possibility. This is the first time I’ve heard this feedback though!

We do have a mechanism in place to override me for these things, it’s the enhancement queue. I’ll restructure this issue and move this into the queue.

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by hteumeuleu** [comment]
Thank you!

**Comment by edwardhorsford** [comment]
I've wondered before about turning off browsersync too whilst keeping the serve portion.

**Comment by chbrandt** [comment]
I open two terminals, in one I run `--serve`, in the other I run `--watch`. Works fine.

**Comment by zachleat** [comment]
Circling back here we do have a custom server api now and this task shipped with #1305 .

Thanks, y’all!

Docs https://www.11ty.dev/docs/dev-server/
