### ISSUE TITLE
Null date throws an error

### ISSUE THREAD

**Issue by dceddia** [11ty/eleventy#786]
**Describe the bug**
I'm converting an existing Jekyll blog to Eleventy. I have some pages that have an empty `date` in the frontmatter, and Eleventy is crashing with the error `Cannot read property 'toLowerCase' of null`.

**To Reproduce**
1. Create this file:

```markdown
---
title: "This blows up"
date:
---
```
2. Run eleventy
3. Boom
```
TypeError: Cannot read property 'toLowerCase' of null
    at Template.getMappedDate (/Users/dceddia/.n/lib/node_modules/@11ty/eleventy/src/Template.js:606:23)
    at async Template.addPageDate (/Users/dceddia/.n/lib/node_modules/@11ty/eleventy/src/Template.js:256:19)
    at async Template.getData (/Users/dceddia/.n/lib/node_modules/@11ty/eleventy/src/Template.js:237:20)
    at async Template.getTemplateMapEntries (/Users/dceddia/.n/lib/node_modules/@11ty/eleventy/src/Template.js:673:16)
    at async TemplateMap.add (/Users/dceddia/.n/lib/node_modules/@11ty/eleventy/src/TemplateMap.js:32:21)
    at async Promise.all (index 0)
    at async TemplateWriter._createTemplateMap (/Users/dceddia/.n/lib/node_modules/@11ty/eleventy/src/TemplateWriter.js:123:3)
    at async TemplateWriter.write (/Users/dceddia/.n/lib/node_modules/@11ty/eleventy/src/TemplateWriter.js:155:3)
    at async Eleventy.write (/Users/dceddia/.n/lib/node_modules/@11ty/eleventy/src/Eleventy.js:428:13)
```

**Expected behavior**
I expected the empty date to be ignored. For some posts or pages the date isn't relevant and I don't want to show it on the page at all. Maybe there's a better way to do this? 

**Environment:**
 - OS and Version: macOS Catalina 10.15.1
 - Eleventy Version 0.9.0

**Additional context**
Near where it fails, in `Template.js`, I can fix the crash by changing this line:
```js
if ("date" in data) {
```
to this:
```js
if ("date" in data && data.date) {
```
Should I create a PR? Is there a better way to fix it?

**Comment by ogdenstudios** [comment]
Looks like your fix works and it definitely feels clear. There's a check around line  625 for validity: 

```
         if (!date.isValid) {
            throw new Error(
              `date front matter value (${data.date}) is invalid for ${this.inputPath}`
            );
          }
```

Which makes me feel like checking other types of validity is within the scope of the `getMappedDate` function. 

But let's say we wanted to avoid a change? Does it break convention to have front matter fields that are empty? What happens if you change it to: 

```
date: ""
```

Instead of just entirely blank? Is it more conventional to *explicitly state that you have left this date blank*? Or again, is it better to take the date field out if it's unused? 

I don't really have any answers or opinions for these questions, but maybe just some prompts to get discussion going about how Eleventy should handle this case in general. 

In the short term, would it fit into your workflow to remove the empty frontmatter for now and avoid the errors?

**Comment by dceddia** [comment]
Yeah those are good questions. The blank file template I'm using came stock with... octopress, I think? And they have a bunch of empty frontmatter fields that Jekyll silently ignores, so I always just left them alone. It does seem a bit odd to have blank fields though, and maybe it'd be clearer (for my own posts) if I left off the `date` and added a field like `timeless: true` or something.

**Comment by ogdenstudios** [comment]
I mean, I support adding `timeless: true` to all your posts, if only for the confidence boost.

**Comment by ogdenstudios** [comment]
Did a little thinking and a little reading, and I think you should submit your PR and see what @zachleat thinks. 

[YAML treats empty nodes as `null`](https://yaml.org/spec/1.2/spec.html#id2786563). Since Eleventy defaults to YAML in its templates, I think it ought to treat YAML the way YAML wants to be treated. 

But the `date` node is given special consideration in [Template.js](https://github.com/11ty/eleventy/blob/master/src/Template.js), through the `getMappedDate` function. This special consideration (attempting to parse front matter with the `date` node in a specific way) is what's causing the error. I think Eleventy would do well to handle the valid YAML value of `null` with the check you've proposed. 

I have a feeling Jekyll doesn't do anything with `date` by default, which is part of why this doesn't throw an issue there.

**Comment by edwardhorsford** [comment]
I had a similar issue with _null_ tags - [which I raised in this issue](https://github.com/11ty/eleventy/issues/556).

Likewise I have a template markdown file with mostly blank keys - date always throws an error first time.

If date isn't *required* by eleventy, I would support empty keys being ignored (like tags was above).

**Comment by zachleat** [comment]
Yep I’m on board with this—take care not to change any existing unit tests in your pull request please! I want to know if anything fails
