### ISSUE TITLE
OpenCollective alternative for non-Credit Card users

### ISSUE THREAD

**Issue by Ryuno-Ki** [11ty/eleventy#797]
Hooray for https://twitter.com/eleven_ty/status/1197550926636158982

@zachleat asked me to [fill a ticket](https://twitter.com/eleven_ty/status/1197615928424435714) to see, whether my „problem” with it gets some resonance with the community.

I don't have (nor want) a credit card. Same goes for PayPal etc.
This excludes me from pretty much everything eCommerce.

Except for some parts of Europe (where I happen to live). Here I have (often, not always) the possibility to pay with bank transfer / SEPA.
I was in touch with [Web Archive](https://archive.org) and learned that I could donate money via SWIFT there.

Do you know alternatives (no, cryptocurrencies don't count) for contributing money to Open Source projects like eleventy?

**Comment by zachleat** [comment]
Haven’t heard very much about folks needing this but I did look into the other options that OpenCollective has and it seems like they’ve probably added a few new options since this was filed.

Specifically: https://docs.opencollective.com/help/fiscal-hosts/bank-transfers

Gonna close this one for now but it’s still great to have it in the search results on the issue tracker!

Thanks!
