### ISSUE TITLE
Syntax errors in global data files breaks the watcher

### ISSUE THREAD

**Issue by dwightjack** [11ty/eleventy#833]
**Describe the bug**

I am using a global data file inside a `_data` folder to share global links and info on the website.

When running eleventy in watch mode, if when I save the file the content has a syntax error the watcher errors and seems to stop.

While this is totally fine in a build process I am not sure it's so good during development.  

**To Reproduce**

1. Add a new global data file `demo.js` with the content:

```js
module.exports = {
    hello: 'worldx'
}
```

2. Print the hello property data in a Nunjucks template: `{{ demo.hello }}`
3. Change the content to something broken:

```js
module.exports = {
    hello 'worldx // removed ending '
}
```

4. Console errors:

```
Eleventy fatal watch error: (more in DEBUG output)
> Invalid or unexpected token (SyntaxError):
        hello: 'world
               ^^^^^^

    SyntaxError: Invalid or unexpected token
```

5. Fixing the error does not trigger the watcher anymore

**Expected behavior**

I'd expect the watcher to be still running

**Screenshots**

**Environment:**

- OS and Version: Mac 10.14
- Eleventy Version 0.8.3

**Additional context**

**Comment by jediyozh** [comment]
I think a have something similar when I try `{% if page.url === /about/ %}` and have error in wathcer:
```
Error writing templates:
 unexpected token: /
```

Is there some workaround for it?

**Comment by stevenpetryk** [comment]
I opened that PR ⬆️ but it wasn't solving the real problem. The real problem is that when a fatal error like this is encountered, Eleventy bails out of the watcher on these lines:

https://github.com/11ty/eleventy/blob/8ffbb9927ea8482c5a46515f3a2ed25cd8830ad8/src/Eleventy.js#L441-L443

In other words, when an error is encountered, the build is never marked as "finished", so subsequent builds are simply cancelled. Updating my PR now :)

**Comment by stevenpetryk** [comment]
All better! https://github.com/11ty/eleventy/pull/1071

**Comment by zachleat** [comment]
This wil ship with 1.0, thank you!
