### ISSUE TITLE
Are there limitations when using {% include "..." %} ?

### ISSUE THREAD

**Issue by wsw70** [11ty/eleventy#868]
I have just started to use Eleventy and tried to build a simple test page with Bootstrap and Nunjucks. My problem is with the various `{% include "..." %}`.

The general skeleton of the `index.njk` page is

```
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "head.njk" %}
</head>
<body>
    {% include "nav.njk" %}
    <a href="testing">wazaa</a>

    {% include "footer.njk" %}
</body>
</html>
```

With only these three includes, I hit two different issues :)

## `footer.njk` : 👍 

```
this is the footer

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
```

- This generates `_site/footer/index.html` 
- and this file is correctly included in the resulting `_site/index.html`

**→ expected behaviour**

##  `nav.njk` 👎 

```
<nav class="navbar navbar-expand-lg navbar-light bg-light">
(... the generic navbar from Bootstrap docs ...)
</nav>
```

- This generates a correct `_site/nav/index.html` 
- but that file is **not** included in the resulting `_site/index.html`. It is just not there where it shoud be: between `<body>` and the `wazaa` link.

##  `head.njk` 👎 👎 

```
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<title>{% page.title %}</title>
```

- This generates **an empty**  `_site/head/index.html` 
- and it may or may not be included in  the resulting `_site/index.html` - I do not know because the file is empty anyway.

---

I am really at loss here, not really knowing where to  go from there with such unexpected issues.

The [documentation for `include`](https://mozilla.github.io/nunjucks/templating.html#include) may state something about that, but I do not understand the exact consequences and do not know whether this is relevant:

> An included template does not participate in the block structure of its including template; it has a totally separate inheritance tree and block namespace. In other words, an include is not a pre-processor that pulls the included template code into the including template before rendering; instead, it fires off a separate render of the included template, and the results of that render are included.

**Comment by cdowdy** [comment]
Hey @wsw70 hopefully I can lend a little!  Hopefully I haven't assumed to much, but Im probably a little verbose :) 

Heres a snippet of the 11ty docs for includes for nunjucks.  https://www.11ty.dev/docs/languages/nunjucks/#supported-features  

> 
> Feature | Syntax
> -- | --
> ✅ Includes | {% include 'included.njk' %} looks in _includes/included.njk. Does not process front matter in the include file.
> ✅ Includes (Relative Path) New in v0.9.0 | Relative paths use ./ (template’s directory) or ../ (template’s parent directory).Example: {% include './included.njk' %} looks for included.njk in the template’s current directory. Does not process front matter in the include file.


 I don't know which version of 11ty you're running but with my local copy of v0.10.0 it will error out trying to include any of the above included files. The directory structure looks as follows so if its different from yours please tell me!    

```  
11ty
├───node_modules
├───src
│   └───site
│       │   footer.njk
│       │   index.njk
│       │   nav.njk
|       |   head.njk
│   .eleventy.js
│   package-lock.json
│   package.json
         
```

since none of those use a relative path. We will need to create an includes directory to satisfy the first table row  in the above quoted portion of the 11ty docs and nunjucks. We will also move the footer, nav and header includes there:  

```
├───src
│   └───site
│       │   index.njk
│       │   
│       └───_includes
|               | nav.njk
|               | footer.njk
|               | head.njk
```
that way when 11ty is ran it will pull those files from the ``_includes`` directory.  

If you'd rather not have the ``_includes`` directory you'd then need to add a relative path to all your includes:  

``` twig 
    {% include "./head.njk" %}

    {% include "./nav.njk" %}

    {% include "./footer.njk" %}  
```

To start from the "top down" of your index page. 

__head.njk__  
you're trying to get the title of the page like below. 
```twig
<title>{% page.title %}</title>    
```   
but you're using the wrong tags. You'll need to use a double brace. 

```twig  
<title>{{ page.title }}</title>  
```  
The "title" is also a bit of front matter that you'll be pulling in from another page - this instance the index.njk page -. 

Which moves us to the ``index.njk`` page. 

here is the index.njk page now:  

```twig  
---
page:  
    title: homepage
---  
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "head.njk" %}
</head>
<body>
    {% include "nav.njk" %}
    <a href="testing">wazaa</a>

    {% include "footer.njk" %}
</body>
</html>
```  

I added a bit of front matter to the top of the page. now when you access ```{{ page.title }}``` from your included files you should get that. You could also strip out the page.title part in the head include and use ```{{ title }}``` but you'd need to switch from an array   

```yaml  
---
page:  
    title: homepage
---  
```  
to a single key: 
```yaml  
---
title: homepage
---   

hopefully this helped a bit and I wasn't completely wrong! if not someone else may come across and find it useful!

**Comment by wsw70** [comment]
Thank you for the extensive help!

I initially went for the basic example (creating everything in the project root directory) but then, following your advice, went for a `src` folder. And a local installation of Eleventy, per the docs.

Actually reading the link you provided helped to understand how everything should be organized. Starting from scratch I reproduced your setup (and indeed could not include like in my initial explanation).

Thank you for all, I will continue form that point on.

**Comment by Ryuno-Ki** [comment]
Basically, `{{ }}` is for interpolating (that is, print value of a variable) and `{% %}` are for tags, i.e. execute some code (like a for loop or an include).
